### ISSUE TITLE
Candy Machine file issue

### ISSUE THREAD

**Issue by Starmoon9800** [metaplex-foundation/metaplex#1010]
Whenever I run the command to use the candy machine cli I get this error:

PS C:\Users\willy\Solana-Mint> npx ts-node ~/Solana-Mint/metaplex/js/packages/cli/src/candy-machine-cli.ts -h
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './candy-machine-cli.ts'
Require stack:
- C:\Users\willy\Solana-Mint\~\Solana-Mint\metaplex\js\packages\cli\src\imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
91:40)
    at main (C:\Users\willy\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:193:27)
    at Object.<anonymous> (C:\Users\willy\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:351:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\willy\\Solana-Mint\\~\\Solana-Mint\\metaplex\\js\\packages\\cli\\src\\imaginaryUncacheableRequireResolveScript'
  ]
}

Can someone please steer me in the right direction?

**Comment by Acidastro** [comment]
i have exactly the same problem. I can't solve it for several hours. help us please

**Comment by barelooksrare** [comment]
`ts-node` wants to run a script at a certain path. Windows doesn't implicitly know what you mean by '~', as a Unix systems would, so it interprets the Unix-style path `~/Solana-Mint/metaplex/js/packages/cli/src/candy-machine-cli.ts` referenced from the `C:\Users\willy\Solana-Mint\` directory as a relative path and therefore combines the paths to try to look for this monster:

`C:\Users\willy\Solana-Mint\~\Solana-Mint\metaplex\js\packages\cli\src\candy-machine-cli.ts`

This is because in a Windows, '~' is not an implicit reference to the home directory, but PS has a feature that it you press tab just after typing it, it'll resolve it to the Windows absolute path (analogous to the home directory): 

`PS C:\Users\willy\Solana-Mint> npx ts-node ~/Solana-Mint/metaplex/js/packages/cli/src/candy-machine-cli.ts`
<PRESS TAB>
`PS C:\Users\willy\Solana-Mint> npx ts-node C:\Users\willy\Solana-Mint\metaplex\js\packages\cli\src\candy-machine-cli.ts`

Then you'll probably run into a bunch of dependency errors until you've run `yarn` or `npm install` from the `C:\Users\willy\Solana-Mint\metaplex\js\packages\cli\` directory.

**Comment by amritabithi** [comment]
I am having this issue on Ubuntu 20 Linux also with the project just cloned today.

**Comment by KrehyDev** [comment]
I tried `npm install` from `js\packages\cli` but without any change.

**Comment by barelooksrare** [comment]
You can't possibly be getting the same error. This error can only occur on Windows running ts-node from poweshell:

PS C:\Users\willy\Solana-Mint> npx ts-node ~/Solana-Mint/metaplex/js/packages/cli/src/candy-machine-cli.ts -h
node:internal/modules/cjs/loader:936
throw err;

Please

**Comment by amritabithi** [comment]
I got the same exception, obviously different path names, because to compile a dependency I had to be root and that placed a file in the root user folder not the web user I had set up.  But no you are right, I totally  imagined fixing that and made it up to come post here just for something to do. 

It means the config file it is trying to read is in the wrong place so relative pathnames weren't working using the home tilde.  I use absolute paths now tomy solana .cli and it works now.

**Comment by amritabithi** [comment]
I mean, I *imagined* that it works now because I never actually experiennced that error.

**Comment by KrehyDev** [comment]
In macOS
I get this error message


internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './candy-machine-cli.ts'
Require stack:
- /Users/krehy/Documents/VisualStudio/metaplex/js/package/cli/src/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at requireResolveNonCached (/usr/local/lib/node_modules/ts-node/dist/bin.js:321:16)
    at getProjectSearchDir (/usr/local/lib/node_modules/ts-node/dist/bin.js:291:40)
    at main (/usr/local/lib/node_modules/ts-node/dist/bin.js:193:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin.js:351:5)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/krehy/Documents/VisualStudio/metaplex/js/package/cli/src/imaginaryUncacheableRequireResolveScript'
  ]
}



after run command
`ts-node js/package/cli/src/candy-machine-cli.ts upload ./assets —env devnet —keypair ~/config/solana/devnet-test.json
`

**Comment by amritabithi** [comment]
I would try changing your command to use all absolute full pathnames and rule out the possibility of the relative paths not pointing to the right place.

**Comment by KrehyDev** [comment]
I replace `js/package/cli/src/candy-machine-cli.ts` with full path and its work now. Thank you! 

But I can't understand why, because I was try run this command without full path in the past and it was working.

**Comment by amritabithi** [comment]
If you had to switch users or use the "su" command to switch to superuser ( I am not familiar with macs so it may be different ) at any time during the build, or built the project as a normal user and are then running it as root, then one of the builds may have output files to a different "home" directory for the other user.  

For example if you are running the app while changed to superuser or logged in as "root" then the current "home" directory will be /root/ instead of /home/youruser/ .

I had this issue because my OS puts one of the dependency files in to a folder that is owned by the root user on my system, so to run the app I must be logged in as root to have the right permissions to load all of the file includes.  So to fix it I just have to use the full path names to my normal user's home directory because that is where I built everything, and run as root.

( I could probably fix it so it so everything loads from the normal user's home directory but I just wanted to get running for now to test with, in production when my app is live I will fix this properly if I can to keep it clean and not running as root. )

**Comment by angushk** [comment]
I've also got the similar issue, typed the Windows path didn't solve the problem.

C:\>ts-node C:\solnft\metaplex-foundation\metaplex\js\packages\cli\src\candy-machine-cli.ts help
C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:4:25 - error TS2307: Cannot find module 'commander' or its corresponding type declarations.

4 import { program } from 'commander';
                          ~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:5:25 - error TS2307: Cannot find module '@project-serum/anchor' or its corresponding type declarations.

5 import * as anchor from '@project-serum/anchor';
                          ~~~~~~~~~~~~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:6:19 - error TS2307: Cannot find module 'node-fetch' or its corresponding type declarations.

6 import fetch from 'node-fetch';
                    ~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:15:41 - error TS2307: Cannot find module '@solana/spl-token' or its corresponding type declarations.

15 import { Token, TOKEN_PROGRAM_ID } from '@solana/spl-token';
                                           ~~~~~~~~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:16:45 - error TS2307: Cannot find module '@solana/web3.js' or its corresponding type declarations.

16 import { PublicKey, LAMPORTS_PER_SOL } from '@solana/web3.js';
                                               ~~~~~~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:44:17 - error TS2307: Cannot find module 'loglevel' or its corresponding type declarations.

44 import log from 'loglevel';
                   ~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:49:25 - error TS2307: Cannot find module 'mime' or its corresponding type declarations.

49 import { getType } from 'mime';
                           ~~~~~~

    at createTSError (C:\Users\T06880CSD\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:750:12)
    at reportTSError (C:\Users\T06880CSD\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:754:19)
    at getOutput (C:\Users\T06880CSD\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:941:36)
    at Object.compile (C:\Users\T06880CSD\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1243:30)
    at Module.m._compile (C:\Users\T06880CSD\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\T06880CSD\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticText: "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m4\x1B[0m:\x1B[93m25\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'commander' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m4\x1B[0m import { program } from 'commander';\r\n" +
    '\x1B[7m \x1B[0m \x1B[91m                        ~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m5\x1B[0m:\x1B[93m25\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '@project-serum/anchor' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m5\x1B[0m import * as anchor from '@project-serum/anchor';\r\n" +
    '\x1B[7m \x1B[0m \x1B[91m                        ~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m6\x1B[0m:\x1B[93m19\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'node-fetch' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m6\x1B[0m import fetch from 'node-fetch';\r\n" +
    '\x1B[7m \x1B[0m \x1B[91m                  ~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m15\x1B[0m:\x1B[93m41\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '@solana/spl-token' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m15\x1B[0m import { Token, TOKEN_PROGRAM_ID } from '@solana/spl-token';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                                        ~~~~~~~~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m16\x1B[0m:\x1B[93m45\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '@solana/web3.js' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m16\x1B[0m import { PublicKey, LAMPORTS_PER_SOL } from '@solana/web3.js';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                                            ~~~~~~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m44\x1B[0m:\x1B[93m17\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'loglevel' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m44\x1B[0m import log from 'loglevel';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                ~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m49\x1B[0m:\x1B[93m25\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'mime' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m49\x1B[0m import { getType } from 'mime';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                        ~~~~~~\x1B[0m\r\n',
  diagnosticCodes: [
    2307, 2307,
    2307, 2307,
    2307, 2307,
    2307
  ]
}

**Comment by angushk** [comment]
I've also got the similar issue, typed the Windows path didn't solve the problem.

C:\>ts-node C:\solnft\metaplex-foundation\metaplex\js\packages\cli\src\candy-machine-cli.ts help
C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:4:25 - error TS2307: Cannot find module 'commander' or its corresponding type declarations.

4 import { program } from 'commander';
                          ~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:5:25 - error TS2307: Cannot find module '@project-serum/anchor' or its corresponding type declarations.

5 import * as anchor from '@project-serum/anchor';
                          ~~~~~~~~~~~~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:6:19 - error TS2307: Cannot find module 'node-fetch' or its corresponding type declarations.

6 import fetch from 'node-fetch';
                    ~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:15:41 - error TS2307: Cannot find module '@solana/spl-token' or its corresponding type declarations.

15 import { Token, TOKEN_PROGRAM_ID } from '@solana/spl-token';
                                           ~~~~~~~~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:16:45 - error TS2307: Cannot find module '@solana/web3.js' or its corresponding type declarations.

16 import { PublicKey, LAMPORTS_PER_SOL } from '@solana/web3.js';
                                               ~~~~~~~~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:44:17 - error TS2307: Cannot find module 'loglevel' or its corresponding type declarations.

44 import log from 'loglevel';
                   ~~~~~~~~~~
metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:49:25 - error TS2307: Cannot find module 'mime' or its corresponding type declarations.

49 import { getType } from 'mime';
                           ~~~~~~

    at createTSError (C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:750:12)
    at reportTSError (C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:754:19)
    at getOutput (C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:941:36)
    at Object.compile (C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1243:30)
    at Module.m._compile (C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\XXXXXXXXXX\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticText: "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m4\x1B[0m:\x1B[93m25\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'commander' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m4\x1B[0m import { program } from 'commander';\r\n" +
    '\x1B[7m \x1B[0m \x1B[91m                        ~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m5\x1B[0m:\x1B[93m25\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '@project-serum/anchor' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m5\x1B[0m import * as anchor from '@project-serum/anchor';\r\n" +
    '\x1B[7m \x1B[0m \x1B[91m                        ~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m6\x1B[0m:\x1B[93m19\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'node-fetch' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m6\x1B[0m import fetch from 'node-fetch';\r\n" +
    '\x1B[7m \x1B[0m \x1B[91m                  ~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m15\x1B[0m:\x1B[93m41\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '@solana/spl-token' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m15\x1B[0m import { Token, TOKEN_PROGRAM_ID } from '@solana/spl-token';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                                        ~~~~~~~~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m16\x1B[0m:\x1B[93m45\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module '@solana/web3.js' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m16\x1B[0m import { PublicKey, LAMPORTS_PER_SOL } from '@solana/web3.js';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                                            ~~~~~~~~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m44\x1B[0m:\x1B[93m17\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'loglevel' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m44\x1B[0m import log from 'loglevel';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                ~~~~~~~~~~\x1B[0m\r\n' +
    "\x1B[96mmetaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts\x1B[0m:\x1B[93m49\x1B[0m:\x1B[93m25\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2307: \x1B[0mCannot find module 'mime' or its corresponding type declarations.\r\n" +
    '\r\n' +
    "\x1B[7m49\x1B[0m import { getType } from 'mime';\r\n" +
    '\x1B[7m  \x1B[0m \x1B[91m                        ~~~~~~\x1B[0m\r\n',
  diagnosticCodes: [
    2307, 2307,
    2307, 2307,
    2307, 2307,
    2307
  ]
}

**Comment by leastgs** [comment]
I'm having the same problem. MacOS m1

**Comment by leastgs** [comment]
I solved it by downgrading node.js

**Comment by amritabithi** [comment]
Try node version 14.17.0 specifically and it should work.

To set the version use:
nvm use 14.17.0 --default

**Comment by isactrick2g** [comment]
> I replace `js/package/cli/src/candy-machine-cli.ts` with full path and its work now. Thank you!
> 
> But I can't understand why, because I was try run this command without full path in the past and it was working.

how did you do that? please tell me im stuck. how do you replace with full path? thank you in advance!

**Comment by amritabithi** [comment]
> 

If you are on linux, you can view your current working directory by typing the command  pwd  which stands for 'print working directory.'  

If I am under a normal user called "amrita" and I use the pwd command I should see the output:
**amrita@localhost:~$  pwd
/home/amrita**

However if I have run a command during my build that required me using "sudo" or "su" to run as root, I may now be under the root user's working directory.  You can see this by switching to the root user with the command:  **sudo su -**
Which should output:
**amrita@localhost:~$ sudo su -
[sudo] password for amrita: 
root@localhost:~# pwd
/root
root@localhost:~#**

You can always get the full pathname to the current directory by typing the " pwd " command to help with copying and pasting those paths in to your code easily.

At least for my computer's setup, I have to use sudo for certain things and I may have installed a library under the wrong user at some point, so for now I just need to make sure switch to my home directory again, so my output would be like:
**root@localhost:~# pwd
/root
root@localhost:~# cd /home/amrita
root@localhost:/home/amrita# pwd
/home/amrita
root@localhost:/home/amrita#**

At the end of that output you can see I end up back in my normal user's home directory, /home/amrita, and so when I run my commands they will be pointing to the right folder to run from.

**Comment by ArguableExorcist8** [comment]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './candy-machine-cli.ts'
Require stack:
- /Users/macbookpro/metaplex/imaginaryUncacheableRequireResolveScript
    at requireResolveNonCached (/usr/local/lib/node_modules/ts-node/dist/bin.js:321:16)
    at getProjectSearchDir (/usr/local/lib/node_modules/ts-node/dist/bin.js:291:40)
    at main (/usr/local/lib/node_modules/ts-node/dist/bin.js:193:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin.js:351:5)
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/macbookpro/metaplex/imaginaryUncacheableRequireResolveScript'
  ]
}

**Comment by amritabithi** [comment]
> node:internal/modules/cjs/loader:936 throw err; ^
> 
> Error: Cannot find module './candy-machine-cli.ts' Require stack:
> 
> * /Users/macbookpro/metaplex/imaginaryUncacheableRequireResolveScript
>   at requireResolveNonCached (/usr/local/lib/node_modules/ts-node/dist/bin.js:321:16)
>   at getProjectSearchDir (/usr/local/lib/node_modules/ts-node/dist/bin.js:291:40)
>   at main (/usr/local/lib/node_modules/ts-node/dist/bin.js:193:27)
>   at Object. (/usr/local/lib/node_modules/ts-node/dist/bin.js:351:5)
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/Users/macbookpro/metaplex/imaginaryUncacheableRequireResolveScript'
>   ]
>   }

First I suggest double checking that you are currently in the proper directory by using the command " pwd " which should show your metaplax folder, otherwise change directories back to metaplex with the following:
cd /home/YOURUSER/metaplex

Also, try node version 14.17.0 specifically and it should work.

To set the version use:
nvm use 14.17.0 --default

Always check these two things before starting to build or rebooting, on my system it reverts to the OS's built-in node version 10.x constantly but I have not figured out why I just do the above steps when I build.

**Comment by ArguableExorcist8** [comment]
Done that and now it's saying

[ERR] error: unknown command 'upload'

**Comment by amritabithi** [comment]
Its hard to tell without the full error output, but unknown command upload would tell me that there is a relative pathname that is not working properly.  

I suggest replacing the relative pathnames in your command with all full pathnames, and save these commands to a text file so you can paste them easily the next time and not have to figure out the full path again.

I think that with this software, any time you get any problem first check node version ( run 14.17.0 ) and see what relative pathnames are in use either in config files or on the command line, and convert them to the full path names.

**Comment by amritabithi** [comment]
( Also try issuing the command without the use of "sudo" if you are using sudo, and see if that recognizes the command without it being run as sudo. )

**Comment by ArguableExorcist8** [comment]
> ( Also try issuing the command without the use of "sudo" if you are using sudo, and see if that recognizes the command without it being run as sudo. )

macbookpro@MacBooks-MacBook-Air src % ts-node ./candy-machine-cli.ts upload ./assets --env mainnet-beta -keypair ~/config/solana/mainnet-beta.json
[ERR] error: unknown command 'upload'



still the same thing

**Comment by amritabithi** [comment]
> > ( Also try issuing the command without the use of "sudo" if you are using sudo, and see if that recognizes the command without it being run as sudo. )
> 
> macbookpro@MacBooks-MacBook-Air src % ts-node ./candy-machine-cli.ts upload ./assets --env mainnet-beta -keypair ~/config/solana/mainnet-beta.json [ERR] error: unknown command 'upload'
> 
> still the same thing

First you should try re-installing the solana cli tools from here - https://docs.solana.com/cli/install-solana-cli-tools

Then you can try making sure you are on node v14.17.0 first, then repeat these steps:
```
$ cd metaplex/js
$ yarn install && yarn bootstrap && yarn build
$ yarn start
```

Then try to run the command again and see if it recognizes solana cli.

**Comment by amritabithi** [comment]
( Also for anybody reading this, I suggest documenting your build steps meaning make a text file with the exact steps you take and when it works save those steps and refer to them later.  This is a must with solana as the build can break for numerous reasons, so if you are successful building and starting the app absolutely save those build steps to a file for yourself before going any further, it is a MUST. )

**Comment by ArguableExorcist8** [comment]
![error](https://user-images.githubusercontent.com/83228542/148249331-17210ac9-35e4-472e-bd6e-42e0f51118f7.png)

**Comment by amritabithi** [comment]
> ![error](https://user-images.githubusercontent.com/83228542/148249331-17210ac9-35e4-472e-bd6e-42e0f51118f7.png)

Are you intending to connect to the mainnet?  If you are still in the testing phase you will want to run this command and rebuild:
```
# Change to devnet
solana config set --url devnet
```

**Comment by ArguableExorcist8** [comment]
No mine is mainnet

**Comment by amritabithi** [comment]
> No mine is mainnet

It may be an issue with ardrive uploads if you require tokens or something to do that with ardrive, and the same for regular solana function calls they would need solana in the wallet to work I believe.  I have not yet put anything on the mainnet so I am not sure how to help past that point, other than to recommend trying it on the testnet and see if you still get errors, and fix it on testnet first just to iron it out.

**Comment by Rooseveltthedev** [comment]
Anyone figure out what the issue is? im having the same issue even after trying the full path.

![image](https://user-images.githubusercontent.com/35243275/149063040-21f1c8d3-98e2-4bdb-b739-1a00d94b6b35.png)

**Comment by ehteshaxm** [comment]
Did anyone get the solution?

**Comment by amritabithi** [comment]
> Did anyone get the solution?

Some have.  

1) Replace your relative paths in your command with absolute paths, I don't care if it seems like it shouldn't matter.

2) Make sure your node version is 14.17.0, every single time you cannot build.

    To set the node version use:
    nvm use 14.17.0 --default

3) Check that you are running the command from the proper directory, use the command "pwd" to print your current working directory.

4) Make sure that you have set your project to use devnet if that is what you are trying to use, with the command:

    solana config set --url devnet

**Comment by piermarcob** [comment]
I just would like to leave here my experience about this: My exception was as the one from @angushk.
Apparently, when cloning metaplex and installing it with `yarn`, being in the wrong directory will not make you install it properly.
Just be sure to follow [this](https://docs.opensea.io/docs/part-2-installing-the-metaplex-cli).
