### ISSUE TITLE
_bn !== undefined after the update_candy_machine command

### ISSUE THREAD

**Issue by sammyngy** [metaplex-foundation/metaplex#1035]
Hello, After a couple retries, of deleting resinstalling all the metaplex folder, I still have this issue : 

` src git:(master) ✗ Sudo npx ts-node ./candy-machine-cli.ts \
    update_candy_machine \
    --env devnet \
    --keypair ~/.config/solana/devnet.json \
    --price 1 \
    --date "26 Sep 2021 00:12:00 GMT"
wallet public key: mywalletKey

/Users/sammy/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:29
  return (value as PublicKeyData)._bn !== undefined;
                                  ^
TypeError: Cannot read property '_bn' of undefined
    at isPublicKeyData (/Users/sammy/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:29:35)
    at new PublicKey (/Users/sammy/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:45:9)
    at /Users/sammy/metaplex/js/packages/cli/src/candy-machine-cli.ts:765:26
    at step (/Users/sammy/metaplex/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/Users/sammy/metaplex/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/Users/sammy/metaplex/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

This error appear after running this command : 

`sudo npx ts-node ./candy-machine-cli.ts \
    update_candy_machine \
    --env devnet \
    --keypair ~/.config/solana/devnet.json \
    --price 1 \
    --date "26 Sep 2021 00:12:00 GMT"`

I have the 'symbols' and creator 'address' in each json of my png, I would like to understand how to fixe this error

Thanks you

**Comment by sammyngy** [comment]
fix, I had to create the candy machine, check if you have the 'candyMachineAddress' in you .cache file
