### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by JamisonO** [metaplex-foundation/metaplex#1057]
I try to generate some NFTs by punching `ts-node ~/Desktop/BlockchainWorkshop/NFTs/KillerKlowns/metaplex/js/packages/cli/src/candy-machine-cli.ts create_generative_art -n 10` into the terminal and it returns this:

```
Loaded configuration file
/Users/"User"/Desktop/BlockchainWorkshop/NFTs/KillerKlowns/metaplex/js/packages/cli/src/helpers/metadata.ts:43
  while (numberOfFilesCreated < premadeCustoms.length) {
                                               ^
TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (/Users/"User"/Desktop/BlockchainWorkshop/NFTs/KillerKlowns/metaplex/js/packages/cli/src/helpers/metadata.ts:43:48)
    at step (/Users/"User"/Desktop/BlockchainWorkshop/NFTs/KillerKlowns/metaplex/js/packages/cli/src/helpers/metadata.ts:44:23)
    at Object.next (/Users/"User"/Desktop/BlockchainWorkshop/NFTs/KillerKlowns/metaplex/js/packages/cli/src/helpers/metadata.ts:25:53)
    at fulfilled (/Users/"User"/Desktop/BlockchainWorkshop/NFTs/KillerKlowns/metaplex/js/packages/cli/src/helpers/metadata.ts:16:58)
```
And here's my json:
```

{
    "name": "Klown #",
    "symbol": "KK",
    "description": "Killer Klowns",
    "seller_fee_basis_points": 1000,
    "creators": [
        {
            "address": "912MZwwQ9W9PYgmM57Tq4LBDTHuUjbPYJcgzRhrTjBfa",
            "share": 100
        }
    ],
    "collection": {
        "name": "Killer Klowns",
        "family": "Killer Klowns"
    },
    "breakdown": {
        "background": {
            "background.gif": 1
        },
        "body": {
            "bum.gif": 0.08,
            "circus1.gif": 0.07,
            "circus2.gif": 0.07,
            "cowboy.gif": 0.04,
            "doctor.gif": 0.01,
            "gold.gif": 0.05,
            "jester.gif": 0.03,
            "joker.gif": 0.09,
            "mime.gif": 0.02,
            "pierrot.gif": 0.07,
            "santa.gif": 0.01,
            "silver.gif": 0.46
        },
        "mouth": {
            "bum.gif": 0.01,
            "frown.gif": 0.09,
            "joker.gif": 0.04,
            "mask.gif": 0.1,
            "mime.gif": 0.09,
            "monster.gif": 0.07,
            "pennywise.gif": 0.1,
            "smile.gif": 0.08,
            "smile2.gif": 0.09,
            "zombie.gif": 0.33
        },
        "eyes": {
            "bum.gif": 0.04,
            "circle1.gif": 0.01,
            "circle2.gif": 0.05,
            "cross.gif": 0.06,
            "crosscolored1.gif": 0.03,
            "crosscolored2.gif": 0.03,
            "evil.gif": 0.04,
            "glasses.gif": 0.05,
            "mime.gif": 0.06,
            "normal.gif": 0.02,
            "pennywise.gif": 0.06,
            "shades.gif": 0.01,
            "tears.gif": 0.03,
            "triangle.gif": 0.02,
            "trianglecolored1.gif": 0.05,
            "trianglecolored2.gif": 0.05,
            "zombie.gif": 0.39
        },
        "hair": {
            "afro.gif": 0.05,
            "arrow.gif": 0.02,
            "bald.gif": 0.06,
            "beret.gif": 0.05,
            "bouler.gif": 0.05,
            "bum.gif": 0.03,
            "cowboy.gif": 0.02,
            "doctor.gif": 0.03,
            "jester.gif": 0.05,
            "joker.gif": 0.03,
            "mohawk.gif": 0.01,
            "pennywise.gif": 0.02,
            "pierrot.gif": 0.04,
            "point.gif": 0.03,
            "pointy.gif": 0.04,
            "santa.gif": 0.02,
            "spikey.gif": 0.02,
            "tophat.gif": 0.43
        },
        "pants": {
            "bum.gif": 0.04,
            "circus1.gif": 0.01,
            "circus2.gif": 0.03,
            "cowboy.gif": 0.1,
            "gold.gif": 0.04,
            "jester.gif": 0.1,
            "joker.gif": 0.01,
            "mime.gif": 0.08,
            "pierrot.gif": 0.04,
            "santa.gif": 0.02,
            "silver.gif": 0.53
        },
        "weapon": {
            "axe.gif": 0.05,
            "balloon.gif": 0.02,
            "bat.gif": 0.02,
            "candycane.gif": 0.05,
            "chicken.gif": 0.04,
            "coin.gif": 0.04,
            "crowbar.gif": 0.03,
            "glove.gif": 0.04,
            "gun.gif": 0.03,
            "hammer.gif": 0.05,
            "horn.gif": 0.03,
            "knife.gif": 0.06,
            "mace.gif": 0.04,
            "machete.gif": 0.01,
            "pie.gif": 0.04,
            "saw.gif": 0.04,
            "sword.gif": 0.05,
            "syringe.gif": 0.36
        }
    },
    "order": [
        "background",
        "pants",
        "body",
        "weapon",
        "mouth",
        "hair",
        "eyes"
    ],
    "width": 1000,
    "height": 1000
}
```

I am cd'd into the cli file

After some screwing around trying to figure out what's going on, I deduced that it was the metadata.ts file attempting to read my traits-configuration.json and not being able to read premadeCustoms. So apparently it's something wrong with my json metadata, but what in the world is premadeCustoms? What is that supposed to be reading?

 - Mac OS
 - Firefox

**Comment by amine7777** [comment]
@JamisonO  Please check this https://github.com/metaplex-foundation/metaplex/issues/1001 
I had the same issue, there is a solution That I am using but it's just a workaround.

**Comment by JamisonO** [comment]
Found the problem:

https://github.com/metaplex-foundation/metaplex/pull/1032#issue-1059491184

Apparently, they added some new stuff to the metadata json. Did a fresh install of metamask, generated some images, and it worked just fine.
