### ISSUE TITLE
npx ts-node

### ISSUE THREAD

**Issue by vts666** [metaplex-foundation/metaplex#1082]
hello.

after i use thus command npx ts-node candy-machine-cli.ts upload /Users/vts666/Desktop/SolSkeletons/met/metaplex/.assets -env devnet --keypair /Users/vts666/.config/solana/devnet.json

i have this error, can u help me?

Beginning the upload for 2 (png+json) pairs
started at: 1638303362509
wallet public key: H4zsapGACu5MdjAxxLRP1xW5gKPbaM34JBiLSFaCyHnP
(node:61896) UnhandledPromiseRejectionWarning: Error: Unknown https cluster: nv
    at Object.clusterApiUrl (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/node_modules/@solana/web3.js/src/util/cluster.ts:28:11)
    at Object.<anonymous> (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/helpers/accounts.ts:466:26)
    at step (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/helpers/accounts.ts:63:23)
    at Object.next (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/helpers/accounts.ts:44:53)
    at /Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/helpers/accounts.ts:38:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/helpers/accounts.ts:34:12)
    at Object.loadCandyProgram (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/helpers/accounts.ts:473:12)
    at Object.<anonymous> (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/commands/upload.ts:68:31)
    at step (/Users/vts666/Desktop/SolSkeletons/met/metaplex/js/packages/cli/src/commands/upload.ts:44:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:61896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:61896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kevin-dev71** [comment]
typo error... 

`npx ts-node candy-machine-cli.ts upload /Users/vts666/Desktop/SolSkeletons/met/metaplex/.assets --env devnet --keypair /Users/vts666/.config/solana/devnet.json`
