### ISSUE TITLE
Getting an Error

### ISSUE THREAD

**Issue by bplfamily** [metaplex-foundation/metaplex#1101]
I'm performing create gumdrop ( Tokens) with the following command.
$ ts-node gumdrop-cli.ts create -e devnet --keypair <keypair location> --distribution-list <path to your distribution list JSON> --claim-integration transfer --transfer-mint <mint>  --distribution-method discord --discord-token <TOKEN> --otp-auth none --discord-guild <guild id>

/home/buddha/metaplex/js/packages/cli/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
                    ^
Error: Number can only safely store up to 53 bits
    at assert (/home/buddha/metaplex/js/packages/cli/node_modules/bn.js/lib/bn.js:6:21)
    at BN.toNumber (/home/buddha/metaplex/js/packages/cli/node_modules/bn.js/lib/bn.js:547:7)
    at /home/buddha/metaplex/js/packages/cli/src/helpers/gumdrop/claimant.ts:205:48
    at step (/home/buddha/metaplex/js/packages/cli/src/helpers/gumdrop/claimant.ts:52:23)
    at Object.next (/home/buddha/metaplex/js/packages/cli/src/helpers/gumdrop/claimant.ts:33:53)
    at fulfilled (/home/buddha/metaplex/js/packages/cli/src/helpers/gumdrop/claimant.ts:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

As far as I can understand this error comes in the cases of string vs integer index misuse. Any suggestions to where to look for the problem?

**Comment by bplfamily** [comment]
After logging the values of val, I found the val is False.
