### ISSUE TITLE
Create candy machine error  msg: 'Number of config lines must be at least number of items available' code: 313

### ISSUE THREAD

**Issue by juandelia03** [metaplex-foundation/metaplex#1165]
I am trying to create a candymachine with 1k nfts I already uploaded using this repo in the devnet.
I get the following error:

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18218 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139        
    at Connection.sendEncodedTransaction (/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)       
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)     
    at async sendAndConfirmRawTransaction (/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)     
    at async Object.rpc [as initializeCandyMachine] (/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18218 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/packages/cli/node_modules/@project-serum/anchor/src/error.ts:35
      return new ProgramError(errorCode, errorMsg, errorCode + ": " + errorMsg);   
             ^
ProgramError: 313: Number of config lines must be at least number of items available
    at Function.parse (/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/packages/cli/node_modules/@project-serum/anchor/src/error.ts:35:14)
    at Object.rpc [as initializeCandyMachine] (/mnt/c/Users/User/Desktop/Proyectos/SOL_ox/metaplex-master/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {        
  code: 313,
  msg: 'Number of config lines must be at least number of items available'
}

I already tried changing every "onChain":true  to false in the temp file and running the upload script again but didn't work

**Comment by Rakeshpradhan1999** [comment]
Same problem

**Comment by rafaelescrich** [comment]
Same problem here

**Comment by ncarrara** [comment]
same here
