### ISSUE TITLE
upload was not successful, please re-run. Error: timeout of 100000ms exceeded

### ISSUE THREAD

**Issue by nishant9868232** [metaplex-foundation/metaplex#1211]
When trying to upload the images I am getting this error.... I am using custom rpc and it is running fine I tried using solana balance. Tried several time but it didn't worked.
upload was not successful, please re-run. Error: timeout of 100000ms exceeded
    at createError (D:\work\metaplex\js\node_modules\@bundlr-network\client\node_modules\arweave\node_modules\axios\lib\core\createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (D:\work\metaplex\js\node_modules\@bundlr-network\client\node_modules\arweave\node_modules\axios\lib\adapters\http.js:328:16)
    at RedirectableRequest.emit (node:events:390:28)
    at RedirectableRequest.emit (node:domain:475:12)
    at Timeout.<anonymous> (D:\work\metaplex\js\node_modules\follow-redirects\index.js:164:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 100000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: 536870912,
    maxBodyLength: Infinity,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/octet-stream',
      'User-Agent': 'axios/0.22.0',
      'Content-Length': 902
    },
    baseURL: 'https://node1.bundlr.network:443',
    method: 'post',
    url: 'https://node1.bundlr.network:443/tx/solana',
    data: <Buffer 02 00 7b d7 1b 26 04 28 9a 44 dd 43 3a c5 b4 a0 b0 d1 1d 58 b6 d2 df c8 70 6f b9 c9 fc ee bd 80 30 d3 0b ab 47 82 66 b0 73 29 bc 62 2c 46 df 51 6e 33 ... 852 more bytes>
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Array],
      error: [Array],
      socket: [Function: destroyOnTimeout]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/tx/solana',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'node1.bundlr.network',
      port: '443',
      nativeProtocols: [Object],
      pathname: '/tx/solana'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 902,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /tx/solana HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/octet-stream\r\n' +
        'User-Agent: axios/0.22.0\r\n' +
        'Content-Length: 902\r\n' +
        'Host: node1.bundlr.network\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/tx/solana',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'node1.bundlr.network',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'https://node1.bundlr.network:443/tx/solana',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
ended at: 2021-12-14T05:08:53.357Z. time taken: 00:04:39

**Comment by TFTA** [comment]
Same here, i dont know why.
Last time was because i used the candymachine v1 instead of the v2, but here i'm very stuck..
Already uploaded 1700 ,and now i have this issues :/

**Comment by londonbridges13** [comment]
> Same here, i dont know why. Last time was because i used the candymachine v1 instead of the v2, but here i'm very stuck.. Already uploaded 1700 ,and now i have this issues :/

Were you able to figure it out?

**Comment by josezy** [comment]
> This Issue has received no activity for 30 days. We will close it in 2 days, please reopen if you are still experiencing this issue.

I'm experiencing this issue, thought I might be a network issue but it's been 3 days now stuck uploading at 2355 assets (out of 5000)

**Comment by josezy** [comment]
So I inspected the [code](https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/helpers/upload/arweave-bundle.ts#L499) and increased the timeout and now it is working
