### ISSUE TITLE
Subsequent 'upload' attempts failing after initial

### ISSUE THREAD

**Issue by DigitalTechnicality** [metaplex-foundation/metaplex#1236]
So for many users within the past week, they will upload their files. The cache will then be updated with a mix of onchain:true and onchain:false. However, when they try to repeat the 'upload' command in the CLI to repair the onchain:false values, the CLI returns a series empty [] and then says 'done'. I'm sorry this is not a more complete bug report, and I hope someone more experienced comments here as well. I will attempt to look in the upload.ts file to see what could be adjusted as well. 

Thanks.

**Comment by lucastonon** [comment]
Same problem here

**Comment by jasonruncie** [comment]
If by failing you mean just skips writing indices, I have just committed a fix in my PR https://github.com/metaplex-foundation/metaplex/pull/985

**Comment by lucastonon** [comment]
@jasonruncie I am not sure if it's the same problem, but before I was getting:
`signatureUnsubscribe error: Invalid subscription id.`
Then I had to checkout from
`git checkout 938116471dcdb69a233a7ec3e167c83540c2eae4`
Then it's working very slowly, but it's kind of a mess. It's not following a clear order, and maybe it's
skipping a few indices

`
Processing file: 1238, 222.png
Processing file: 1259, 241.png
Processing file: 1280, 260.png
Processing file: 1301, 28.png
Processing file: 1322, 299.png
Processing file: 1343, 317.png
Processing file: 1364, 336.png
Processing file: 1385, 355.png
`

The signature problem still happens, but every once in a while.

So, I am seeing 3 errors, every once in a while, during the upload of a collection.

1.
`
signatureUnsubscribe error: Invalid subscription id.
`

2.

`
Error uploading file 1741 Error: No transaction ID for upload: 1741
    at /Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:119:11
    at step (/Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:52:23)
    at Object.next (/Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:33:53)
    at fulfilled (/Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
`

3.

`
Rejecting for timeout...
Timeout Error caught { timeout: true }
Error uploading file 2098 Error: Timed out awaiting confirmation on transaction
    at /Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/transactions.ts:121:13
    at step (/Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/transactions.ts:33:23)
    at Object.throw (/Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/transactions.ts:14:53)
    at rejected (/Users/lucastonon/Projects/NFT/metaplex/js/packages/cli/src/helpers/transactions.ts:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processTimers (internal/timers.js:497:9)
(node:26286) UnhandledPromiseRejectionWarning: FetchError: request to https://api.devnet.solana.com/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/lucastonon/Projects/NFT/metaplex/js/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26286) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26286) UnhandledPromiseRejectionWarning: FetchError: request to https://api.devnet.solana.com/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/lucastonon/Projects/NFT/metaplex/js/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:26286) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

`

**Comment by brantchoate** [comment]
in addition to using @jasonruncie PR we also had to switch to quicknode for our custom RPC node. Runnode was causing problems as well.

**Comment by ATR-oCiTy** [comment]
Deleting the data for just the entries with onChain=False works
