### ISSUE TITLE
Property 'Wallet' does not exist on type 'typeof import ...

### ISSUE THREAD

**Issue by pra-dan** [metaplex-foundation/metaplex#1241]
**Describe the bug**
I am running Solana and metaplex on Apple M1 and installed them following the [official README](https://github.com/heisenberglit/candy-machine-mint).

**To Reproduce**
1. Install Solana CLI/toolkit using steps [here](https://docs.solana.com/cli/install-solana-cli-tools)
2. Install metaplex using steps [here](https://hackmd.io/@levicook/HJcDneEWF)
3. Run `ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts help upload`

**Expected behavior**
The command should return 
```console
Usage: candy-machine-cli upload [options] <directory>

Arguments:
  directory                  Directory containing images named from 0-n

Options:
  -e, --env <string>         Solana cluster env name (default: "devnet")
  -k, --keypair <path>       Solana wallet location (default: "--keypair not provided")
  -l, --log-level <string>   log level
  -c, --cache-name <string>  Cache file name (default: "temp")
  -n, --number <number>      Number of images to upload
  -h, --help                 display help for command
```

**Logs**
```console
/opt/homebrew/lib/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
js/packages/cli/src/helpers/accounts.ts:469:36 - error TS2339: Property 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.

469   const walletWrapper = new anchor.Wallet(walletKeyPair);
                                       ~~~~~~
js/packages/cli/src/helpers/accounts.ts:491:36 - error TS2339: Property 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.

491   const walletWrapper = new anchor.Wallet(walletKeyPair);
                                       ~~~~~~
js/packages/cli/src/helpers/accounts.ts:512:36 - error TS2339: Property 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.

512   const walletWrapper = new anchor.Wallet(walletKeyPair);
                                       ~~~~~~
js/packages/cli/src/helpers/accounts.ts:533:36 - error TS2339: Property 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.

533   const walletWrapper = new anchor.Wallet(walletKeyPair);
                                       ~~~~~~

    at createTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  diagnosticText: `\x1B[96mjs/packages/cli/src/helpers/accounts.ts\x1B[0m:\x1B[93m469\x1B[0m:\x1B[93m36\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.\n` +
    '\n' +
    '\x1B[7m469\x1B[0m   const walletWrapper = new anchor.Wallet(walletKeyPair);\n' +
    '\x1B[7m   \x1B[0m \x1B[91m                                   ~~~~~~\x1B[0m\n' +
    `\x1B[96mjs/packages/cli/src/helpers/accounts.ts\x1B[0m:\x1B[93m491\x1B[0m:\x1B[93m36\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.\n` +
    '\n' +
    '\x1B[7m491\x1B[0m   const walletWrapper = new anchor.Wallet(walletKeyPair);\n' +
    '\x1B[7m   \x1B[0m \x1B[91m                                   ~~~~~~\x1B[0m\n' +
    `\x1B[96mjs/packages/cli/src/helpers/accounts.ts\x1B[0m:\x1B[93m512\x1B[0m:\x1B[93m36\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.\n` +
    '\n' +
    '\x1B[7m512\x1B[0m   const walletWrapper = new anchor.Wallet(walletKeyPair);\n' +
    '\x1B[7m   \x1B[0m \x1B[91m                                   ~~~~~~\x1B[0m\n' +
    `\x1B[96mjs/packages/cli/src/helpers/accounts.ts\x1B[0m:\x1B[93m533\x1B[0m:\x1B[93m36\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'Wallet' does not exist on type 'typeof import("/Users/prashantdandriyal/Developer/metaplex-foundation/metaplex/node_modules/@project-serum/anchor/dist/cjs/index")'.\n` +
    '\n' +
    '\x1B[7m533\x1B[0m   const walletWrapper = new anchor.Wallet(walletKeyPair);\n' +
    '\x1B[7m   \x1B[0m \x1B[91m                                   ~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2339, 2339, 2339, 2339 ]
}
```

**Desktop (please complete the following information):**
 - OS: MacOS 11.3 Big Sur

**Comment by dpruitt90** [comment]
Same steps and issue

**Comment by pra-dan** [comment]
@dpruitt90 Simply follow the official instructions given in the repo README. It works
Run
```console
$ git clone https://github.com/metaplex-foundation/metaplex.git
$ cd metaplex/js
$ yarn install && yarn bootstrap && yarn build
$ yarn start
```

All dependency issues will vanish :)
