### ISSUE TITLE
Upload problems

### ISSUE THREAD

**Issue by axepro99** [metaplex-foundation/metaplex#1244]
i try to upload some nft to arweave-sol and i get this error, i actually have more than 5 solanas in my account so i dont understand the problem.

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1 
    Program 11111111111111111111111111111111 invoke [1]
    Transfer: insufficient lamports 634030798, need 3716229360
    Program 11111111111111111111111111111111 failed: custom program error: 0x1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3553:13)       
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3513:20)     
    at async sendAndConfirmRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeConfig] (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\helpers\accounts.ts:209:11)
    at async initConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:505:17)
    at async upload (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:818:9)
    at async Command.<anonymous> (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\candy-machine-cli.ts:205:7) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 634030798, need 3716229360',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
}
Error deploying config to Solana network. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3553:13)       
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3513:20)     
    at async sendAndConfirmRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeConfig] (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\helpers\accounts.ts:209:11)
    at async initConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:505:17)
    at async upload (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:818:9)
    at async Command.<anonymous> (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\candy-machine-cli.ts:205:7) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 634030798, need 3716229360',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
}
upload was not successful, please re-run. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3553:13)       
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3513:20)     
    at async sendAndConfirmRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeConfig] (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\helpers\accounts.ts:209:11)
    at async initConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:505:17)
    at async upload (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:818:9)
    at async Command.<anonymous> (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\candy-machine-cli.ts:205:7) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 634030798, need 3716229360',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
}
ended at: 2021-12-16T21:13:06.706Z. time taken: 00:00:07

**Comment by FeedandSeed** [comment]
Exact same issues for me.

**Comment by vts666** [comment]
> i try to upload some nft to arweave-sol and i get this error, i actually have more than 5 solanas in my account so i dont understand the problem.
> 
> 
> 
> 
> 
> Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1 
> 
>     Program 11111111111111111111111111111111 invoke [1]
> 
>     Transfer: insufficient lamports 634030798, need 3716229360
> 
>     Program 11111111111111111111111111111111 failed: custom program error: 0x1
> 
> Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
> 
>     at Connection.sendEncodedTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3553:13)       
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>     at async Connection.sendRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3513:20)     
> 
>     at async sendAndConfirmRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
> 
>     at async Provider.send (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
> 
>     at async Object.rpc [as initializeConfig] (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
> 
>     at async createConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\helpers\accounts.ts:209:11)
> 
>     at async initConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:505:17)
> 
>     at async upload (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:818:9)
> 
>     at async Command.<anonymous> (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\candy-machine-cli.ts:205:7) {
> 
>   logs: [
> 
>     'Program 11111111111111111111111111111111 invoke [1]',
> 
>     'Transfer: insufficient lamports 634030798, need 3716229360',
> 
>     'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
> 
>   ]
> 
> }
> 
> Error deploying config to Solana network. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
> 
>     at Connection.sendEncodedTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3553:13)       
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>     at async Connection.sendRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3513:20)     
> 
>     at async sendAndConfirmRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
> 
>     at async Provider.send (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
> 
>     at async Object.rpc [as initializeConfig] (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
> 
>     at async createConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\helpers\accounts.ts:209:11)
> 
>     at async initConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:505:17)
> 
>     at async upload (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:818:9)
> 
>     at async Command.<anonymous> (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\candy-machine-cli.ts:205:7) {
> 
>   logs: [
> 
>     'Program 11111111111111111111111111111111 invoke [1]',
> 
>     'Transfer: insufficient lamports 634030798, need 3716229360',
> 
>     'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
> 
>   ]
> 
> }
> 
> upload was not successful, please re-run. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
> 
>     at Connection.sendEncodedTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3553:13)       
> 
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
>     at async Connection.sendRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3513:20)     
> 
>     at async sendAndConfirmRawTransaction (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
> 
>     at async Provider.send (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
> 
>     at async Object.rpc [as initializeConfig] (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
> 
>     at async createConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\helpers\accounts.ts:209:11)
> 
>     at async initConfig (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:505:17)
> 
>     at async upload (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\commands\upload.ts:818:9)
> 
>     at async Command.<anonymous> (C:\Users\XD\Desktop\Solana-Mainnet\metaplex\js\packages\cli\src\candy-machine-cli.ts:205:7) {
> 
>   logs: [
> 
>     'Program 11111111111111111111111111111111 invoke [1]',
> 
>     'Transfer: insufficient lamports 634030798, need 3716229360',
> 
>     'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
> 
>   ]
> 
> }
> 
> ended at: 2021-12-16T21:13:06.706Z. time taken: 00:00:07

out of sol, u need more, how many assets do you trying to upload ?

**Comment by brantchoate** [comment]
try using a custom RPC node. Quicknode did it for us.

**Comment by stegaBOB** [comment]
It looks like you dont have enough sol in the account you are uploading from. You need ~4 but its detecting around 0.6

**Comment by stegaBOB** [comment]
Closing this issue. If you are still having issues, feel free to open a new issue that includes all of the information in the Issue template. Thanks!

**Comment by lukaskelley** [comment]
upload was not successful, please re-run. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: Program failed to complete
    at Connection.sendEncodedTransaction (F:\Repository\ship-solana-nft-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3689:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (F:\Repository\ship-solana-nft-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3649:20)
    at async sendAndConfirmRawTransaction (F:\Repository\ship-solana-nft-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (F:\Repository\ship-solana-nft-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (F:\Repository\ship-solana-nft-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (F:\Repository\ship-solana-nft-collection\metaplex\js\packages\cli\src\helpers\accounts.ts:149:11)
    at async uploadV2 (F:\Repository\ship-solana-nft-collection\metaplex\js\packages\cli\src\commands\upload.ts:134:19)
    at async Command.<anonymous> (F:\Repository\ship-solana-nft-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: InitializeCandyMachine',
    "Program log: panicked at 'attempt to subtract with overflow', src/lib.rs:812:39",
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 11466 of 1400000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete'
  ]
}

**Comment by lukaskelley** [comment]
I am very upset because of this problem ..plz help me~

**Comment by drunckj** [comment]
> I am very upset because of this problem ..plz help me~

     

Faced the same today, it can be fixed easily by checking field limits from js/packages/cli/src/helpers/constants.ts. Just make sure you don't exceed the limits mentioned inside the file. For me my symbols were taking more than 10 characters, that's why it was failing.

**Comment by lnfernandobr** [comment]
> 

This is works for me, thanks.

**Comment by devlancer412** [comment]
I met same error

This is my meta data
{
  "name": "Dokesi #0",
  "symbol": "DKS",
  "description": "Dokesi is a PFP inspired by short film animation, with rich and unique rare features, dozens of rare avatars, costumes, and color schemes.",
  "seller_fee_basis_points": 1000,
  "image": "https://dokesi.mypinata.cloud/ipfs/QmU6pw5HZefcS7wMADpiUwbE1BVeVPw3wU3w9irV66dAva/0.json",
  "external_url": "https://dokesi.io/",
  "edition": 0,
  "attributes": [
    { "trait_type": "background", "value": "pale yellow" },
    { "trait_type": "Special", "value": "starry sky" },
    { "trait_type": "Skin", "value": "brown skin" },
    { "trait_type": "Clothing", "value": "Gold Yukata" },
    { "trait_type": "Eye", "value": "gold round glasses" },
    { "trait_type": "Mouth", "value": "open mouth" },
    { "trait_type": "Props", "value": "Gold Circle Necklace" },
    { "trait_type": "Hair", "value": "Gold Headphones + Blonde Hair" },
    { "trait_type": "Hand", "value": "golden fishing rod" }
  ],
  "properties": {
    "files": [{ "uri": "0.png", "type": "image/png" }],
    "category": "image",
    "creators": [
      {
        "address": "BA4cUKFfA243hxdE9BGHWQhsuYxFwjA5KZZC6yR9cEVu",
        "share": 50
      },
      { "address": "n8MrDdXmVTVTcvEU1zoKnZnaH2o5GJCmEEHUgU5pN2U", "share": 50 }
    ]
  },
  "collection": { "name": "Dokesi", "family": "Dokesi" }
}

Please help me..
