### ISSUE TITLE
Error deploying config to Solana network. TypeError: Cannot read properties of undefined (reading '_bn')

### ISSUE THREAD

**Issue by zkhalapyan** [metaplex-foundation/metaplex#1258]
Using `upload` command on candy machine V1 leads to an error as described below:

```
➜  burble git:(main) ✗ ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts upload assets --env devnet --keypair  ~/.config/solana/id.json
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 3 (image+json) pairs
started at: 1639788540157
wallet public key: 6zsuBDfuvtxK5FD9tf8u8LfrYBVnxDWRhj43snmC6Qx6
Processing asset: [object Object]
Processing asset: [object Object]
Processing asset: [object Object]
Initializing program config
Error deploying config to Solana network. TypeError: Cannot read properties of undefined (reading '_bn')
    at isPublicKeyData (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/publickey.ts:29:35)
    at new PublicKey (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/publickey.ts:45:9)
    at /Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:519:18
    at Array.map (<anonymous>)
    at initConfig (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:518:26)
    at upload (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:824:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:205:7)
upload was not successful, please re-run. TypeError: Cannot read properties of undefined (reading '_bn')
    at isPublicKeyData (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/publickey.ts:29:35)
    at new PublicKey (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/publickey.ts:45:9)
    at /Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:519:18
    at Array.map (<anonymous>)
    at initConfig (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:518:26)
    at upload (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:824:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:205:7)
ended at: 2021-12-18T00:49:18.971Z. time taken: 00:00:18
```

The assets folder is correctly initialized.

**Comment by zkhalapyan** [comment]
```
"creators": [
      {
        "address": "INSERT_CREATOR_WALLET_ADDRESS_HERE",
        "share": 100
      }
    ]
```

Forgot to set the correct creator address 🤦‍♂️
