### ISSUE TITLE
Canvas was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by zkhalapyan** [metaplex-foundation/metaplex#1288]
**Describe the bug**
```
ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/id.json
Error: The module '/Users/zkhalapyan/metaplex-foundation/metaplex/js/node_modules/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/zkhalapyan/metaplex-foundation/metaplex/js/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

**To Reproduce**
1. `nvm install 14.17.0` -> `nvm use 14.17.0`
2. Clone & pull latest metaplex repo
3. cd metaplex/js, then run `yarn install && yarn bootstrap && yarn build` 
4. From your assets folder, run `ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/id.json` 

**Expected behavior**
Should upload assets. 

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey 

**Additional context**
- I tried after uninstalling all other node versions except the correct one (14.17.0).
- I tried after calling `yarn add -w @types/offscreencanvas` 

These were just some workaround from previous threads.

**Comment by zkhalapyan** [comment]
The Tl;DR: for the fix was to call `nvm ci` to delete the `node_modules` and recompile again. Seems like canvas was not getting rebuilt after I changed the node version using `nvm`. Restart your terminal in case you're using multiple tabs — nvm only changes the node version for the current terminal session and could make things a bit confusing. 


FWIW, metaplex compiled with v17.2.0 🤷‍♂️

```
node --version
v17.2.0
```
