### ISSUE TITLE
I cant create candy machine

### ISSUE THREAD

**Issue by FairyClub** [metaplex-foundation/metaplex#1313]
I keep getting this error

C:\Users\veron\Desktop\solana-mint\metaplex\js\packages\cli\src\candy-machine-cli.ts:53
  .argument(
                      ^
TypeError: Cannot read properties of undefined (reading 'program')
    at C:\Users\veron\Desktop\solana-mint\metaplex\js\packages\cli\src\candy-machine-cli.ts:705:47
    at step (C:\Users\veron\Desktop\solana-mint\metaplex\js\packages\cli\src\candy-machine-cli.ts:53:23)
    at Object.next (C:\Users\veron\Desktop\solana-mint\metaplex\js\packages\cli\src\candy-machine-cli.ts:34:53)
    at fulfilled (C:\Users\veron\Desktop\solana-mint\metaplex\js\packages\cli\src\candy-machine-cli.ts:25:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

when I run 

ts-node js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env mainnet-beta --keypair ~/config/solana/devnet-test.json

**Comment by Khushhal23** [comment]
Try adding npx to starting of command or adding like 0.05 SOL to ur wallet

**Comment by moonvision2020** [comment]
try  ts-node C:\Users\veron\Desktop\solana-mint\metaplex\js\packages\cli\src\candy-machine-cli.ts
