### ISSUE TITLE
Error 0x66 when running upload command for CMv2

### ISSUE THREAD

**Issue by kzka90** [metaplex-foundation/metaplex#1361]
I'm trying to mint some assets using the CandyMachineV2 JS CLI, but I keep getting a 0x66 error.

I'm trying to run the command as follows:

`ts-node build/candy-machine-v2-cli.js upload ./assets -k id.json -cp config.json -e devnet`

And the logs throw the following:

```
wallet public key: <MY PUBLIC ADDRESS>
Beginning the upload for 1 (img+json) pairs
started at: 1640908491098
Size 1 { mediaExt: '.png', index: '0' }
Processing asset: 0
initializing candy machine
Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Custom program error: 0x66
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 4502 of 200000 compute units
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0x66
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66
    at Connection.sendEncodedTransaction (/var/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/var/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/var/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/var/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/var/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async createCandyMachineV2 (/var/metaplex/js/packages/cli/build/helpers/accounts.js:93:15)
    at async /var/metaplex/js/packages/cli/build/commands/upload.js:136:37
    at async Promise.all (index 0)
    at async uploadV2 (/var/metaplex/js/packages/cli/build/commands/upload.js:110:9)
```

My `./assets` folder consist of:

```
./assets
|--- 0.png
|--- 0.json
```

Where `0.json` is set as:

```
{
	"name": "Example Monkey",
	"image": "0.png",
	"description": "This is my first asset",
	"seller_fee_basis_points": 100,
	"symbol": "MTT",
	"properties": {
		"files": [{
			"uri": "0.png",
			"type": "image/png"
		}],
		"creators": [{
			"address": "<MY PUBLIC ADDRESS>",
			"share": 100
		}]
	}
}
```

And the `config.json` file for the CandyMachine is set as:

```
{
  "price": 0.01,
  "number": 1,
  "solTreasuryAccount": "<MY PUBLIC ADDRESS>",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "2021-12-30T22:55:04Z",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "storage": "ipfs",
  "ipfsInfuraProjectId": "<INFURA_PROJECT>",
  "ipfsInfuraSecret": "<INFURA_SECRET>",
  "awsS3Bucket": null,
  "noRetainAuthority": false,
  "noMutable": false
}
```

I already tried it in 2 different machines, one Ubuntu, one Windows.

What am I missing? Am I missing a dependency? Am I missing a property? The error seems to be in the serialization of data, maybe? But where?

**Comment by kzka90** [comment]
I was missing the `"gatekeep":null`  on the `config.json`. I think the error logs should be a little more informative 🙃.
