### ISSUE TITLE
CMv2 Discount Price of 0 causes error

### ISSUE THREAD

**Issue by kyleqian** [metaplex-foundation/metaplex#1381]
**Describe the bug**
I'm unable to upload or update with a CMv2 config where discountPrice is 0.

Error:
```
Error deploying config to Solana network. TypeError: src.toArrayLike is not a function
    at BNLayout.encode (/Users/kyle/lib/metaplex/js/packages/cli/node_modules/@project-serum/borsh/src/index.ts:59:11)
    at OptionLayout.encode (/Users/kyle/lib/metaplex/js/packages/cli/node_modules/@project-serum/borsh/src/index.ts:136:24)
    at Structure.encode (/Users/kyle/lib/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1263:26)
    at OptionLayout.encode (/Users/kyle/lib/metaplex/js/packages/cli/node_modules/@project-serum/borsh/src/index.ts:136:24)
    at Structure.encode (/Users/kyle/lib/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1263:26)
    at Structure.encode (/Users/kyle/lib/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1263:26)
    at InstructionCoder._encode (/Users/kyle/lib/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:85:24)
    at InstructionCoder.encode (/Users/kyle/lib/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:68:17)
    at /Users/kyle/lib/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/index.ts:51:56
    at ix (/Users/kyle/lib/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:43:15)
```

**To Reproduce**
1. Create CMv2 config where discountPrice for whitelist is 0 or 0.0
2. Try to upload with CLI
3. Error as shown above

**Expected behavior**
It creates a candy machine where people on the presale get to mint for free

**Comment by ybsat** [comment]
The problem is that when getCandyMachinev2() is called, it takes discountPrice == 0 as a boolean false. And the value then remains 0 instead of getting converted to a BigNumber (BN) which is the required input when calling through Anchor.

To solve this, in /js/packages/cli/src/helpers/various.ts, I updated around line 146 to the following:

`  if (whitelistMintSettings) {
    whitelistMintSettings.mint = new web3.PublicKey(whitelistMintSettings.mint);
    if ((whitelistMintSettings?.discountPrice) || (whitelistMintSettings?.discountPrice === 0)) {
      whitelistMintSettings.discountPrice = new BN(
        whitelistMintSettings.discountPrice,
      );
    }
  }`

This essentialy allows cases of discountPrice === 0 to also be converted to BN before they are passed downstream. A cleaner implemenration would be 1 condition like whitelistMintSettings?.discountPrice >= 0 without having an || statement.

**Comment by ck256-2000** [comment]
curious - no one else reported this?  this would be how you give away free NFTs to whitelist holders . .or is that function supposed to be in gumdrop?  thx for your work on this !

**Comment by OlajideOgun** [comment]
I have te same problem

**Comment by yamijuan** [comment]
use `null` instead of `0`

**Comment by aungthumoe5** [comment]
https://github.com/metaplex-foundation/metaplex/pull/1573 fixes the issue. Ticket can be closed.
