### ISSUE TITLE
CMv2 ate my ~6 SOL on mainnet-beta, and didn't create .cache file

### ISSUE THREAD

**Issue by FluffyPorcupine** [metaplex-foundation/metaplex#1394]
**Describe the bug**
I have a 3.5k collection that deployed successfully on devnet. I switched everything over to mainnet-beta, and tried to run the following command, and got an error:

PS D:\repos\Solana\metaplex-2> ts-node ./js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k .config/solana/mainnet.json -cp ./config.json -c mainnet ./assets

```
Beginning the upload for 3500 (img+json) pairs
started at: 1641320040784
Size 3500 { mediaExt: '.png', index: '0' }
initializing candy machine
Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 2wSkABdWGY9xhASUTJRdcmu257caCJyd5V2ZhhSgNEwS7K1KNPUywuzonNB1saawrhi8kmQ5xR8QVMKDatZELLrx using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)      
    at async Object.rpc [as initializeCandyMachine] (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (D:\repos\Solana\metaplex-2\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (D:\repos\Solana\metaplex-2\js\packages\cli\src\commands\upload.ts:133:21)
    at async Command.<anonymous> (D:\repos\Solana\metaplex-2\js\packages\cli\src\candy-machine-v2-cli.ts:183:7)
Error deploying config to Solana network. Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 2wSkABdWGY9xhASUTJRdcmu257caCJyd5V2ZhhSgNEwS7K1KNPUywuzonNB1saawrhi8kmQ5xR8QVMKDatZELLrx using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)      
    at async Object.rpc [as initializeCandyMachine] (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (D:\repos\Solana\metaplex-2\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (D:\repos\Solana\metaplex-2\js\packages\cli\src\commands\upload.ts:133:21)
    at async Command.<anonymous> (D:\repos\Solana\metaplex-2\js\packages\cli\src\candy-machine-v2-cli.ts:183:7)
upload was not successful, please re-run. Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 2wSkABdWGY9xhASUTJRdcmu257caCJyd5V2ZhhSgNEwS7K1KNPUywuzonNB1saawrhi8kmQ5xR8QVMKDatZELLrx using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)      
    at async Object.rpc [as initializeCandyMachine] (D:\repos\Solana\metaplex-2\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (D:\repos\Solana\metaplex-2\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (D:\repos\Solana\metaplex-2\js\packages\cli\src\commands\upload.ts:133:21)
    at async Command.<anonymous> (D:\repos\Solana\metaplex-2\js\packages\cli\src\candy-machine-v2-cli.ts:183:7)
ended at: 2022-01-04T18:15:01.338Z. time taken: 00:01:00
```

I looked up the transaction on solscan, and it completed successfully: https://solanascan.io/txn/2wSkABdWGY9xhASUTJRdcmu257caCJyd5V2ZhhSgNEwS7K1KNPUywuzonNB1saawrhi8kmQ5xR8QVMKDatZELLrx

I looked at my .cache directory, and no cache file was created! It took my ~6 SOL, and now I have no idea of the address of the candy machine that was created. Is there any way that I can determine the candy machine address from the solscan transaction, and manually create a .cache file? 

Here is my .cache folder, where it shows no such file was created:
![image](https://user-images.githubusercontent.com/91390370/148110530-25555977-81f9-4489-809c-d346b54eb387.png)

I tried running the upload command again, just in case it would work magically, but it tried to create a new candy machine! Luckily I didn't have the funds to create a new one, so the second upload command errored out.

Edit:
I'm thinking that maybe this is the candy machine address that was created? Is there a way that you know of to get a candy machine uuid from an address?

![image](https://user-images.githubusercontent.com/91390370/148113984-36e25528-0fd6-4db8-bb75-b3bfcdb36001.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 11

**Comment by FluffyPorcupine** [comment]
If this happens to anyone in the future, I took the Hgw5Aqjunz8gQaNAp3VCEQ6WV6SVaEURdhcLAUupgo71 address listed in the picture above, and then manually created a file in the .cache folder called "mainnet-beta-mainnet.json". In the file I placed the following (the uuid came from the first 6 chars of the candy machine address):

```
{
  "program": {
    "uuid": "Hgw5Aq",
    "candyMachine": "Hgw5Aqjunz8gQaNAp3VCEQ6WV6SVaEURdhcLAUupgo71"
  },
  "items": {},
  "env":"mainnet-beta",
  "cacheName":"mainnet",
  "startDate":"61c65f00"
}
```
I was then able to re-run the upload command to get the assets to upload correctly.

It might be an enhancement to modify the `createCandyMachineV2` function in js/packages/cli/src/helpers/accounts.ts to create the .cache file BEFORE it does the await on the transaction?

**Comment by prashantcrypto** [comment]
hey i can make your candy machine on v2.
my fee is too low than other.
my discord #shyaid5168

**Comment by Medienor** [comment]
> hey i can make your candy machine on v2. my fee is too low than other. my discord #shyaid5168

how much?

**Comment by srajeevan** [comment]
> If this happens to anyone in the future, I took the Hgw5Aqjunz8gQaNAp3VCEQ6WV6SVaEURdhcLAUupgo71 address listed in the picture above, and then manually created a file in the .cache folder called "mainnet-beta-mainnet.json". In the file I placed the following (the uuid came from the first 6 chars of the candy machine address):
> 
> ```
> {
>   "program": {
>     "uuid": "Hgw5Aq",
>     "candyMachine": "Hgw5Aqjunz8gQaNAp3VCEQ6WV6SVaEURdhcLAUupgo71"
>   },
>   "items": {},
>   "env":"mainnet-beta",
>   "cacheName":"mainnet",
>   "startDate":"61c65f00"
> }
> ```
> 
> I was then able to re-run the upload command to get the assets to upload correctly.
> 
> It might be an enhancement to modify the `createCandyMachineV2` function in js/packages/cli/src/helpers/accounts.ts to create the .cache file BEFORE it does the await on the transaction?



> If this happens to anyone in the future, I took the Hgw5Aqjunz8gQaNAp3VCEQ6WV6SVaEURdhcLAUupgo71 address listed in the picture above, and then manually created a file in the .cache folder called "mainnet-beta-mainnet.json". In the file I placed the following (the uuid came from the first 6 chars of the candy machine address):
> 
> ```
> {
>   "program": {
>     "uuid": "Hgw5Aq",
>     "candyMachine": "Hgw5Aqjunz8gQaNAp3VCEQ6WV6SVaEURdhcLAUupgo71"
>   },
>   "items": {},
>   "env":"mainnet-beta",
>   "cacheName":"mainnet",
>   "startDate":"61c65f00"
> }
> ```
> 
> I was then able to re-run the upload command to get the assets to upload correctly.
> 
> It might be an enhancement to modify the `createCandyMachineV2` function in js/packages/cli/src/helpers/accounts.ts to create the .cache file BEFORE it does the await on the transaction?

@FluffyPorcupine , same thing happened to me as well.
I tried to upload 25 assets initially and got the same error that you got.
I am gonna try and create the file in .cache folder like you did.
You have kept the items as empty in the file.
That is fine ?

**Comment by prashantcrypto** [comment]
> > hey i can make your candy machine on v2. my fee is too low than other. my discord #shyaid5168
> 
> how much?
1.5-2 sol

**Comment by prashantcrypto** [comment]
> > hey i can make your candy machine on v2. my fee is too low than other. my discord #shyaid5168
> 
> how much?

1.5-2 sol

**Comment by stegaBOB** [comment]
In this situation, it is likely easier just to withdraw from the candy machine and retry. The documentation for that can be found in our docs at https://docs.metaplex.com
