### ISSUE TITLE
Candy Machine 2 upload "Blockhash not found"

### ISSUE THREAD

**Issue by asdasdasdasdasdasdasdad** [metaplex-foundation/metaplex#1413]
I'm trying upload assets candy machine 2. I tested on devnet its work but not working on mainnet
```
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e mainnet-beta \
    -k ~/.config/solana/mainnet.json \
    -cp config.json \
    -c mainnet \
    /var/www/assets --rpc-url https://
```
I got error:
```
Writing indices 910-919
Transaction simulation failed: Blockhash not found 
    
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (/home/opc/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/opc/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/home/opc/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/opc/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/home/opc/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async /home/opc/metaplex/js/packages/cli/src/commands/upload.ts:367:19
    at async Promise.all (index 0)
    at async uploadV2 (/home/opc/metaplex/js/packages/cli/src/commands/upload.ts:347:7) {
  logs: []
}
...
Done. Successful = false.
```
I reruning same command:

```
Beginning the upload for 3333 (img+json) pairs
started at: 1641451620522
Size 0 undefined
upload was not successful, please re-run. TypeError: Cannot read properties of undefined (reading 'index')
    at uploadV2 (/home/opc/metaplex/js/packages/cli/src/commands/upload.ts:112:16)
    at Command.<anonymous> (/home/opc/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:183:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
```
config.json
{
    "price": 0.33,
    "number": 3333,
    "gatekeeper": null,
    "solTreasuryAccount": "xxxx",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "06 Jan 2021 00:00:00 GMT",
    "endSettings": null,
    "whitelistMintSettings": null,
    "hiddenSettings": null,
    "storage": "arweave-sol",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}
```

**Comment by timashov** [comment]
I have the same issue rn. Were you able to fix it somehow?

**Comment by asdasdasdasdasdasdasdad** [comment]
> 

https://github.com/metaplex-foundation/metaplex/commit/fa9cf55a636d0577395fc78015fff7700e118c94
Metaplex have a new update. It's work for me

**Comment by stegaBOB** [comment]
> > 
> 
> https://github.com/metaplex-foundation/metaplex/commit/fa9cf55a636d0577395fc78015fff7700e118c94
> Metaplex have a new update. It's work for me

Looks like this issue has been resolved
