### ISSUE TITLE
Upload was not successful, please re-run. TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by lawncegoh** [metaplex-foundation/metaplex#1442]
**To Reproduce**
1. Ran this command `ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ./wallet/.config/solana/seller.json  -cp ./config.json ./assets --rpc-url https://snowy-autumn-wave.solana-mainnet.quiknode.pro/383630905bc38029c07c0d133f6b370f1b4c1f4d/`
2. Got `Size 0 undefined
upload was not successful, please re-run. TypeError: Cannot read property 'index' of undefined
    at uploadV2 (/Users/lawnce/Desktop/mint/metaplex/js/packages/cli/src/commands/upload.ts:112:16)
    at Command.<anonymous> (/Users/lawnce/Desktop/mint/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:183:21)`
3. I am able to verify_upload: `Key size 0
uploaded (1488) out of (1488)
ready to deploy!`
4. I am able to update_candy_machine: `update_candy_machine finished 46h7qZpmtttwgJJ7NxMxNz1w12qddg9wcWBf3oGZ3sKLwDbAkG6VKoKEv64UqJ81FBpLKKBwrEJ2kmMV3DtKW6DP
`

**Expected behavior**
Expected the cli to allow for re-upload due to the failed assets that couldn't get on chain i.e onChain = false in the cache file

**Version**
Already on release version if it matters

**Comment by lawncegoh** [comment]
fixed, didn't checkout to proper branch before build
