### ISSUE TITLE
Metaplex UI: React has detected a change in the order of Hooks called by CurrentUserBadge

### ISSUE THREAD

**Issue by psavva** [metaplex-foundation/metaplex#1460]
**Describe the bug**
Start up Metaplex UI:
`yarn start`

Check the console from chrome:
```
Warning: React has detected a change in the order of Hooks called by CurrentUserBadge. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useContext                 useContext
3. useContext                 useContext
4. useState                   useState
5. undefined                  useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at CurrentUserBadge (http://localhost:3000/_next/static/chunks/src_App_tsx.js:129086:78)
    at div
    at div
    at AppBar (http://localhost:3000/_next/static/chunks/src_App_tsx.js:124443:78)
    at header
    at Basic (http://localhost:3000/_next/static/chunks/src_App_tsx.js:235829:25)
    at Adapter (http://localhost:3000/_next/static/chunks/src_App_tsx.js:235812:66)
    at section
    at BasicLayout (http://localhost:3000/_next/static/chunks/src_App_tsx.js:235844:63)
    at Adapter (http://localhost:3000/_next/static/chunks/src_App_tsx.js:235812:66)
    at _c (http://localhost:3000/_next/static/chunks/src_App_tsx.js:130706:27)
    at ConfettiProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:128597:3)
    at LoaderProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:130816:3)
    at MetaProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:499062:25)
    at StoreProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:500065:26)
    at CoingeckoProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:135179:3)
    at SPLTokenListProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:135470:3)
    at AccountsProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:496861:29)
    at WalletModalProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:500192:32)
    at WalletProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:194701:27)
    at WalletProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:500225:27)
    at ConnectionProvider (http://localhost:3000/_next/static/chunks/src_App_tsx.js:497456:31)
    at Providers (http://localhost:3000/_next/static/chunks/src_App_tsx.js:137685:3)
    at Router (http://localhost:3000/_next/static/chunks/src_App_tsx.js:426342:30)
    at HashRouter (http://localhost:3000/_next/static/chunks/src_App_tsx.js:426002:35)
    at Routes
    at App
    at LoadableImpl (http://localhost:3000/_next/static/chunks/pages/index.js?ts=1641626105038:388:36)
    at App
    at div
    at App (http://localhost:3000/_next/static/chunks/pages/_app.js?ts=1641626105038:34:3)
    at ErrorBoundary (http://localhost:3000/_next/static/chunks/main.js?ts=1641626105038:158:47)
    at ReactDevOverlay (http://localhost:3000/_next/static/chunks/main.js?ts=1641626105038:274:23)
    at Container (http://localhost:3000/_next/static/chunks/main.js?ts=1641626105038:8350:1)
    at AppContainer (http://localhost:3000/_next/static/chunks/main.js?ts=1641626105038:8729:3)
    at Root (http://localhost:3000/_next/static/chunks/main.js?ts=1641626105038:8859:3)

```

**To Reproduce**
```
$ git clone https://github.com/metaplex-foundation/metaplex.git
$ cd metaplex/js
$ yarn install && yarn bootstrap && yarn build
$ yarn start

```

Step 2: Connect Phantom Wallet
Step 3: Check the Chrome Developers Console.

**Expected behavior**
No exceptions should be thrown 

**Screenshots**
![image](https://user-images.githubusercontent.com/1454758/148635599-80d1d142-5f66-4b77-a169-67061779773d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by bxuserx** [comment]
I have the same issue. I think it's causing the /metaplex/js/ storefront to fail to load. 

<img width="1285" alt="Screen Shot 2022-01-08 at 8 42 58 PM" src="https://user-images.githubusercontent.com/86570251/148667349-d056feb3-cbd9-454b-9456-0c71d55b50be.png">

**Comment by curest0x1021** [comment]
I got the same issue. Please fix it and let me know.

**Comment by curest0x1021** [comment]
And when check the `Network` in the Chrome inspect, it calls the same apis repeatedly and the loading screen doesn't disappear.

**Comment by museumnfts** [comment]
same here

**Comment by wasif1024** [comment]
same here. if someone has found its solution please let me know

**Comment by deanrad** [comment]
Hooks should be called unconditionally https://reactjs.org/docs/hooks-faq.html

**Comment by spock-mark1** [comment]
How can I fix it?! can you help me? @psavva

**Comment by psavva** [comment]
I have not got it working.  Waiting for the devs...

**Comment by bxuserx** [comment]
> Perhaps the version of Node makes a difference here... I tried with Node V16

I'm using node 17.3.1, still have this issue. 

@deanrad Would you mind clarifying a bit more? Do we need to update to a certain version of typescript, update our package-lock.json? I read through your link, but I couldn't figure out the answer :/

**Comment by JohnRosey** [comment]
Hi,
try to add in url `metaplex#/?network=devnet`

**Comment by bxuserx** [comment]
@psavva  There are two problems. You get the hook error when you are using a version of node past node 15.  So change your node and yarn versions to the suggested in the README:

$ nvm install 14.17.6  
$ yarn set version 1.22.10

Next, use the following URL instead of just localhost:
http://localhost:3000/#/?network=devnet

Issue should be solved.

Thanks @JohnRosey  for the help!

**Comment by bruno1308** [comment]
I'm having the same issue on my Mac, even when trying with the suggested url and nvm/yarn versions above.

**Comment by psavva** [comment]
I still believe this should be fixed against the latest versions of Node.
@bxuserx  Shall I close this ticket? Or is there a update being planned to support new node versions?
