### ISSUE TITLE
candy-machine-v2 error

### ISSUE THREAD

**Issue by davincii1889** [metaplex-foundation/metaplex#1474]
Im getting this error: (required option '-cp, --config-path <string>' not specified)
 when i run ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload ./assets -env mainnet --keypair ~/.config/solana/mainnet-test.json

**Comment by stegaBOB** [comment]
Please check out our docs. You're missing the config path option in your command. https://docs.metaplex.com/candy-machine-v2/creating-candy-machine

**Comment by davincii1889** [comment]
thank you

**Comment by davincii1889** [comment]
Im still getting this error even thought i did what was recommended on the website:
Error: Cannot find module './candy-machine-v2-cli.ts'
Require stack:
 js/packages/cli/src/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:321:16)
    at getProjectSearchDir (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:291:40)
    at main (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:193:27)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/ts-node/dist/bin.js:351:5)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [

**Comment by malikh36** [comment]
I can surely help contact me email me easystudy36@gmail.com
