### ISSUE TITLE
Error: Invalid config, there must be at least one creator.

### ISSUE THREAD

**Issue by burningalc** [metaplex-foundation/metaplex#1504]
When running `ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload ...`, an error

```
Error deploying config to Solana network. Error: Invalid config, there must be at least one creator.
    at createCandyMachineV2 (/root/mock-nft/metaplex/js/packages/cli/src/helpers/accounts.ts:127:11)
    at uploadV2 (/root/mock-nft/metaplex/js/packages/cli/src/commands/upload.ts:130:45)
    at Command.<anonymous> (/root/mock-nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. Error: Invalid config, there must be at least one creator.
    at createCandyMachineV2 (/root/mock-nft/metaplex/js/packages/cli/src/helpers/accounts.ts:127:11)
    at uploadV2 (/root/mock-nft/metaplex/js/packages/cli/src/commands/upload.ts:130:45)
    at Command.<anonymous> (/root/mock-nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

has occured.

However, there is not anything about specifying the field `creators` in [docs](https://docs.metaplex.com/candy-machine-v2/configuration).

After a little bit of hacking, commenting all the `creators` code in `metaplex/js/packages/cli/src/helpers/accounts.ts`

```
  if (!candyData.creators || candyData.creators.length === 0) {
    throw new Error(`Invalid config, there must be at least one creator.`);
  }

  const totalShare = (candyData.creators || []).reduce(
    (acc, curr) => acc + curr.share,
    0,
  );

  if (totalShare !== 100) {
    throw new Error(`Invalid config, creators shares must add up to 100`);
  }
```
can temporarily walk around the issue.

**Comment by burningalc** [comment]
My bad, this `creators` field is about on the json of the NFT itself
