### ISSUE TITLE
"bad secret key size" Errror 

### ISSUE THREAD

**Issue by Nicksart** [metaplex-foundation/metaplex#1536]
After i upload candy machine v2 (devnet) i try to veryfi it and mint 1 token and got "bad severt key size" error. Can't do anything with it. 

https://prnt.sc/26d5snm

**Comment by samuelvanderwaal** [comment]
You're passing in your "config.json" file instead of your actual secret key file.

**Comment by Stevein5280** [comment]
I'm also getting this message 
`ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k TWallet_Keypair/pubkey.json \
    -cp js/packages/cli/upload-config.json \
    -c example \
    ./assets
(node:32774) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32774) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
/Users/strra/Desktop/Solana-NFT-Generator/metaplex/js/node_modules/tweetnacl/nacl-fast.js:2320
    throw new Error('bad secret key size');
          ^
Error: bad secret key size
    at Function.fromSecretKey (/Users/strra/Desktop/Solana-NFT-Generator/metaplex/js/node_modules/tweetnacl/nacl-fast.js:2320:11)
    at Function.fromSecretKey (/Users/strra/Desktop/Solana-NFT-Generator/metaplex/js/node_modules/@solana/web3.js/src/keypair.ts:64:39)
    at loadWalletKey (/Users/strra/Desktop/Solana-NFT-Generator/metaplex/js/packages/cli/src/helpers/accounts.ts:595:26)
    at Command.<anonymous> (/Users/strra/Desktop/Solana-NFT-Generator/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:132:40)
    at Command.listener [as _actionHandler] (/Users/strra/Desktop/Solana-NFT-Generator/metaplex/js/packages/cli/node_modules/commander/lib/command.js:488:17)`
