### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '\--e'

### ISSUE THREAD

**Issue by realisttt** [metaplex-foundation/metaplex#1586]
Facing this problem when trying to upload / create candy machine, any help is appreciated!

C:\Users\Derick>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \--e devnet \   -k ~/.config/solana/devnet.json \   -cp ~\metaplex\js\packages\cli\config.json-c example \ ~\metaplex\js\packages\cli\assets
Error: ENOENT: no such file or directory, scandir '\--e'
    at Object.readdirSync (node:fs:1390:3)
    at Argument.parseArg (C:\Users\Derick\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:63:17)
    at myParseArg (C:\Users\Derick\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1088:34)
    at C:\Users\Derick\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1120:19
    at Array.forEach (<anonymous>)
    at Command._processArguments (C:\Users\Derick\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1103:16)
    at Command._parseCommand (C:\Users\Derick\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1223:12)
    at Command._dispatchSubcommand (C:\Users\Derick\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1050:25)
    at Command._parseCommand (C:\Users\Derick\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1193:19)
    at Command.parse (C:\Users\Derick\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:897:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '\\--e'

**Comment by tomtom1233** [comment]
I think it might be because you have 2 (-) at -e devnet 

C:\Users\Derick>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~\metaplex\js\packages\cli\config.json-c example \ ~\metaplex\js\packages\cli\assets
should be this command

**Comment by realisttt** [comment]
C:\Users\Derick>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~\metaplex\js\packages\cli\config.json-c example \ ~\metaplex\js\packages\cli\assets
wallet public key: 3g8z3NrjLEekogyXjZRbf7L9coTYWBMySagydXuEFeLT
Error: ENOENT: no such file or directory, open '~\metaplex\js\packages\cli\config.json-c'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCandyMachineV2Config (C:\Users\Derick\~\metaplex\js\packages\cli\src\helpers\various.ts:53:27)
    at Command.<anonymous> (C:\Users\Derick\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:99:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '~\\metaplex\\js\\packages\\cli\\config.json-c'
  
  came back with this error @tomtom1233
