### ISSUE TITLE
upload was not successful, please re-run. SyntaxError: Unexpected token } in JSON at position 682

### ISSUE THREAD

**Issue by NabiiBux** [metaplex-foundation/metaplex#1594]
trying to upload image 36: Panda #33
File uploaded: https://arweave.net/14EGm5UUZdEmn-7upBqEZ_upUCQ5cf1p_YncnR0foFg
Updating cache for  240
upload was not successful, please re-run. SyntaxError: Unexpected token } in JSON at position 682
    at JSON.parse (<anonymous>)
    at getAssetManifest (C:\Users\Nabibux\Desktop\solana\metaplex\js\packages\cli\src\commands\upload.ts:441:35)
    at C:\Users\Nabibux\Desktop\solana\metaplex\js\packages\cli\src\commands\upload.ts:230:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 4)
    at uploadV2 (C:\Users\Nabibux\Desktop\solana\metaplex\js\packages\cli\src\commands\upload.ts:221:7)
    at Command.<anonymous> (C:\Users\Nabibux\Desktop\solana\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
PS C:\Users\Nabibux\Desktop\solana\metaplex\js\packages\cli\src>

can somebody help me here?. I am uploading 310 nfts but got this error after uploading 150 plus nfts

**Comment by 21e8** [comment]
you have a broken json file somewhere

**Comment by NabiiBux** [comment]
Thanks issue was resolved after updating json files

**Comment by CaduceusInc** [comment]
> you probably have a broken json file somewhere. check the files here: https://jsonlint.com/

Hi, I also have the same issue. I used jsonlint to validate my config and 0.json, 1.json, 2.json and 3.json files, but still run into this error when I run the command:

ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp config.json ./assets

Here is my trace:
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 3 (img+json) pairs
started at: 1650199019148
upload was not successful, please re-run. SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getAssetManifest (/Users/wale/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:474:35)
    at uploadV2 (/Users/wale/metaplex-foundation/metaplex/js/packages/cli/src/commands/upload.ts:123:32)
    at Command.<anonymous> (/Users/wale/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:269:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
