### ISSUE TITLE
RangeError: Indeterminate Span 

### ISSUE THREAD

**Issue by Zalapenos** [metaplex-foundation/metaplex#1596]
![error](https://user-images.githubusercontent.com/74668676/150166545-e2aaa647-c707-4b68-bc7c-82c5a25b26bb.PNG)

Have looked around for other errors similar but it seems like there is no error reports on the web of this exact error

**Comment by kir4567** [comment]
Same thing, does not work at all even with one img+json pair.

$ ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp ./config.json -c example -l debug ./assets
setting the log value to: debug
wallet public key: 6J6WxWZkAU1kgJ5Z4r4xbMoFxzjTLtETVSeRRAY5iTRF
program id from anchor cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 1 (img+json) pairs
started at: 1642640056623
initializing candy machine
Error deploying config to Solana network. RangeError: indeterminate span
    at Structure.getSpan (/Users/Kirill/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1221:13)
    at Structure.encode (/Users/Kirill/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1267:23)
    at InstructionCoder._encode (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:85:24)
    at InstructionCoder.encode (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:68:17)
    at /Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/index.ts:51:56
    at ix (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:43:15)
    at txFn (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/transaction.ts:17:14)
    at Object.rpc [as initializeCandyMachine] (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:16:18)
    at createCandyMachineV2 (/Users/Kirill/metaplex/js/packages/cli/src/helpers/accounts.ts:149:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. RangeError: indeterminate span
    at Structure.getSpan (/Users/Kirill/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1221:13)
    at Structure.encode (/Users/Kirill/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1267:23)
    at InstructionCoder._encode (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:85:24)
    at InstructionCoder.encode (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:68:17)
    at /Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/index.ts:51:56
    at ix (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:43:15)
    at txFn (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/transaction.ts:17:14)
    at Object.rpc [as initializeCandyMachine] (/Users/Kirill/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:16:18)
    at createCandyMachineV2 (/Users/Kirill/metaplex/js/packages/cli/src/helpers/accounts.ts:149:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by HassanRaza02** [comment]
Facing the same issue.

**Comment by Random-Nico** [comment]
Same, anyone know how to solve this yet? I think it might be an issue with the directories, it's the only thing I can think of

**Comment by RidhwanDev** [comment]
Also facing the issue, any updates on this one?

**Comment by stegaBOB** [comment]
This could be an issue with the length of the names/symbols of your NFTs. This is more an issue regarding needing better logging. Our [Discord](https://discord.gg/metaplex) may be a better place to get help.
