### ISSUE TITLE
Upload / Done. Successful = false.

### ISSUE THREAD

**Issue by gambitboxdev** [metaplex-foundation/metaplex#1598]
I've run the `upload` command with 1,000 (img+json) pairs on the mainnet
and it seemed like it was going alright, however, I have received "`Translating error Error: Transaction was not confirmed in 60.01 seconds.`" in few parts. At the end it said "`Done. Successful = false.`"

Do I just need to keep re-uploading and wasting a lot of SOL until it says "Done. Successful = true"?
or is there other solutions?

```
PS C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection> ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/mainnet-beta -cp ./config.json -c example ./assets --rpc-url https://.....
wallet public key: HTfazzDTBFpoETdjxLMk47jNaq9YUp1Xkz2Y9e4zBWfP
USING CUSTOM URL https://....
Beginning the upload for 1000 (img+json) pairs
started at: 1642596702208
initializing candy machine
initialized config for a candy machine with publickey: BhCwyLz6ACigmZ6MBD6ZVKAhQKdtVrb2e7KnGhoNJdWk
Uploading Size 1000 { mediaExt: '.png', index: '0' }
Saved bundle upload result to cache.
Computed Bundle range, including 362 file pair(s) totaling 99.905MB.
Uploading bundle via bundlr... in multiple transactions
0.01465437 SOL to upload
Bundle uploaded!
Saved bundle upload result to cache.
Computed Bundle range, including 363 file pair(s) totaling 99.996MB.
Uploading bundle via bundlr... in multiple transactions
0.014656284 SOL to upload
Bundle uploaded!
Saved bundle upload result to cache.
Computed Bundle range, including 275 file pair(s) totaling 76.030MB.
Uploading bundle via bundlr... in multiple transactions
0.011142907 SOL to upload
Bundle uploaded!
Saved bundle upload result to cache.
Upload done.
Writing indices 0-9
Writing indices 10-19
Writing indices 20-29
Writing indices 30-39
Writing indices 40-49
Writing indices 50-59
Writing indices 60-69
Writing indices 70-79
Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature hagiTEHRBaApcfptocMXykNJkMxL7AkYpq4uA2KwHkZxULyV1mKmShUwS4KqiBtJvLayfGqXRqG1gkLEdArXcUX using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
saving config line 70-79 failed Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature hagiTEHRBaApcfptocMXykNJkMxL7AkYpq4uA2KwHkZxULyV1mKmShUwS4KqiBtJvLayfGqXRqG1gkLEdArXcUX using the Solana Explorer or CLI tools.       
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
Writing indices 80-89
Writing indices 90-99
Writing indices 100-109
Writing indices 110-119
Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature HZzPRqHDnTZo6vU1ahumP7u5F3WUAbSshq9DGe79oiRUqVr7Hs2Pbwag6ca5GUrfy4e8zr7Qgm647kFY7PbLg8T using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
saving config line 110-119 failed Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature HZzPRqHDnTZo6vU1ahumP7u5F3WUAbSshq9DGe79oiRUqVr7Hs2Pbwag6ca5GUrfy4e8zr7Qgm647kFY7PbLg8T using the Solana Explorer or CLI tools.     
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
Writing indices 120-129
Writing indices 130-139
Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5tXAEmj8RNK9jGxA74EqJpRXcKRX2v2wAq5sJaC1P6Xq8etXSRcFfHWTx8Q7cniVANtvrP6ek4bNUz8Kg2xyE172 using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
saving config line 130-139 failed Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 5tXAEmj8RNK9jGxA74EqJpRXcKRX2v2wAq5sJaC1P6Xq8etXSRcFfHWTx8Q7cniVANtvrP6ek4bNUz8Kg2xyE172 using the Solana Explorer or CLI tools.    
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
Writing indices 140-149
Writing indices 150-159
Writing indices 160-169
Writing indices 170-179
Writing indices 180-189
Writing indices 190-199
Writing indices 200-209
Writing indices 210-219
Writing indices 220-229
Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 5HhP4GwqcQxrV5hUqo4LS22wEznnavWBuBVuVfEhQtAxVmFZo3hTJY8Xhn9jLvQkH6ZMw3Hg9YttmmEpxmcGYLhh using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
saving config line 220-229 failed Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 5HhP4GwqcQxrV5hUqo4LS22wEznnavWBuBVuVfEhQtAxVmFZo3hTJY8Xhn9jLvQkH6ZMw3Hg9YttmmEpxmcGYLhh using the Solana Explorer or CLI tools.    
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
Writing indices 230-239
Writing indices 240-249
Writing indices 250-259
Writing indices 260-269
Writing indices 270-279
Writing indices 280-289
Writing indices 290-299
Writing indices 300-309
Writing indices 310-319
Writing indices 320-329
Writing indices 330-339
Writing indices 340-349
Writing indices 350-359
Writing indices 360-369
Writing indices 370-379
Writing indices 380-389
Writing indices 390-399
Writing indices 400-409
Writing indices 410-419
Writing indices 420-429
Writing indices 430-439
Writing indices 440-449
Writing indices 450-459
Translating error Error: Transaction was not confirmed in 60.02 seconds. It is unknown if it succeeded or failed. Check signature 3QyAeMtJ4zWrS6q7msKWQpgdN7kbPdBr7VvQJAYwQxoFnS2cELebKJNg4h3Qqbx9iZ97TzrhYqFSfAAuJSWy9dnd using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
saving config line 450-459 failed Error: Transaction was not confirmed in 60.02 seconds. It is unknown if it succeeded or failed. Check signature 3QyAeMtJ4zWrS6q7msKWQpgdN7kbPdBr7VvQJAYwQxoFnS2cELebKJNg4h3Qqbx9iZ97TzrhYqFSfAAuJSWy9dnd using the Solana Explorer or CLI tools.    
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
Writing indices 460-469
Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature f8fEF3ViTy18GMfguphA5FjN77g6XxsMgwUDFneQoYHbHzPUyrpP8XsCYVWNFSHQzksJvYa4CWYQzURzxSqv4VU using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
saving config line 460-469 failed Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature f8fEF3ViTy18GMfguphA5FjN77g6XxsMgwUDFneQoYHbHzPUyrpP8XsCYVWNFSHQzksJvYa4CWYQzURzxSqv4VU using the Solana Explorer or CLI tools.     
    at Connection.confirmTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2686:13)
    at async sendAndConfirmRawTransaction (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:320:19    
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\commands\upload.ts:300:7)
    at async Command.<anonymous> (C:\Users\admin\Desktop\candy-machine-v2\the-quantum-mind-collection\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7)
Writing indices 470-479
Writing indices 480-489
Writing indices 490-499
Writing indices 500-509
Writing indices 510-519
Writing indices 520-529
Writing indices 530-539
Writing indices 540-549
Writing indices 550-559
Writing indices 560-569
Writing indices 570-579
Writing indices 580-589
Writing indices 590-599
Writing indices 600-609
Writing indices 610-619
Writing indices 620-629
Writing indices 630-639
Writing indices 640-649
Writing indices 650-659
Writing indices 660-669
Writing indices 670-679
Writing indices 680-689
Writing indices 690-699
Writing indices 700-709
Writing indices 710-719
Writing indices 720-729
Writing indices 730-739
Writing indices 740-749
Writing indices 750-759
Writing indices 760-769
Writing indices 770-779
Writing indices 780-789
Writing indices 790-799
Writing indices 800-809
Writing indices 810-819
Writing indices 820-829
Writing indices 830-839
Writing indices 840-849
Writing indices 850-859
Writing indices 860-869
Writing indices 870-879
Writing indices 880-889
Writing indices 890-899
Writing indices 900-909
Writing indices 910-919
Writing indices 920-929
Writing indices 930-939
Writing indices 940-949
Writing indices 950-959
Writing indices 960-969
Writing indices 970-979
Writing indices 980-989
Writing indices 990-999
Done. Successful = false.
ended at: 2022-01-19T14:28:24.977Z. time taken: 01:36:42
```

**Comment by psavva** [comment]
Reupload, it continues the ones that failed...

**Comment by gambitboxdev** [comment]
> w

Oh right ... Thanks for the clarification.
