### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Instinct1V** [metaplex-foundation/metaplex#1612]
This is what i recieve, how do i fix it??

import * as anchor from '@project-serum/anchor';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at main (/usr/local/lib/node_modules/ts-node/src/bin.ts:331:12)

**Comment by stegaBOB** [comment]
If you are still having this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). Thanks.

**Comment by codewithsyre** [comment]
august@Augusts-MacBook-Pro JavaScript % npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/august/Documents/JavaScript/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/august/Documents/JavaScript/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/august/.npm/_logs/2022-02-26T11_30_48_926Z-debug-0.log
