### ISSUE TITLE
Non-base58 character Error

### ISSUE THREAD

**Issue by fxxkk** [metaplex-foundation/metaplex#1624]
as soon as I use the upload command I keep getting this error:
 throw new Error('Non-base' + BASE + ' character')
          ^
Error: Non-base58 character
    at Object.decode (C:\Users\Felix\Desktop\v2\metaplex\js\node_modules\base-x\src\index.js:111:11)
    at new PublicKey (C:\Users\Felix\Desktop\v2\metaplex\js\node_modules\@solana\web3.js\src\publickey.ts:56:30)
    at getCandyMachineV2Config (C:\Users\Felix\Desktop\v2\metaplex\js\packages\cli\src\helpers\various.ts:150:9)
    at Command.<anonymous> (C:\Users\Felix\Desktop\v2\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:99:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 

can anyone please help me?

**Comment by prashantcrypto** [comment]
Yes i can. 
My discord shyaid#5168

**Comment by rcturner7** [comment]
Hi, did anyone figure out this error.  I am getting the same error.

**Comment by Khushhal23** [comment]
Check your json files for this error

**Comment by stegaBOB** [comment]
If you are still having this issue, please open a new issue that includes all the required info in our GitHub issue form (it will show the needed info automatically now when you open an issue). Thanks.

**Comment by ZaryabArif** [comment]
as soon as I use the upload command I keep getting this error:
throw new Error('Non-base' + BASE + ' character')
^
Error: Non-base58 character
at Object.decode (C:\Users\Felix\Desktop\v2\metaplex\js\node_modules\base-x\src\index.js:111:11)
at new PublicKey (C:\Users\Felix\Desktop\v2\metaplex\js\node_modules@solana\web3.js\src\publickey.ts:56:30)
at getCandyMachineV2Config (C:\Users\Felix\Desktop\v2\metaplex\js\packages\cli\src\helpers\various.ts:150:9)
at Command. (C:\Users\Felix\Desktop\v2\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:99:38)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

can anyone please help me?

**Comment by Khushhal23** [comment]
Ur json files are incorrect

**Comment by Rad-Art** [comment]
G:\solana\metaplex-master\js\node_modules\base-x\src\index.js:111
    throw new Error('Non-base' + BASE + ' character')
          ^
Error: Non-base58 character
    at Object.decode (G:\solana\metaplex-master\js\node_modules\base-x\src\index.js:111:11)
    at Object.decode (G:\solana\metaplex-master\js\node_modules\@project-serum\anchor\src\utils\bytes\bs58.ts:8:15)
    at loadWalletKey (G:\solana\metaplex-master\js\packages\cli\src\helpers\accounts.ts:526:14)
    at Command.<anonymous> (G:\solana\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:140:40)
    at Command.listener [as _actionHandler] (G:\solana\metaplex-master\js\packages\cli\node_modules\commander\lib\command.js:480:17)
    at G:\solana\metaplex-master\js\packages\cli\node_modules\commander\lib\command.js:1234:65
    at Command._chainOrCall (G:\solana\metaplex-master\js\packages\cli\node_modules\commander\lib\command.js:1151:12)
    at Command._parseCommand (G:\solana\metaplex-master\js\packages\cli\node_modules\commander\lib\command.js:1234:27)
    at Command._dispatchSubcommand (G:\solana\metaplex-master\js\packages\cli\node_modules\commander\lib\command.js:1057:25)
    at Command._parseCommand (G:\solana\metaplex-master\js\packages\cli\node_modules\commander\lib\command.js:1200:19)

I have the same Ettor anyone help me please to understand the solve?

**Comment by AldanisVigo** [comment]
> 

I am getting the same exact thing as you. I tried everything. I changed the wallet address several times and nothing. Keep getting this same exact error. Hope someone has the solution soon. I want to try this out.

**Comment by itsdiay** [comment]
I was able to fix this error by encoded the key with `base58.encode(Buffer.from(privateKey, 'hex'))`

**Comment by Gordi769** [comment]
Šta da radim s ovim error 58
