### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by G0804019u** [metaplex-foundation/metaplex#1718]
### Which package is this bug report for?

candy machine cli

### Issue description

give error saying module not found

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/wolfie-mainnet.json -cp ~\metaplex\js\packages\cli\config.json -c example ~\metaplex\js\packages\cli\assets
```

### Relevant log output

```shell
PS C:\Users\justy\nft_collection\~\metaplex> ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ~/.config/solana/wolfie-mainnet.json -cp ~\metaplex\js\packages\cli\config.json -c example ~\metaplex\js\packages\cli\assets
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './candy-machine-v2-cli.ts'
Require stack:
- C:\Users\justy\nft_collection\~\metaplex\~\metaplex\js\packages\cli\src\imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (C:\Users\justy\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:321:16)
    at getProjectSearchDir (C:\Users\justy\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:291:40)
    at main (C:\Users\justy\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:193:27)
    at Object.<anonymous> (C:\Users\justy\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:351:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\justy\\nft_collection\\~\\metaplex\\~\\metaplex\\js\\packages\\cli\\src\\imaginaryUncacheableRequireResolveScript'
  ]
```

### Operating system

window 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Please try asking in our [Discord](https://discord.gg/metaplex). This question would be better asked there.
