### ISSUE TITLE
[Bug]: Create Candy Machine / upload was not successful, please re-run. SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by andi00x** [metaplex-foundation/metaplex#1732]
### Which package is this bug report for?

candy machine cli

### Issue description

I want to create candy machine but I get this error.

### Command

```shell
ts-node C:\Users\Andi\Downloads\Solana\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -e devnet -k C:\Users\Andi\Downloads\Solana\~\.config\solana\wallet.json -cp C:\Users\Andi\Downloads\Solana\metaplex\js\packages\cli\config.json -c temp C:\Users\Andi\Downloads\Solana\metaplex\js\packages\cli\assets
```

### Relevant log output

```shell
wallet public key: HwWmYcicV2kJjqtACAcFJ3n4eypJgq6W2DxfWUNo114o
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 2 (img+json) pairs
started at: 1644152729960
upload was not successful, please re-run. SyntaxError: Unexpected token { in JSON at position 292
    at JSON.parse (<anonymous>)
    at getAssetManifest (C:\Users\Andi\Downloads\Solana\metaplex\js\packages\cli\src\commands\upload.ts:465:35)        
    at uploadV2 (C:\Users\Andi\Downloads\Solana\metaplex\js\packages\cli\src\commands\upload.ts:106:32)
    at Command.<anonymous> (C:\Users\Andi\Downloads\Solana\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:219:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
PS C:\Users\Andi\Downloads\Solana\metaplex>
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Randy808** [comment]
This just seems like you have a problem with your json, not a bug with the candy-machine-v2-cli

**Comment by andi00x** [comment]
> This just seems like you have a problem with your json, not a bug with the candy-machine-v2-cli

Oh sry, Which JSON could act?

**Comment by stegaBOB** [comment]
This is a better question for our Discord. Please ask there. Thanks. https://discord.gg/metaplex
