### ISSUE TITLE
[Bug]: 'ERR_INVALID_ARG_TYPE'

### ISSUE THREAD

**Issue by SiawaschAmootari** [metaplex-foundation/metaplex#1733]
### Which package is this bug report for?

other

### Issue description

i think the problem is that it does not recognize my images and the json files but i have specified the path to the folder correctly i have double checked everything again can anyone help me ?

![Unbenannt](https://user-images.githubusercontent.com/38475312/152684387-9d18c398-e4e0-4620-8da2-d6d66d52fa53.png)
![Unbenannty](https://user-images.githubusercontent.com/38475312/152684572-d1baadc3-ec33-43d0-9f9b-bc48a57f8f60.png)

### Command

```shell
ts-node C:\Users\Fabio\Desktop\NFTStuff\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload \ -e mainnet-beta \ -k  C:\Users\Fabio\Desktop\NFTStuff\keypair\.config\solana\id.json \ -cp C:\Users\Fabio\Desktop\NFTStuff\metaplex\js\packages\cli\config.json \ -c C:\Users\Fabio\Desktop\NFTStuff\assets
```

### Relevant log output

```shell
C:\Users\Fabio\Desktop\NFTStuff>ts-node C:\Users\Fabio\Desktop\NFTStuff\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload \ -e mainnet-beta \ -k  C:\Users\Fabio\Desktop\NFTStuff\keypair\.config\solana\id.json \ -cp C:\Users\Fabio\Desktop\NFTStuff\metaplex\js\packages\cli\config.json \ -c C:\Users\Fabio\Desktop\NFTStuff\assets
wallet public key: FtuNnnUirYXPbUNjVPvcnZF7QTd3NPP8YUBxM8qcp2s8
WARNING: Skipping unsupported file type \$AV_AVG
WARNING: Skipping unsupported file type \$Recycle.Bin
WARNING: Skipping unsupported file type \$WinREAgent
WARNING: Skipping unsupported file type \82ace7d6-0197-474d-bf4b-a2043e72329b
WARNING: Skipping unsupported file type \BOOTNXT
WARNING: Skipping unsupported file type \Dokumente und Einstellungen
WARNING: Skipping unsupported file type \DumpStack.log.tmp
WARNING: Skipping unsupported file type \ESD
WARNING: Skipping unsupported file type \hiberfil.sys
WARNING: Skipping unsupported file type \hp
WARNING: Skipping unsupported file type \inetpub
WARNING: Skipping unsupported file type \Intel
WARNING: Skipping unsupported file type \PerfLogs
WARNING: Skipping unsupported file type \Program Files
WARNING: Skipping unsupported file type \Program Files (x86)
WARNING: Skipping unsupported file type \ProgramData
WARNING: Skipping unsupported file type \Programme
WARNING: Skipping unsupported file type \Python310
WARNING: Skipping unsupported file type \Recovery
WARNING: Skipping unsupported file type \solana-install-tmp
WARNING: Skipping unsupported file type \swapfile.sys
WARNING: Skipping unsupported file type \SWSetup
WARNING: Skipping unsupported file type \System Volume Information
WARNING: Skipping unsupported file type \SYSTEM.SAV
WARNING: Skipping unsupported file type \Users
WARNING: Skipping unsupported file type \Windows
Beginning the upload for 9921 (img+json) pairs
started at: 1644155348043
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.dirname (path.js:619:5)
    at uploadV2 (C:\Users\Fabio\Desktop\NFTStuff\metaplex\js\packages\cli\src\commands\upload.ts:100:24)
    at Command.<anonymous> (C:\Users\Fabio\Desktop\NFTStuff\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:219:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
You added a -c before the assets path. You need to remove that first.

**Comment by SiawaschAmootari** [comment]
i changed it but still no difference  same output

**Comment by SiawaschAmootari** [comment]
> You added a -c before the assets path. You need to remove that first.

i changed it but still no difference same output

**Comment by Pyr0zen** [comment]
I have the same problem

**Comment by reedjones** [comment]
same problem
