### ISSUE TITLE
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by ben112233** [metaplex-foundation/metaplex#1744]
### Which package is this bug report for?

candy machine cli

### Issue description

I have had these issues for a couple of hours now and I cannot find a way to fix them. Any help would be appreciated.

### Command

```shell
C:\Users\1\OneDrive\desktop\solana\metaplex>ts-node "C:/users/1/OneDrive/desktop/solana/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts" upload \ -e devnet \ -k "C:/Users/1/OneDrive/desktop/solana/metaplex/~/.config/solana/devnet.json" \ -cp "C:/Users/1/OneDrive/desktop/solana/metaplex/config.json" \ "C:/Users/1/OneDrive/desktop/solana/metaplex/assets"
```

### Relevant log output

```shell
wallet public key: CEb3E82GNy6P6ehmJrJb3b8ypmW6oXacbk52PTR8kuZB
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type \$Recycle.Bin
WARNING: Skipping unsupported file type \$SysReset
WARNING: Skipping unsupported file type \$WinREAgent
WARNING: Skipping unsupported file type \config
WARNING: Skipping unsupported file type \Documents and Settings
WARNING: Skipping unsupported file type \DRIVER
WARNING: Skipping unsupported file type \DumpStack.log
WARNING: Skipping unsupported file type \DumpStack.log.tmp
WARNING: Skipping unsupported file type \hiberfil.sys
WARNING: Skipping unsupported file type \OneDriveTemp
WARNING: Skipping unsupported file type \pagefile.sys
WARNING: Skipping unsupported file type \PerfLogs
WARNING: Skipping unsupported file type \Program Files
WARNING: Skipping unsupported file type \Program Files (x86)
WARNING: Skipping unsupported file type \ProgramData
WARNING: Skipping unsupported file type \Python310
WARNING: Skipping unsupported file type \Recovery
WARNING: Skipping unsupported file type \solana-install-tmp
WARNING: Skipping unsupported file type \swapfile.sys
WARNING: Skipping unsupported file type \System Volume Information
WARNING: Skipping unsupported file type \Users
WARNING: Skipping unsupported file type \Windows
Beginning the upload for 5 (img+json) pairs
started at: 1644308955978
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (C:\users\1\OneDrive\desktop\solana\metaplex\js\packages\cli\src\commands\upload.ts:97:24)
    at Command.<anonymous> (C:\users\1\OneDrive\desktop\solana\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Operating system

window 11

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by SiawaschAmootari** [comment]
i have the exact same problem now for 4-5 days need help too....

**Comment by stegaBOB** [comment]
This is not a Metaplex issue. You likely have some sort of issue with your packages. Try deleting the node_modules folder and reinstalling with `yarn install`. If that doesn't work, please try asking in our discord: https://discord.gg/metaplex
