### ISSUE TITLE
Upload Error please help[Bug]: 

### ISSUE THREAD

**Issue by JasonJvV** [metaplex-foundation/metaplex#1764]
### Which package is this bug report for?

candy machine cli

### Issue description

When I try to run the upload of CM2, I get the error below that the module is not found. Id be grateful for any assistance, been stuck for a while now. 

I have checked my path, tried ./ vs ~/ I have also checked metaplex version installed correctly, yarn installed correctly. No idea what I'm missing

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp ~/metaplex/js/packages/cli/config.json -c example ~/metaplex/js/packages/cli/assets
```

### Relevant log output

```shell
Error: Cannot find module './candy-machine-v2-cli.ts'
Require stack:
- /Users/jasonjansevanvuuren/metaplex/js/packages/cli/src/imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at requireResolveNonCached (/usr/local/lib/node_modules/ts-node/dist/bin.js:321:16)
    at getProjectSearchDir (/usr/local/lib/node_modules/ts-node/dist/bin.js:291:40)
    at main (/usr/local/lib/node_modules/ts-node/dist/bin.js:193:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin.js:351:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jasonjansevanvuuren/metaplex/js/packages/cli/src/imaginaryUncacheableRequireResolveScript'
```

### Operating system

Mac M1

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by walter-grace** [comment]
Make sure you are using the correct path, I have add this issue when I didnt put my full path. Go to your vscode and file the candy-machine-v2-cli.ts and click copy path then paste it. That was how I solved this issue for myself
<img width="370" alt="Screen Shot 2022-02-10 at 8 41 01 AM" src="https://user-images.githubusercontent.com/31444892/153454202-553aeda4-77cd-49ab-99c1-886ab352464c.png">
e

**Comment by JasonJvV** [comment]
Thanks but still receiving the same error
