### ISSUE TITLE
[Bug]: Error: Cannot find module './candy-machine-v2-cli.js'

### ISSUE THREAD

**Issue by SOLBEYBLADE** [metaplex-foundation/metaplex#1785]
### Which package is this bug report for?

candy machine cli

### Issue description

- C:\Users\Sandeep\Desktop\solbeyblade\imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireResolveNonCached (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:375:16)
    at getProjectSearchDir (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:345:40)
    at main (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:220:27)
    at Object.<anonymous> (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:405:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Sandeep\\Desktop\\solbeyblade\\imaginaryUncacheableRequireResolveScript'
  ]

i dont know how to fix this issue  any one help me

### Command

```shell
ts-node candy-machine-v2-cli.js upload -e devnet -k C:\Users\Sandeep\Desktop\solbeyblade\~\.config\solana\solbeyblade.json -1 debug -c cm -cp \assets-packages c:\users\sandeep\git\cm\setup uploadfolder
```

### Operating system

WINDOW 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DojoSoMope** [comment]
Check your pathing.

**Comment by nullvoid237** [comment]
I think it should be `candy-machine-v2-cli.ts`
