### ISSUE TITLE
Error: Non-base58 character[Bug]: 

### ISSUE THREAD

**Issue by SOLBEYBLADE** [metaplex-foundation/metaplex#1790]
### Which package is this bug report for?

candy machine ui

### Issue description

 at Object.decode (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\node_modules\base-x\src\index.js:111:11)
    at new PublicKey (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\node_modules\@solana\web3.js\src\publickey.ts:56:30)
    at getCandyMachineV2Config (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\packages\cli\src\helpers\various.ts:152:9)
    at Command.<anonymous> (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:107:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet --keypair C:/Users/Sandeep/.config/solana/cli/devnet-test.json -cp C:/Users/Sandeep/Desktop/Solbeyblade/metaplex-master/js/beyblade.json ./assets
```

### Relevant log output

```shell
at Object.decode (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\node_modules\base-x\src\index.js:111:11)
    at new PublicKey (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\node_modules\@solana\web3.js\src\publickey.ts:56:30)
    at getCandyMachineV2Config (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\packages\cli\src\helpers\various.ts:152:9)
    at Command.<anonymous> (C:\Users\Sandeep\Desktop\Solbeyblade\metaplex-master\js\packages\cli\src\candy-machine-v2-cli.ts:107:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

WINDOW 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Can you share your config file please?

**Comment by SOLBEYBLADE** [comment]
---
json_rpc_url: "https://metaplex.devnet.rpcpool.com/"
websocket_url: ""
keypair_path: "C:\\Users\\Sandeep\\.config\\solana\\cli\\devnet-test.json"
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed

**Comment by yamijuan** [comment]
the `config.json` file. Looks like one of the addresses is incorrect

**Comment by stegaBOB** [comment]
If you're still having issues, please try asking in our discord (https://discord.gg/metaplex)

**Comment by Rad-Art** [comment]
I have the same error now anyone can help please?

**Comment by LorenzoElenkov** [comment]
Most likely the 
> --keypair ...

pathing is not correct.

I managed to fix it on my end by simply putting
> -k ./relative/path/from/where you are currently in

My case structure looks like this:

(folder) MY MAIN FOLDER LOCATED ON DESKTOP
-- (folder) assets
-- (folder) metaplex
-- (folder) wallets
-- (file) config.json

I have set my terminal (VS Code) location from lowest order folder (MY MAIN FOLDER LOCATED ON DESKTOP) and when I run the command I run the following thing:

ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ./wallets/Payer.json \
    -cp config.json \
    ./assets

As you can see here in ***-k ./wallets/Payer.json*** I have the pathing starting from main folder not from root folder of OS.

NOTE: I AM WORKING ON MACOS SYSTEM!

I hope this explains it well and fix it for you.
