### ISSUE TITLE
Upload problems with Candy-machine-v2/ problems with folder[Bug]: 

### ISSUE THREAD

**Issue by Tix00** [metaplex-foundation/metaplex#1814]
### Which package is this bug report for?

candy machine cli

### Issue description

I was following the candy machine v2 guide: https://docs.metaplex.com/candy-machine-v2/getting-started
Everithing is set up correctly:
```
{
    "price": 1.0,
    "number": 1,
    "gatekeeper": null,
    "solTreasuryAccount": "4u7YLzfmQoqmFiEai2Yybxr9FkbqPWJFxwUYTY3M3GWd",
    "splTokenAccount": null,
    "splToken": null,
    "goLiveDate": "25 Mar 2022 00:00:00 GMT",
    "endSettings": null,
    "whitelistMintSettings": null,
    "hiddenSettings": null,
    "storage": "arweave-sol",
    "ipfsInfuraProjectId": null,
    "ipfsInfuraSecret": null,
    "awsS3Bucket": null,
    "noRetainAuthority": false,
    "noMutable": false
}
```

this is my congif.json file

`
    Directory: C:\Users\User\Documents\nftmint\~\~\metaplex\assets

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        17/02/2022     12:05            408 0.json
-a----        17/02/2022     12:05           5218 0.png`

This is my assets folder

The dev net is correctly set up.

When using the upload command it doesnt detect the assets folder(containing the nft).
What might be the problem?

### Command

```shell
PS C:\Users\User\Documents\nftmint\~> ts-node C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload     -e devnet     -k C:\Users\User\~\.config\solana     -cp config.json   -c example C:\Users\User\Documents\nftmint\~\~\metaplex\js\assets\images
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at loadWalletKey (C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\src\helpers\accounts.ts:571:34)
    at Command.<anonymous> (C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:84:40)
    at Command.listener [as _actionHandler] (C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:488:17)
    at C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1227:65
    at Command._chainOrCall (C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1144:12)
    at Command._parseCommand (C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1227:27)
    at Command._dispatchSubcommand (C:\Users\User\Documents\nftmint\~\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1050:25) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
```

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DojoSoMope** [comment]
This looks like a system issue. Are you sure you have the correct access rights ?

**Comment by Tix00** [comment]
> This looks like a system issue. Are you sure you have the correct access rights ?

I checked with fs.accessSync, i don't. How can i grants permission to my script?

**Comment by Tix00** [comment]
> This looks like a system issue. Are you sure you have the correct access rights ?

I'm on windows btw

**Comment by Kunal123ETH** [comment]
also get same errror  EISDIR: illegal operation on a directory, read
