### ISSUE TITLE
hey guys can anyone help me with this error code 0x177d[Bug]: 

### ISSUE THREAD

**Issue by ZakariaRh** [metaplex-foundation/metaplex#1817]
### Which package is this bug report for?

candy machine cli

### Issue description

i cant find any thing on google about this error code 0x177d i cant update the candy machine and i cant upload any new assets.

### Command

```shell
C:\Users\user\Desktop\solana-nft\metaplex>ts-node C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts update_candy_machine -e devnet -k C:\Users\user\Desktop\solana-nft\devnet-wallet.json -cp C:\Users\user\Desktop\solana-nft\config.json -c example C:\Users\user\Desktop\solana-nft\assets
```

### Relevant log output

```shell
wallet public key: EHP1Gtd6RRfAxj6EJcASxSk5hhCqQWRZQZjdkU7sexCe
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x177d
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Instruction: UpdateCandyMachine
    Program log: Custom program error: 0x177d
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 7584 of 200000 compute units
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0x177d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x177d
    at Connection.sendEncodedTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3961:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3918:20)
    at async sendAndConfirmRawTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as updateCandyMachine] (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async Command.<anonymous> (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:799:16) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: UpdateCandyMachine',
    'Program log: Custom program error: 0x177d',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 7584 of 200000 compute units',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0x177d'
  ]
}
C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:35
      return new ProgramError(errorCode, errorMsg, errorCode + ": " + errorMsg);
             ^
ProgramError: 6013: Cannot change number of lines unless is a hidden config
    at Function.parse (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:35:14)
    at Object.rpc [as updateCandyMachine] (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:799:16) {
  code: 6013,
  msg: 'Cannot change number of lines unless is a hidden config'
}
```

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DojoSoMope** [comment]
You can't upload any new assets on an already initialized candy machine

**Comment by DojoSoMope** [comment]
You would have to withdraw this candymachine, and upload again with the right assets

**Comment by ZakariaRh** [comment]
> You would have to withdraw this candymachine, and upload again with the right assets

how can i withdraw the candymachine ?

**Comment by ZakariaRh** [comment]
> You would have to withdraw this candymachine, and upload again with the right assets

**Comment by ZakariaRh** [comment]
> You would have to withdraw this candymachine, and upload again with the right assets

can i do that with just a command or i have to start everything again

**Comment by ZakariaRh** [comment]
> You would have to withdraw this candymachine, and upload again with the right assets

i did it but it shows this when i want to upload again

**Comment by ZakariaRh** [comment]
C:\Users\user\Desktop\solana-nft\metaplex>ts-node C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -e devnet -k C:\Users\user\Desktop\solana-nft\devnet-wallet.json -cp C:\Users\user\Desktop\solana-nft\config.json -c example C:\Users\user\Desktop\solana-nft\assets
wallet public key: EHP1Gtd6RRfAxj6EJcASxSk5hhCqQWRZQZjdkU7sexCe
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 10 (img+json) pairs
started at: 1645221124085
config for a candy machine with publickey: Dd9YTDLQRoDUcAJymHZW39Rr3qqhXcqHyTLLh6SawsXy has been already initialized
Uploading Size 3 { mediaExt: '.png', index: '7' }
Processing asset: 0
Processing asset: 1
Processing asset: 2
Writing indices 0-9
Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Instruction: AddConfigLines
    Program log: Custom program error: 0xbc4
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 12219 of 200000 compute units
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0xbc4
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4
    at Connection.sendEncodedTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3961:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3918:20)
    at async sendAndConfirmRawTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:342:19
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:322:7)
    at async Command.<anonymous> (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:216:7) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    'Program log: Custom program error: 0xbc4',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 12219 of 200000 compute units',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0xbc4'
  ]
}
saving config line 0-9 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4
    at Connection.sendEncodedTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3961:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3918:20)
    at async sendAndConfirmRawTransaction (C:\Users\user\Desktop\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:342:19
    at async Promise.all (index 0)
    at async uploadV2 (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:322:7)
    at async Command.<anonymous> (C:\Users\user\Desktop\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:216:7) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    'Program log: Custom program error: 0xbc4',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 12219 of 200000 compute units',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0xbc4'
  ]
}
Done. Successful = false.
ended at: 2022-02-18T21:52:16.722Z. time taken: 00:00:12

**Comment by DojoSoMope** [comment]
I highly advise you follow the docs

**Comment by Khushhal23** [comment]
1. You can't upload more assets to an existing candy machine.
2. If the problem still persists, please verify the name of the NFTs in jsons are too long:)
