### ISSUE TITLE
[Bug]: SyntaxError: Unexpected token J in JSON at position 1

### ISSUE THREAD

**Issue by Kerambi** [metaplex-foundation/metaplex#1841]
### Which package is this bug report for?

candy machine cli

### Issue description

At first I had an error [ERR_INVALID_ARG_TYPE] but the config.json candy machine v2 was set up well. I tried to rebuild project and now I have an error SyntaxError: Unexpected token J in JSON at position 1 and I don't know what to do.

### Command

```shell
ts-node C:/Users/Administrator/my-generative-nfts/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
-e devnet \ 
-k C:/Users/Administrator/.config/solana/devnet.json \ 
-cp C:/Users/Administrator/my-generative-nfts/metaplex/config.json \ 
-c example \ 
 C:/Users/Administrator/my-generative-nfts/metaplex/assets
```

### Relevant log output

```shell
PS C:\Users\Administrator\my-generative-nfts\metaplex> ts-node C:/Users/Administrator/my-generative-nfts/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k C:/Users/Administrator/.config/solana/devnet.json \ -cp C:/Users/Administrator/my-generative-nfts/metaplex/config.json \ -c example \ C:/Users/Administrator/my-generative-nfts/metaplex/assets
C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\src\helpers\accounts.ts:571
    new Uint8Array(JSON.parse(fs.readFileSync(keypair).toString())),
                        ^
SyntaxError: Unexpected token J in JSON at position 1
    at JSON.parse (<anonymous>)
    at loadWalletKey (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\src\helpers\accounts.ts:571:25)
    at Command.<anonymous> (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:101:40)
    at Command.listener [as _actionHandler] (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\node_modules\commander\lib\command.js:488:17)
    at C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1227:65
    at Command._chainOrCall (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1144:12)
    at Command._parseCommand (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1227:27)
    at Command._dispatchSubcommand (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1050:25)
    at Command._parseCommand (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1193:19)
    at Command.parse (C:\Users\Administrator\my-generative-nfts\metaplex\js\packages\cli\node_modules\commander\lib\command.js:897:10)
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Khushhal23** [comment]
Hello! Please check your config file and assets json files. It's not a bug

**Comment by Kerambi** [comment]
> Hello! Please check your config file and assets json files. It's not a bug

This is my config.json , i think its good.

> {
  "price": 0.01,
  "number": 1000,
  "gatekeeper": {
    "gatekeeperNetwork": "ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6",
    "expireOnUse": true
  },
  "solTreasuryAccount": "3uE2RCfnKYRz27WM3KGorLPorAB8v4zrT5i9vpCrqgkV",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "22 FEB 2022 00:00:00 GMT",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "storage": "arweave",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "awsS3Bucket": null,
  "nftStorageKey": null,
  "noRetainAuthority": false,
  "noMutable": false
}

And assets json files was generated via hashlips

**Comment by Kerambi** [comment]
And when i put code from accounts.ts to https://jsonlint.com/
i get same error 

> Error: Parse error on line 1:
import {	Keypair,	
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by stegaBOB** [comment]
Looks like something may have happened to your keypair file. You may have accidentally deleted something in it. Try generating a new keypair file (with `solana-keygen new` or something like that) file if you cant find the error in your keypair file.
