### ISSUE TITLE
[Bug]: src/helpers/upload/arweave-bundle.ts:16:31 - error TS2307: Cannot find module '@bundlr-network/client/build/src/transaction'

### ISSUE THREAD

**Issue by Belacosaur** [metaplex-foundation/metaplex#1843]
### Which package is this bug report for?

other cli

### Issue description

After running NPM install which is successful
I go to check the version:
ts-node ./src/candy-machine-v2.cli.tss --version
I get the error:
TSError: ⨯ Unable to compile TypeScript:
src/helpers/upload/arweave-bundle.ts:14:20 - error TS2307: Cannot find module '@bundlr-network/client' or its corresponding type declarations.

14 import Bundlr from '@bundlr-network/client';
                      ~~~~~~~~~~~~~~~~~~~~~~~~
src/helpers/upload/arweave-bundle.ts:16:31 - error TS2307: Cannot find module '@bundlr-network/client/build/src/transaction' or its corresponding type declarations.

16 import BundlrTransaction from '@bundlr-network/client/build/src/transaction';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:828:12)
    at reportTSError (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:832:19)
    at getOutput (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1022:36)
    at Object.compile (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1326:43)
    at Module.m._compile (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1458:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1462:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  diagnosticCodes: [ 2307, 2307 ]
  
  I could not work out the fix so I continued onwards with the rest of the setup. after completing the test NFTs and metadata I ran:
  ts-node ./src/candy-machine-v2-cli.ts upload -e devnet -k C:users/caleb/.config/solana/devnet.json -p config.json -c temp ./assets
  
  and got the same error message as above.
  
  I tried doing a fresh pull and start again but still the same error occurs. What could be missing here?

### Command

```shell
ts-node ./src/candy-machine-v2.cli.tss --version
```

### Relevant log output

```shell
PS C:\Users\caleb\Desktop\Candy Machine\metaplex\js\packages\cli> ts-node ./src/candy-machine-v2-cli.ts upload -e devnet -k C:users/caleb/.config/solana/devnet.json -p config.json -c temp ./assets
C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:828
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/helpers/upload/arweave-bundle.ts:14:20 - error TS2307: Cannot find module '@bundlr-network/client' or its corresponding type declarations.

14 import Bundlr from '@bundlr-network/client';
                      ~~~~~~~~~~~~~~~~~~~~~~~~
src/helpers/upload/arweave-bundle.ts:16:31 - error TS2307: Cannot find module '@bundlr-network/client/build/src/transaction' or its corresponding type declarations.

16 import BundlrTransaction from '@bundlr-network/client/build/src/transaction';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at createTSError (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:828:12)
    at reportTSError (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:832:19)
    at getOutput (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1022:36)
    at Object.compile (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1326:43)
    at Module.m._compile (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1458:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1462:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  diagnosticCodes: [ 2307, 2307 ]
}
PS C:\Users\caleb\Desktop\Candy Machine\metaplex\js\packages\cli> ts-node ./src/candy-machine-v2-cli.ts upload -e devnet -k C:users/caleb/.config/solana/devnet.json -p config.json -c temp ./assets
C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:828
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/helpers/upload/arweave-bundle.ts:14:20 - error TS2307: Cannot find module '@bundlr-network/client' or its corresponding type declarations.

14 import Bundlr from '@bundlr-network/client';
                      ~~~~~~~~~~~~~~~~~~~~~~~~
src/helpers/upload/arweave-bundle.ts:16:31 - error TS2307: Cannot find module '@bundlr-network/client/build/src/transaction' or its corresponding type declarations.

16 import BundlrTransaction from '@bundlr-network/client/build/src/transaction';
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:828:12)
    at reportTSError (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:832:19)
    at getOutput (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1022:36)
    at Object.compile (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1326:43)
    at Module.m._compile (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1458:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\caleb\AppData\Roaming\nvm\v14.17.6\node_modules\ts-node\src\index.ts:1462:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  diagnosticCodes: [ 2307, 2307 ]
}
PS C:\Users\caleb\Desktop\Candy Machine\metaplex\js\packages\cli>
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
You ran npm install? You should be using yarn. Also, did you run `yarn bootstrap` in the js directory after running `npm install`

**Comment by stegaBOB** [comment]
I am unable to reproduce this issue. Closing for now. If you still have errors feel free to ask in our discord (https://discord.gg/metaplex)
