### ISSUE TITLE
[Bug]:  Error deploying config to Solana network. RangeError: indeterminate span

### ISSUE THREAD

**Issue by ArchTaqi** [metaplex-foundation/metaplex#1846]
### Which package is this bug report for?

candy machine cli

### Issue description

[](https://stackoverflow.com/posts/71026269/timeline)I'm trying to upload NFT assets to the Solana devnet using candy machine with json file metadata 

```json
{
  "name": "TEST",
  "symbol": "TSTX",
  "description": "TEST",
  "seller_fee_basis_points": 500,
  "image": "image.png",
  "external_url": "https://yourwebsite.com/details/0",
  "attributes": [
    {
      "value": "United States of America",
      "trait_type": "COUNTRY"
    },
    {
      "value": "1790",
      "trait_type": "FOUNDATION"
    },
    {
      "value": "George Washington",
      "trait_type": "NAMED FOR"
    },
    {
      "value": "680K+",
      "trait_type": "POP"
    }
  ],
  "collection": {
    "name": "OGs",
    "family": "Solana Candy Factory"
  },
  "properties": {
    "files": [
      {
        "uri": "image.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "share": 100,
        "address": "EZtysjsfwbRShJzAXZkHsj3PgUVrpSa1BzCqA43QFfCU"
      }
    ]
  }
}
```
when I run the command above, I get this error message like `Error deploying config to Solana network. RangeError: indeterminate span`. 

Any ideas on how to fix it?

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -l debug -cp config.json -c ape-family-nft-devnet ~/ape-family-nft
```

### Relevant log output

```shell
Beginning the upload for 6 (img+json) pairs
started at: 1645708453466
initializing candy machine
Error deploying config to Solana network. RangeError: indeterminate span
    at Structure.getSpan (/Users/muhammadtaqi/Projects/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1221:13)
    at Structure.encode (/Users/muhammadtaqi/Projects/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1267:23)
    at InstructionCoder._encode (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:85:24)
    at InstructionCoder.encode (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:68:17)
    at /Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/index.ts:51:56
    at ix (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:43:15)
    at txFn (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/transaction.ts:17:14)
    at Object.rpc [as initializeCandyMachine] (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:16:18)
    at createCandyMachineV2 (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/src/helpers/accounts.ts:153:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. RangeError: indeterminate span
    at Structure.getSpan (/Users/muhammadtaqi/Projects/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1221:13)
    at Structure.encode (/Users/muhammadtaqi/Projects/metaplex/js/node_modules/buffer-layout/lib/Layout.js:1267:23)
    at InstructionCoder._encode (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:85:24)
    at InstructionCoder.encode (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:68:17)
    at /Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/index.ts:51:56
    at ix (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/instruction.ts:43:15)
    at txFn (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/transaction.ts:17:14)
    at Object.rpc [as initializeCandyMachine] (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:16:18)
    at createCandyMachineV2 (/Users/muhammadtaqi/Projects/metaplex/js/packages/cli/src/helpers/accounts.ts:153:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

Apple M1, Mac OS 12.1

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by ArchTaqi** [comment]
Found out the issue, I was missing `"whitelistMintSettings": null,` in the config.json, was not sure `whitelistMintSettings` is mandatory to be defined.
