### ISSUE TITLE
Error Uploading Sample Collection From Metaplex

### ISSUE THREAD

**Issue by cctogs** [metaplex-foundation/metaplex#1858]
### Which package is this bug report for?

candy machine cli

### Issue description

See error logs below.

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
    ./assets-pictures
```

### Relevant log output

```shell
type: 'invalid-json'
}
Processing asset: 0
Error uploading file 0.png FetchError: invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile reason: Unexpected token E in JSON at position 0
    at /Users/charlestaylor/metaplex/js/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async upload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:24:10)
    at async arweaveUpload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:105:18)
    at async /Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:290:41
    at async Promise.all (index 0)
    at async uploadV2 (/Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:221:7)
    at async Command.<anonymous> (/Users/charlestaylor/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:227:7) {
  type: 'invalid-json'
}
Processing asset: 0
Error uploading file 0.png FetchError: invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile reason: Unexpected token E in JSON at position 0
    at /Users/charlestaylor/metaplex/js/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async upload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:24:10)
    at async arweaveUpload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:105:18)
    at async /Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:290:41
    at async Promise.all (index 0)
    at async uploadV2 (/Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:221:7)
    at async Command.<anonymous> (/Users/charlestaylor/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:227:7) {
  type: 'invalid-json'
}
Processing asset: 0
Error uploading file 0.png FetchError: invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile reason: Unexpected token E in JSON at position 0
    at /Users/charlestaylor/metaplex/js/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async upload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:24:10)
    at async arweaveUpload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:105:18)
    at async /Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:290:41
    at async Promise.all (index 0)
    at async uploadV2 (/Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:221:7)
    at async Command.<anonymous> (/Users/charlestaylor/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:227:7) {
  type: 'invalid-json'
}
Processing asset: 0
Error uploading file 0.png FetchError: invalid json response body at https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile reason: Unexpected token E in JSON at position 0
    at /Users/charlestaylor/metaplex/js/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async upload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:24:10)
    at async arweaveUpload (/Users/charlestaylor/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:105:18)
    at async /Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:290:41
    at async Promise.all (index 0)
    at async uploadV2 (/Users/charlestaylor/metaplex/js/packages/cli/src/commands/upload.ts:221:7)
    at async Command.<anonymous> (/Users/charlestaylor/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:227:7) {
```

### Operating system

Mac Ver: 10.14.6

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Looks like an issue with our cloud function to upload. Try using a different upload method in the meantime (such as nft.storage for devnet or arweave-sol for mainnet). We are aware of the issue and are working on a fix.

**Comment by stegaBOB** [comment]
We have fixed the issue. The `arweave` method should be working again now.

**Comment by cctogs** [comment]
Thanks,stegaBOB. It just uploaded. Best.
