### ISSUE TITLE
[Bug]: web: Failed to get source map: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Zachkes** [metaplex-foundation/metaplex#1868]
### Which package is this bug report for?

candy machine cli

### Issue description

1. yarn 
2. yarn bootstrap
3. yarn start

### Command

```shell
yarn start
```

### Relevant log output

```shell
yarn run v1.22.15
4:00:57 pm - Starting compilation in watch mode...
web: info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
@oyster/common: 4:01:09 pm - Found 0 errors. Watching for file changes.
web: event - compiled successfully
web: Attention: Next.js now collects completely anonymous telemetry regarding usage.
web: This information is used to shape Next.js' roadmap and prioritize features.
web: You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
web: https://nextjs.org/telemetry
web: event - build page: /
web: wait  - compiling...
web: event - compiled successfully
web: Failed to get source map: RangeError: Maximum call stack size exceeded
web:     at RegExp.exec (<anonymous>)
web:     at Object.getSourceMapUrl (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\internal\helpers\getSourceMapUrl.js:8:26) 
web:     at Object.getRawSourceMap (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\internal\helpers\getRawSourceMap.js:10:39)
web:     at C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:195:47
web:     at step (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:33:23)
web:     at Object.next (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:14:53)
web:     at fulfilled (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:5:58)
web: Failed to get source map: RangeError: Maximum call stack size exceeded
web:     at RegExp.exec (<anonymous>)
web:     at Object.getSourceMapUrl (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\internal\helpers\getSourceMapUrl.js:8:26)
web:     at Object.getRawSourceMap (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\internal\helpers\getRawSourceMap.js:10:39)
web:     at C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:195:47
web:     at step (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:33:23)
web:     at Object.next (C:\Users\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:14:53)
web:     at fulfilled (C:\Users\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:5:58)
web: Failed to get source map: RangeError: Maximum call stack size exceeded
web:     at RegExp.exec (<anonymous>)
web:     at Object.getSourceMapUrl (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\internal\helpers\getSourceMapUrl.js:8:26)
web:     at Object.getRawSourceMap (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\internal\helpers\getRawSourceMap.js:10:39)
web:     at C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:195:47
web:     at step (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:33:23)
web:     at Object.next (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:14:53)
web:     at fulfilled (C:\Users\Desktop\Candy Machine\metaplex\js\node_modules\@next\react-dev-overlay\lib\middleware.js:5:58)
```

### Operating system

Windows

### Priority this issue should have

Low (slightly annoying)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by DrewWeth** [comment]
I'm also running into this

**Comment by stegaBOB** [comment]
I couldn't reproduce this issue. Can you try pulling from master again and removing all of the node modules with `lerna clean` and then restarting? Thanks.

**Comment by flatplate** [comment]
This happened to me with a fresh install. I initialized the project and started the server as per documentation. After connecting my wallet (solflare, firefox), it was stuck on loading (like https://github.com/metaplex-foundation/metaplex/issues/1339), and I saw this error message on the console.

**Comment by OmPals** [comment]
Facing same issue while following the docs.
