### ISSUE TITLE
[Bug]: Error Uploading NFT using CMv2

### ISSUE THREAD

**Issue by sarangjain40** [metaplex-foundation/metaplex#1878]
### Which package is this bug report for?

candy machine cli

### Issue description

I have 1 SOL in my wallet.  While I am trying to upload 2 images, 
My config file is : 

{ "price": 1.0, "number": 2, "gatekeeper": null, "solTreasuryAccount": "A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4", "splTokenAccount": null, "splToken": null, "goLiveDate": "25 Dec 2021 00:00:00 GMT", "endSettings": null, "whitelistMintSettings": null, "hiddenSettings": null, "storage": "arweave", "ipfsInfuraProjectId": null, "ipfsInfuraSecret": null, "awsS3Bucket": null, "noRetainAuthority": false, "noMutable": false }

Please help

### Relevant log output

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet -k ~/.config/solana/mywallet.json -cp config.json -c assets assets/
wallet public key: A1eu7Dbv6mZRGM4Z5sPrEnLmWxv1W47vTjRTWZxoXHE4
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type assets/0.json_bkp
WARNING: Skipping unsupported file type assets/backup
Beginning the upload for 2 (img+json) pairs
started at: 1646221923268
initializing candy machine
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    Program 11111111111111111111111111111111 invoke [1]
    Transfer: insufficient lamports 4545142, need 9291600
    Program 11111111111111111111111111111111 failed: custom program error: 0x1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/sarang.jain/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/home/sarang.jain/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async createCandyMachineV2 (/home/sarang.jain/metaplex/js/packages/cli/src/helpers/accounts.ts:150:11)
    at async uploadV2 (/home/sarang.jain/metaplex/js/packages/cli/src/commands/upload.ts:130:19)
    at async Command.<anonymous> (/home/sarang.jain/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:184:7) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 4545142, need 9291600',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
}
Error deploying config to Solana network. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/sarang.jain/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/home/sarang.jain/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async createCandyMachineV2 (/home/sarang.jain/metaplex/js/packages/cli/src/helpers/accounts.ts:150:11)
    at async uploadV2 (/home/sarang.jain/metaplex/js/packages/cli/src/commands/upload.ts:130:19)
    at async Command.<anonymous> (/home/sarang.jain/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:184:7) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 4545142, need 9291600',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
}
upload was not successful, please re-run. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/home/sarang.jain/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/sarang.jain/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/home/sarang.jain/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async createCandyMachineV2 (/home/sarang.jain/metaplex/js/packages/cli/src/helpers/accounts.ts:150:11)
    at async uploadV2 (/home/sarang.jain/metaplex/js/packages/cli/src/commands/upload.ts:130:19)
    at async Command.<anonymous> (/home/sarang.jain/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:184:7) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 4545142, need 9291600',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
```

### Operating system

linux

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by sarangjain40** [comment]
Its solved. I airdropped 2 SOL and it started working.
