### ISSUE TITLE
[Bug]: Incorrect size/amount for bundlr fund txn. 

### ISSUE THREAD

**Issue by felixxcheng** [metaplex-foundation/metaplex#1885]
### Which package is this bug report for?

candy machine cli

### Issue description

Hey guys, tried to make some NFTs on mainnet-beta with the arweave-sol storage option.  It is relaying to me that 0.00000157 SOL is necessary upload and yet my 0.5 SOL wallet has insuffient funds?

Please help!  Also, the docs just gleans over the storage options.  Are there docs out there that go into the further detail about these storage options as maybe, just maybe, arweave-sol is an unavailble option?  

Thank you kindly!

### Command

```shell
ts-node C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload 
-e mainnet-beta 
-k C:\Users\netfe\.config\solana\power2.json 
-cp C:\Users\netfe\Desktop\metaplex\js\packages\cli\config.json 
C:\Users\netfe\Desktop\metaplex\asseting
```

### Relevant log output

```shell
wallet public key: 5TQsnMGXUqukFBMsJyy93TsHbN4ncWfSHdD4VoCvD5XB
WARNING: Skipping unsupported file type C:\Users\netfe\Desktop\metaplex\asseting\.cache
Beginning the upload for 2 (img+json) pairs
started at: 1646258912343
initializing candy machine
initialized config for a candy machine with publickey: Gh1sx6jX2GehTLdB3NxtKSSCL15aYrTdk1Z3jDLip47r
Uploading Size 2 { mediaExt: '.png', index: '0' }
Saved bundle upload result to cache.
Computed Bundle range, including 2 file pair(s) totaling 0.009MB.
Uploading bundle via bundlr... in multiple transactions
0.00000157 SOL to upload
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data
    at NodeUploader.dataItemUploader (C:\Users\netfe\Desktop\metaplex\js\packages\cli\node_modules\@bundlr-network\client\build\common\upload.js:43:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async uploadTransaction (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:589:13)
    at async processBundle (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:604:11)
    at async uploadV2 (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\commands\upload.ts:202:11)
    at async Command.<anonymous> (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:215:7)
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 2) Error: Not enough funds to send data
    at NodeUploader.dataItemUploader (C:\Users\netfe\Desktop\metaplex\js\packages\cli\node_modules\@bundlr-network\client\build\common\upload.js:43:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async uploadTransaction (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:589:13)
    at async C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:600:15
    at async uploadTransaction (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:589:13)
    at async processBundle (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:604:11)
    at async uploadV2 (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\commands\upload.ts:202:11)
    at async Command.<anonymous> (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:215:7)
upload was not successful, please re-run. Error: Not enough funds to send data
    at NodeUploader.dataItemUploader (C:\Users\netfe\Desktop\metaplex\js\packages\cli\node_modules\@bundlr-network\client\build\common\upload.js:43:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async uploadTransaction (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:589:13)
    at async C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:600:15
    at async uploadTransaction (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:589:13)
    at async C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:600:15
    at async uploadTransaction (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:589:13)
    at async processBundle (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:604:11)
    at async uploadV2 (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\commands\upload.ts:202:11)
    at async Command.<anonymous> (C:\Users\netfe\Desktop\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:215:7)
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by sarangjain40** [comment]
Try airdrop 1 or 2 sol in Devnet for the same Address and try again. It worked for me.

solana airdrop 1 --url https://api.devnet.solana.com

**Comment by felixxcheng** [comment]
the problem though is that I am trying to deploy on mainnet-beta.  A devnet airdrop wouldn't be the proper solution.  If its stated that 0.00000157 SOL are the required funds, there some be reasonable expectation that is right around the case as 0.5 is many multi of times more than that value.

**Comment by sarangjain40** [comment]
Even I was trying to upload on mainnet and I was getting insufficient Lamports. Then just as a trial I did that and it worked. So try doing that.

**Comment by felixxcheng** [comment]
> Even I was trying to upload on mainnet and I was getting insufficient Lamports. Then just as a trial I did that and it worked. So try doing that.

I appreciate the help and I tried it your way, devnet airdroppping 2 SOL instead of just 1 SOL to be doubly sure.  
Still the same issue:
"Uploading bundle via bundlr... in multiple transactions
0.000001658 SOL to upload
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data"

I even tried minting a piece of be sure maybe the error thrown should be ignored.  Just paid the price for no new NFT added to my Phantom's collection.  Its ok, as this is a valuable learning lesson without a heavy penalty.

Got any other ideas to throw at this?

**Comment by sarangjain40** [comment]
For me everything is success but still no NFT added on my Phanton APP

**Comment by stegaBOB** [comment]
Please update to the latest repo. We have improved the CLI and bundlr should work more reliably.

**Comment by stegaBOB** [comment]
If you are still having issues after that let us know.

**Comment by 1trackprojects1** [comment]
I'm having the same issue with mainnet

**Comment by 1trackprojects1** [comment]
I had 1 sol in my wallet and started uploading,

`Beginning the upload for 10 (img+json) pairs
started at: 1646551755444
initializing candy machine
initialized config for a candy machine with publickey: REDACTED
Uploading Size 10 { mediaExt: '.png', index: '0' }
Saved bundle upload result to cache.
Computed Bundle range, including 10 file pair(s) totaling 0.217MB.
Uploading bundle via bundlr... in multiple transactions
0.000043163 SOL to upload
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data`

it said this but still took some sol from my wallet, as my balance now is 0.977273117 SOL

**Comment by stegaBOB** [comment]
We are aware of the issue and are investigating this.

**Comment by stegaBOB** [comment]
I think we found the issue! yay. Should have an update out later today.

**Comment by cryptoboole** [comment]
@stegaBOB is there an update on this?

**Comment by phillmorgan28** [comment]
Hi, we're getting this very same issue today

`Uploading bundle via Bundlr... in multiple transactions
0.005354806 SOL to upload 16.909MB with buffer. Sending fund txn...
Successfully funded Arweave Bundler, starting upload
Progress: [██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░] 34% | 3463/9999
Could not complete Bundlr tx upload successfully, exiting due to:  Error: Not enough funds to send data`

It appears to send a chunk and then randomly stop and throw the Not enough funds error.

**Comment by studentofcoding** [comment]
Similar problem are arising on `arweave-sol` 
Env : devnet
OS : Mac-M1

```
Computed Bundle range, including 20 file pair(s) totaling 78.242MB.
Processing file groups...
Progress: [████████████████████████████████████████] 100% | 20/20
Uploading bundle via Bundlr... in multiple transactions
0.020689178 SOL to upload 78.247MB with buffer. Sending fund txn...
Successfully funded Arweave Bundler, starting upload
Progress: [███████████████████████████████████░░░░░] 88% | 53/60
Could not complete Bundlr tx upload successfully, exiting due to:  Error: timeout of 60000ms exceeded
```

Here are the complete log of it
```
Could not complete Bundlr tx upload successfully, exiting due to:  Error: timeout of 60000ms exceeded
    at createError (/Users/gic_owner/metaplex_new/js/node_modules/@bundlr-network/client/node_modules/axios/lib/core/createError.js:)
    at RedirectableRequest.handleRequestTimeout (/Users/gic_owner/metaplex_new/js/node_modules/@bundlr-network/client/node_modules/a)
    at RedirectableRequest.emit (node:events:390:28)
    at Timeout.<anonymous> (/Users/gic_owner/metaplex_new/js/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 60000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: 536870912,
    maxBodyLength: Infinity,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/octet-stream',
      'User-Agent': 'axios/0.25.0',
      'Content-Length': 3837104
    },
    baseURL: 'https://devnet.bundlr.network:443',
    method: 'post',
    url: 'https://devnet.bundlr.network:443/tx/solana',
    data: <Buffer 02 00 6e e4 c8 dc 90 6a 7e c6 c0 88 fe b7 4d 91 dd 59 f1 9b 45 1c 50 59 f7 0d 66 a1 14 08 c6 c8 bb 3a 5a 07 67 f6 >
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/tx/solana',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'devnet.bundlr.network',
      port: '443',
      nativeProtocols: [Object],
      pathname: '/tx/solana'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 3837104,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /tx/solana HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/octet-stream\r\n' +
        'User-Agent: axios/0.25.0\r\n' +
        'Content-Length: 3837104\r\n' +
        'Host: devnet.bundlr.network\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/tx/solana',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'devnet.bundlr.network',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'https://devnet.bundlr.network:443/tx/solana',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
upload was not successful, please re-run. Error: timeout of 60000ms exceeded
    at createError (/Users/gic_owner/metaplex_new/js/node_modules/@bundlr-network/client/node_modules/axios/lib/core/createError.js:)
    at RedirectableRequest.handleRequestTimeout (/Users/gic_owner/metaplex_new/js/node_modules/@bundlr-network/client/node_modules/a)
    at RedirectableRequest.emit (node:events:390:28)
    at Timeout.<anonymous> (/Users/gic_owner/metaplex_new/js/node_modules/follow-redirects/index.js:164:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 60000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: 536870912,
    maxBodyLength: Infinity,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/octet-stream',
      'User-Agent': 'axios/0.25.0',
      'Content-Length': 3837104
    },
    baseURL: 'https://devnet.bundlr.network:443',
    method: 'post',
    url: 'https://devnet.bundlr.network:443/tx/solana',
    data: <Buffer 02 00 6e e4 c8 dc 90 6a 7e c6 c0 88 fe b7 4d 91 dd 59 f1 9b 45 1c 50 59 f7 0d 66 a1 14 08 c6 c8 bb 3a 5a 07 67 f6 >
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Array]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/tx/solana',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'devnet.bundlr.network',
      port: '443',
      nativeProtocols: [Object],
      pathname: '/tx/solana'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 3837104,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /tx/solana HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/octet-stream\r\n' +
        'User-Agent: axios/0.25.0\r\n' +
        'Content-Length: 3837104\r\n' +
        'Host: devnet.bundlr.network\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/tx/solana',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'devnet.bundlr.network',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'https://devnet.bundlr.network:443/tx/solana',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```
Please kindly help @stegaBOB, thanks

**Comment by stegaBOB** [comment]
> Hi, we're getting this very same issue today
> 
> `Uploading bundle via Bundlr... in multiple transactions`
> `0.005354806 SOL to upload 16.909MB with buffer. Sending fund txn...`
> `Successfully funded Arweave Bundler, starting upload`
> `Progress: [██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░] 34% | 3463/9999`
> `Could not complete Bundlr tx upload successfully, exiting due to:  Error: Not enough funds to send data`
> 
> It appears to send a chunk and then randomly stop and throw the Not enough funds error.

Looks like you're using an older version? Are you sure you're on the latest metaplex? @phillmorgan28

**Comment by phillmorgan28** [comment]
@stegaBOB Just to be certain I deleted and cloned again, installed and attempt the upload again. Same error:

```
Computed Bundle range, including 3333 file pair(s) totaling 14.871MB.
Processing file groups...
Progress: [████████████████████████████████████████] 100% | 3333/3333
Uploading bundle via Bundlr... in multiple transactions
0.005298298 SOL to upload 16.909MB with buffer. Sending fund txn...
Successfully funded Arweave Bundler, starting upload
Progress: [██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░] 34% | 3459/9999
Could not complete Bundlr tx upload successfully, exiting due to:  Error: Not enough funds to send data
    at NodeUploader.dataItemUploader (/home/phill/metaplex/js/node_modules/@bundlr-network/client/build/common/upload.js:43:23)
```

IPFS was unsuccessful due to Infura rate limiting, it fails to upload any more after around 20 NFTs.

**Comment by stegaBOB** [comment]
That's super odd. What you can do is use the bundlr CLI to "overfund" the bundlr node. Or modify the multiplier in the arweave-bundlr.ts fine in the js/packages/cli/helpers/upload/ directory. We'll look into this a bit deeper

**Comment by phillmorgan28** [comment]
@stegaBOB is this the correct line to adjust?
`await bundlr.fund(cost.multipliedBy(2));`

**Comment by stegaBOB** [comment]
The withdraw in that is kinda unreliable. Try using the withdraw_bundlr command.

**Comment by GottliebGlob** [comment]
> I'll give it a go once I've finished deploying. Thank you for you assistance. It appears as though a high multiplier is needed for one reason or another. I think 5x would have done it. I'm not sure why there is such a large price difference though, perhaps something has changed at bundlrs end?

Thanks fir your help. Did you use `arweave-bundle`?

**Comment by ddcc3388** [comment]
Hey guys, have any of you tried using rpc?

**Comment by DeeKay02** [comment]
> > I'll give it a go once I've finished deploying. Thank you for you assistance. It appears as though a high multiplier is needed for one reason or another. I think 5x would have done it. I'm not sure why there is such a large price difference though, perhaps something has changed at bundlrs end?
> 
> No, didn't work for me( ![image](https://user-images.githubusercontent.com/53971863/158554812-79bf38c9-b899-4d67-984b-b92a62bf0c06.png)

Were you able to solve the issue?
