### ISSUE TITLE
[Bug]: Cany machine 2 minting error pls help

### ISSUE THREAD

**Issue by Balesz03** [metaplex-foundation/metaplex#1892]
### Which package is this bug report for?

candy machine cli

### Issue description

(base) Balesz-MacBook-Pro:metaplex balint$ ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \
>     -e devnet \
>     -k ~/config/solana/devnettest.json \
>     -cp config.json \
>     -c example \
>     assets
wallet public key: 6rra3RqfMTW3hSYxmDp82cbZ64KEsZUx2N3X26eAWDn3
(node:27690) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 6 (img+json) pairs
started at: 1646394238808
initializing candy machine
Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 5v4dSCHCsyCxmAMuo4EEQNp8Vw8DnD2kVyBDZtRB8cKKs3zba8v3SKG33HfjorW3DvMEuTEkRzoFb2RerVK8Y7rF using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (/Users/balint/Documents/Cryptoalien/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2781:13)
    at async sendAndConfirmRawTransaction (/Users/balint/Documents/Cryptoalien/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async createCandyMachineV2 (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/helpers/accounts.ts:153:11)
    at async uploadV2 (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/commands/upload.ts:141:19)
    at async Command.<anonymous> (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:263:7)
Error deploying config to Solana network. Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 5v4dSCHCsyCxmAMuo4EEQNp8Vw8DnD2kVyBDZtRB8cKKs3zba8v3SKG33HfjorW3DvMEuTEkRzoFb2RerVK8Y7rF using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (/Users/balint/Documents/Cryptoalien/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2781:13)
    at async sendAndConfirmRawTransaction (/Users/balint/Documents/Cryptoalien/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async createCandyMachineV2 (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/helpers/accounts.ts:153:11)
    at async uploadV2 (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/commands/upload.ts:141:19)
    at async Command.<anonymous> (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:263:7)
upload was not successful, please re-run. Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 5v4dSCHCsyCxmAMuo4EEQNp8Vw8DnD2kVyBDZtRB8cKKs3zba8v3SKG33HfjorW3DvMEuTEkRzoFb2RerVK8Y7rF using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (/Users/balint/Documents/Cryptoalien/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2781:13)
    at async sendAndConfirmRawTransaction (/Users/balint/Documents/Cryptoalien/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async createCandyMachineV2 (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/helpers/accounts.ts:153:11)
    at async uploadV2 (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/commands/upload.ts:141:19)
    at async Command.<anonymous> (/Users/balint/Documents/Cryptoalien/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:263:7)
(base) Balesz-MacBook-Pro:metaplex balint$ 

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload \
>     -e devnet \
>     -k ~/config/solana/devnettest.json \
>     -cp config.json \
>     -c example \
>     assets
```

### Operating system

Mac os Catalina

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by MaximeLassalleHub** [comment]
Same [here](https://github.com/metaplex-foundation/metaplex/issues/1893)

**Comment by stegaBOB** [comment]
Devnet is just having some issues now unfortunately. Not much we can do on our end.
