### ISSUE TITLE
[Bug]: Problem Upload Candy Machine devnet

### ISSUE THREAD

**Issue by UnKnOwN7GoDz** [metaplex-foundation/metaplex#1908]
### Which package is this bug report for?

candy machine cli

### Issue description

i have problem when i upload candy machine on devnet..

### Command

```shell
ts-node E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -k E:\Project\DEVforYOU\Solana\DEV\Setjwh4yMb4kjax7n47twKadjuWMMYz44WSF1unoyaQ.json -cp E:\Project\DEVforYOU\Solana\DEV\config.json E:\Project\DEVforYOU\Solana\DEV\Assets
```

### Relevant log output

```shell
>ts-node E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -k E:\Project\DEVforYOU\Solana\DEV\Setjwh4yMb4kjax7n47twKadjuWMMYz44WSF1unoyaQ.json -cp E:\Project\DEVforYOU\Solana\DEV\config.json E:\Project\DEVforYOU\Solana\DEV\Assets
wallet public key: Setjwh4yMb4kjax7n47twKadjuWMMYz44WSF1unoyaQ
(node:5800) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 33 (img+json) pairs
started at: 1646563372322
initializing candy machine
Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 2n9iunZWuk3jrN25NVuLFeeowHzg2BSh41TYCJf6c8NyotxwFaPjccBg1Gzz6n7bpNZoBD5kG2dAPa73c5fame8F using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2781:13)
    at async sendAndConfirmRawTransaction (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\helpers\accounts.ts:153:11)
    at async uploadV2 (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\commands\upload.ts:141:19)
    at async Command.<anonymous> (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:263:7)
Error deploying config to Solana network. Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 2n9iunZWuk3jrN25NVuLFeeowHzg2BSh41TYCJf6c8NyotxwFaPjccBg1Gzz6n7bpNZoBD5kG2dAPa73c5fame8F using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2781:13)
    at async sendAndConfirmRawTransaction (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\helpers\accounts.ts:153:11)
    at async uploadV2 (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\commands\upload.ts:141:19)
    at async Command.<anonymous> (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:263:7)
upload was not successful, please re-run. Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 2n9iunZWuk3jrN25NVuLFeeowHzg2BSh41TYCJf6c8NyotxwFaPjccBg1Gzz6n7bpNZoBD5kG2dAPa73c5fame8F using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2781:13)
    at async sendAndConfirmRawTransaction (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\helpers\accounts.ts:153:11)
    at async uploadV2 (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\commands\upload.ts:141:19)
    at async Command.<anonymous> (E:\Project\DEVforYOU\Solana\DEV\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:263:7)
```

### Operating system

win 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by rakshpma** [comment]
devnet is dead right now. I have been facing the same issue.

**Comment by merlox** [comment]
same, devnet is broken. I've tried with testnet and it did deploy but sometimes it fails, it's very annoying and can be costly if you're doing it in mainnet. I bet there's a setting somewhere to change the confirmation time to something larger

**Comment by stegaBOB** [comment]
Devnet is just broken right now basically. Nothing we can do on our end. The transactions are likely just being dropped by validators.
