### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by danielmarian110** [metaplex-foundation/metaplex#1921]
### Which package is this bug report for?

candy machine cli

### Issue description

Hey i have a problem , the code recive me a error :
Error: Creator address is missing

### Command

```shell
ts-node C:/Users/pasca/solana-nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload --env devnet --keypair C:/Users/pasca/solana-nft/wallet.json -cp C:/Users/pasca/solana-nft/config.json -c example ./assets
```

### Relevant log output

```shell
Error: Creator address is missing
    at uploadV2 (C:\Users\pasca\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:126:15)
    at Command.<anonymous> (C:\Users\pasca\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:216:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. Error: Creator address is missing
    at uploadV2 (C:\Users\pasca\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:126:15)
    at Command.<anonymous> (C:\Users\pasca\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:216:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by merlox** [comment]
you are missing some parameter in the config.json

**Comment by stegaBOB** [comment]
Its actually probably a field in your 0.json for creators. As of now the candy machine pulls from that to get the creator addresses (which will be changed).
