### ISSUE TITLE
ENOENT: no such file or directory, open '\0.json'

### ISSUE THREAD

**Issue by larbito** [metaplex-foundation/metaplex#1924]
![files exist](https://user-images.githubusercontent.com/28695593/157251687-f039fded-1cff-4146-b943-653aa2e69aea.png)
### Which package is this bug report for?

candy machine cli

### Issue description

upload was not successful, please re-run. Error: ENOENT: no such file or directory, open '\0.json'

### Command

```shell
ts-node C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload \ -e devnet \ -k C:\Users\Larbi\.config\solana\devnet10.json \ -cp C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\config.json \ -c example \ C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\assets
```

### Relevant log output

```shell
(node:18840) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

WARNING: Skipping unsupported file type \$Recycle.Bin
WARNING: Skipping unsupported file type \$WinREAgent
WARNING: Skipping unsupported file type \AITEMP
WARNING: Skipping unsupported file type \Documents and Settings
WARNING: Skipping unsupported file type \Drivers
WARNING: Skipping unsupported file type \DumpStack.log.tmp
WARNING: Skipping unsupported file type \hiberfil.sys
WARNING: Skipping unsupported file type \Intel
WARNING: Skipping unsupported file type \pagefile.sys
WARNING: Skipping unsupported file type \PerfLogs
WARNING: Skipping unsupported file type \Program Files
WARNING: Skipping unsupported file type \Program Files (x86)
WARNING: Skipping unsupported file type \ProgramData
WARNING: Skipping unsupported file type \Python310
WARNING: Skipping unsupported file type \Recovery
WARNING: Skipping unsupported file type \solana-install-tmp
WARNING: Skipping unsupported file type \swapfile.sys
WARNING: Skipping unsupported file type \System Volume Information
WARNING: Skipping unsupported file type \Users
WARNING: Skipping unsupported file type \Windows
Beginning the upload for 3 (img+json) pairs
started at: 1646747332115
upload was not successful, please re-run. Error: ENOENT: no such file or directory, open '\0.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getAssetManifest (C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\commands\upload.ts:461:8)
    at uploadV2 (C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\commands\upload.ts:116:32)
    at Command.<anonymous> (C:\Users\Larbi\Desktop\solanaproject\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:263:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '\\0.json'
}
```

### Operating system

Windows 11

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Try removing all of the `\` between your commands. it may be confusing windows.
