### ISSUE TITLE
[Bug]: ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time Error: Non-base58 character

### ISSUE THREAD

**Issue by emirhanber** [metaplex-foundation/metaplex#1930]
### Which package is this bug report for?

candy machine cli

### Issue description

Hello Devs.  İ want create  candy machine v2 for test . But  something going wrong... I get the following error when I try to upload.
I searched for this error >>>(Error: Non-base58 character) they are telling me to regenerate the fader address. I did not do it many times.. Thanks

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload     
-e devnet     
-k ~/.config/solana/devnet-wallet.json     
-cp ~/dev/config.json     -c example  ~/dev/assets
```

### Relevant log output

```shell
$ ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload     -e devnet     -k ~/.config/solana/devnet-wallet.json     -cp ~/dev/config.json     -c example  ~/dev/assets         
wallet public key: PKvSGxK6ZQsu6E4gGucrta3ZfQVsEpZmC6LhgDKwyUJ
(node:21744) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\nft\metaplex\js\node_modules\base-x\src\index.js:111
    throw new Error('Non-base' + BASE + ' character')
          ^
Error: Non-base58 character
    at Object.decode (C:\Users\nft\metaplex\js\node_modules\base-x\src\index.js:111:11)
    at new PublicKey (C:\Users\nft\metaplex\js\node_modules\@solana\web3.js\src\publickey.ts:56:30)
    at getCandyMachineV2Config (C:\Users\nft\metaplex\js\packages\cli\src\helpers\various.ts:156:9)
    at Command.<anonymous> (C:\Users\nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:157:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

Windows 10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by gw19191** [comment]
hey @emirhanber how did you fix this issue?
