### ISSUE TITLE
[Bug]: Type 'Uint8Array' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators

### ISSUE THREAD

**Issue by arrbrk1** [metaplex-foundation/metaplex#1942]
### Which package is this bug report for?

candy machine cli

### Issue description

I'm having these error messages when running a command with ts-node:

```metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:499:16 - error TS2569: Type 'Uint8Array' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

499             ...thisSlice.slice(4, 36).filter(n => n !== 0),
                   
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:502:16 - error TS2569: Type 'Uint8Array' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

502             ...thisSlice.slice(40, 240).filter(n => n !== 0),```
```
I've already tried updating tsconfig.json target to **es5** and **es2015** as suggested on some forums and also adding the downlevelIteration: true line, but the error keep the same.

### Command

```shell
npx ts-node C:/Users/ariel.DESKTOP-6GEBQCM/Documents/www/offbeat/solana-nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts verify_upload -e devnet -k keypair.json
```

### Relevant log output

```shell
return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:499:16 - error TS2569: Type 'Uint8Array' is not an array type or a string type. Use 
compiler option '--downlevelIteration' to allow iterating of iterators.

499             ...thisSlice.slice(4, 36).filter(n => n !== 0),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:502:16 - error TS2569: Type 'Uint8Array' is not an array type or a string type. Use 
compiler option '--downlevelIteration' to allow iterating of iterators.

502             ...thisSlice.slice(40, 240).filter(n => n !== 0),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (C:\Users\ariel.DESKTOP-6GEBQCM\node_modules\ts-node\src\index.ts:423:12)
    at reportTSError (C:\Users\ariel.DESKTOP-6GEBQCM\node_modules\ts-node\src\index.ts:427:19)
    at getOutput (C:\Users\ariel.DESKTOP-6GEBQCM\node_modules\ts-node\src\index.ts:554:36)
    at Object.compile (C:\Users\ariel.DESKTOP-6GEBQCM\node_modules\ts-node\src\index.ts:760:32)
    at Module.m._compile (C:\Users\ariel.DESKTOP-6GEBQCM\node_modules\ts-node\src\index.ts:839:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\ariel.DESKTOP-6GEBQCM\node_modules\ts-node\src\index.ts:842:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

### Operating system

Windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Please try pulling from master and trying again. I can't reproduce this issue. Let us know if it still isn't working.

**Comment by arrbrk1** [comment]
Pulled from master and got the same error running the same command

![image](https://user-images.githubusercontent.com/25717193/161167329-1103cabf-081d-477d-97f5-9172e23b4008.png)
