### ISSUE TITLE
[Bug]: Error 0xbc4

### ISSUE THREAD

**Issue by psavva** [metaplex-foundation/metaplex#1956]
### Which package is this bug report for?

candy machine cli

### Issue description

I'm able to simulate an error 0xbc4 - decimal: 3012

Steps:
1) upload nfts using candymachinev2 upload command
2) verify OK
3) withdraw
4) upload nfts again, error is thrown.

The error  3012 according to:
[Project-Serum](https://github.com/project-serum/anchor/blob/041414f52a5fd65dd71c8f93e62371d32996aa1c/lang/src/error.rs#L146-L148)
is that `"The program expected this account to be already initialized"`.

If withdrawal is destroying the account somehow, perhaps that must be re-thought...
If the upload perhaps should check if the account is initialized, and if not, re-initialize it?

### Relevant log output

```shell
PS C:\repos\NFT\OiKattes> ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k solana-mint/devnet-keypair.json -cp solana-mint/config.json -c testcache solana-mint/assets 
wallet public key: EoQFqam61FNeNLymwPEMm9SSrJK2S8GvBFpUuihZdeuf
(node:25756) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time 
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25756) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
WARNING: The "arweave" storage option will be going away soon. Please migrate to arweave-bundle or arweave-sol for mainnet.

Beginning the upload for 5 (img+json) pairs
started at: 1647290231877
config for a candy machine with publickey: Hea6EGFW22DBpKjzk66p9NYZ2urc52ubFsNVJJk25SRQ has been already initialized
[5] out of [5] items have been uploaded
Writing all indices in 1 transactions...
Progress: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 0/1Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4 
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Instruction: AddConfigLines
    Program log: Custom program error: 0xbc4
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 8569 of 200000 compute units
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0xbc4
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4
    at Connection.sendEncodedTransaction (C:\repos\NFT\OiKattes\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3964:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\repos\NFT\OiKattes\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3921:20)
    at async sendAndConfirmRawTransaction (C:\repos\NFT\OiKattes\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\repos\NFT\OiKattes\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (C:\repos\NFT\OiKattes\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async addConfigLines (C:\repos\NFT\OiKattes\metaplex\js\packages\cli\src\commands\upload.ts:549:22)
    at async PromisePoolExecutor.handler (C:\repos\NFT\OiKattes\metaplex\js\packages\cli\src\commands\upload.ts:587:7)
    at async Promise.all (index 0)
    at async PromisePoolExecutor.drainActiveTasks (C:\repos\NFT\OiKattes\metaplex\js\node_modules\@supercharge\promise-pool\dist\promise-pool-executor.js:335:9) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    'Program log: Custom program error: 0xbc4',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 8569 of 200000 compute units',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: custom program error: 0xbc4'
Done. Successful = false.
ended at: 2022-03-14T20:37:17.110Z. time taken: 00:00:05
PS C:\repos\NFT\OiKattes> 
Failed writing indices 0-4: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xbc4
```

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Withdraw deletes the account. it doesnt delete your cache file. Youll need to delete the cache file since it references an account that no longer exists.

**Comment by psavva** [comment]
Thank you for that
