### ISSUE TITLE
[Bug]: Problem when i init the storefront "Number can only safely store up to 53 bits"

### ISSUE THREAD

**Issue by TerraLegends** [metaplex-foundation/metaplex#1987]
### Which package is this bug report for?

storefront

### Issue description

When i init the storefront in local, i have this error : 

**Unhandled Runtime Error**
**Error: Number can only safely store up to 53 bits**

**_Source_**
assert
../../node_modules/bn.js/lib/bn.js (6:0)
u64.toNumber
../../node_modules/bn.js/lib/bn.js (547:0)
../common/dist/lib/contexts/meta/loadAccounts.js (137:0) @ pullYourMetadata

  135 | const mintList = [];
  136 | for (let i = 0; i < userTokenAccounts.length; i++) {
**> 137 |     if (userTokenAccounts[i].info.amount.toNumber() == 1) {**
  138 |         mintList.push(userTokenAccounts[i].info.mint.toBase58());
  139 |     }
  140 | }
  
  **_Call Stack_**
pullUserMetadata
../common/dist/lib/contexts/meta/meta.js (157:0)
eval
../common/dist/lib/contexts/meta/meta.js (287:0)
invokePassiveEffectCreate
../../node_modules/react-dom/cjs/react-dom.development.js (23487:0)
HTMLUnknownElement.callCallback
../../node_modules/react-dom/cjs/react-dom.development.js (3945:0)
HTMLUnknownElement.sentryWrapped
https://browser.sentry-cdn.com/5.4.0/bundle.min.js (2:38177)
Object.invokeGuardedCallbackDev
../../node_modules/react-dom/cjs/react-dom.development.js (3994:0)
invokeGuardedCallback
../../node_modules/react-dom/cjs/react-dom.development.js (4056:0)
flushPassiveEffectsImpl
../../node_modules/react-dom/cjs/react-dom.development.js (23574:0)
unstable_runWithPriority
../../node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
../../node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushPassiveEffects
../../node_modules/react-dom/cjs/react-dom.development.js (23447:0)
performSyncWorkOnRoot
../../node_modules/react-dom/cjs/react-dom.development.js (22269:0)
eval
../../node_modules/react-dom/cjs/react-dom.development.js (11327:0)
unstable_runWithPriority
../../node_modules/scheduler/cjs/scheduler.development.js (468:0)
runWithPriority$1
../../node_modules/react-dom/cjs/react-dom.development.js (11276:0)
flushSyncCallbackQueueImpl
../../node_modules/react-dom/cjs/react-dom.development.js (11322:0)
flushSyncCallbackQueue
../../node_modules/react-dom/cjs/react-dom.development.js (11309:0)
scheduleUpdateOnFiber
../../node_modules/react-dom/cjs/react-dom.development.js (21893:0)
dispatchAction
../../node_modules/react-dom/cjs/react-dom.development.js (16139:0)
eval
src/hooks/useAuctions.ts (112:8)
  

### Relevant log output

```shell
breadcrumbs.ts:111 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at SalesListView (webpack-internal:///./src/views/home/components/SalesList/index.tsx:57:54)
(anonyme) @ breadcrumbs.ts:111
breadcrumbs.ts:111 CUSTOM STORE: Da7D2RTH4nMfgYFmUuTkZV9bkRANzeBsu5wXRPnjee5e
bn.js?9d76:6 Uncaught (in promise) Error: Number can only safely store up to 53 bits
    at assert (bn.js?9d76:6:1)
    at u64.toNumber (bn.js?9d76:547:1)
    at pullYourMetadata (loadAccounts.js?7f85:137:1)
    at pullUserMetadata (meta.js?071f:157:1)
    at eval (meta.js?071f:287:1)
    at invokePassiveEffectCreate (react-dom.development.js?a814:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?a814:3945:1)
    at HTMLUnknownElement.sentryWrapped (helpers.ts:85:17)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?a814:3994:1)
    at invokeGuardedCallback (react-dom.development.js?a814:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js?a814:23574:1)
    at unstable_runWithPriority (scheduler.development.js?e22e:468:1)
    at runWithPriority$1 (react-dom.development.js?a814:11276:1)
    at flushPassiveEffects (react-dom.development.js?a814:23447:1)
    at performSyncWorkOnRoot (react-dom.development.js?a814:22269:1)
    at eval (react-dom.development.js?a814:11327:1)
    at unstable_runWithPriority (scheduler.development.js?e22e:468:1)
    at runWithPriority$1 (react-dom.development.js?a814:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js?a814:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js?a814:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js?a814:21893:1)
    at dispatchAction (react-dom.development.js?a814:16139:1)
    at eval (useAuctions.ts?f865:112:9)
:3000/_next/webpack-hmr?page=%2F:1          Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
Échec du chargement de la carte source par les Outils de développement : Impossible de charger le contenu de chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map : Erreur système: net::ERR_BLOCKED_BY_CLIENT
Échec du chargement de la carte source par les Outils de développement : Impossible de charger le contenu de https://platform.twitter.com/widgets/requestProvider.js.map : Erreur HTTP : code d'état 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Échec du chargement de la carte source par les Outils de développement : Impossible de charger le contenu de chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map : Erreur système: net::ERR_BLOCKED_BY_CLIENT
Échec du chargement de la carte source par les Outils de développement : Impossible d'analyser le contenu de http://localhost:3000/requestProvider.js.map : Unexpected token < in JSON at position 0
```

### Operating system

MAC OS Big Sur

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by rmdorsey** [comment]
how's this coming along?  Any eta?  I just recently encountered this issue...
