### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by BabyTeeth** [metaplex-foundation/metaplex#1992]
### Which package is this bug report for?

candy machine cli

### Issue description

Can't upload images to devnet.

### Command

```shell
npx ts-node C:/Users/jakee/solana-nft/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k C:\Users\jakee\Solana-NFT\keypair.json -cp C:\Users\jakee\Solana-NFT\config.json -c example C:\Users\jakee\Solana-NFT\assets
```

### Relevant log output

```shell
Error deploying config to Solana network. Error: Invalid public key input
    at new PublicKey (C:\Users\jakee\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\publickey.ts:58:17)
    at C:\Users\jakee\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:169:24
    at Array.map (<anonymous>)
    at uploadV2 (C:\Users\jakee\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:167:60)
    at Command.<anonymous> (C:\Users\jakee\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:269:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
upload was not successful, please re-run. Error: Invalid public key input
    at new PublicKey (C:\Users\jakee\solana-nft\metaplex\js\node_modules\@solana\web3.js\src\publickey.ts:58:17)
    at C:\Users\jakee\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:169:24
    at Array.map (<anonymous>)
    at uploadV2 (C:\Users\jakee\solana-nft\metaplex\js\packages\cli\src\commands\upload.ts:167:60)
    at Command.<anonymous> (C:\Users\jakee\solana-nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:269:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Looks like an issue with your keypair file.

**Comment by BabyTeeth** [comment]
I didn't have my json files with my creator's address filled out was the problem I think

**Comment by stegaBOB** [comment]
Gotcha
