### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nftogetyourich** [metaplex-foundation/metaplex#1996]
### Which package is this bug report for?

candy machine cli

### Issue description

i try to run npx ts-node js/packages/cli/src/candy-machine-cli.ts upload...
and i noticed "upload" no longer works, so i read doc and see we have to use v2, then i have the following problem, please help

### Command

```shell
PS C:\Users\user\Desktop\solana\metaplex-master> ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -k ~/.config/solana/devnet.json ./assets  
internal/modules/cjs/loader.js:905
  throw err;
  ^

PS C:\Users\user\Desktop\solana\metaplex-master> ts-node js/packages/cli/src/candy-machine-v2-cli.ts upload -k ~/.config/solana/devnet.json ./assets
```

### Relevant log output

```shell
Error: Cannot find module './candy-machine-v2-cli.ts'
Require stack:
- C:\Users\user\Desktop\solana\metaplex-master\~\metaplex\js\packages\cli\src\imaginaryUncacheableRequireResolveScript
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at requireResolveNonCached (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:489:16)
    at phase3 (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:263:27)
    at bootstrap (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:44:30)
    at main (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:32:12)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js:519:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\Desktop\\solana\\metaplex-master\\~\\metaplex\\js\\packages\\cli\\src\\imaginaryUncacheableRequireResolveScript'
  ]
}

error: required option '-cp, --config-path <string>' not specified
```

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Looks like you didn't run `yarn install`/`yarn bootstrap` and/or are missing some options that you need to pass in.
