### ISSUE TITLE
[Bug]: Transaction simulation failed: Error processing Instruction 0: Program failed to complete 

### ISSUE THREAD

**Issue by andiiskandarabdullah13** [metaplex-foundation/metaplex#1997]
### Which package is this bug report for?

candy machine cli

### Issue description

1. upload 5 assets
2. add new assets 5 items (with the filename continue the previous index)
3. then upload again with the assets folder that has been added 

### Command

```shell
ts-node src/candy-machine-v2-cli.ts upload -e devnet -k ~/.config/solana/devnet.json -cp config.json -c example assets/
```

### Relevant log output

```shell
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Instruction: AddConfigLines
    Program log: panicked at 'range end index 3117 out of range for slice of length 1927', src/lib.rs:581:18
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 78434 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/var/www/html/purraria-nft/node_modules/@solana/web3.js/src/connection.ts:3964:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/var/www/html/purraria-nft/node_modules/@solana/web3.js/src/connection.ts:3921:20)
    at async sendAndConfirmRawTransaction (/var/www/html/purraria-nft/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/var/www/html/purraria-nft/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/var/www/html/purraria-nft/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async /var/www/html/purraria-nft/src/commands/upload.ts:375:19
    at async Promise.all (index 0)
    at async uploadV2 (/var/www/html/purraria-nft/src/commands/upload.ts:352:7)
    at async Command.<anonymous> (/var/www/html/purraria-nft/src/candy-machine-v2-cli.ts:187:7) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    "Program log: panicked at 'range end index 3117 out of range for slice of length 1927', src/lib.rs:581:18",
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 78434 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete'
  ]
}
saving config line 0-9 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/var/www/html/purraria-nft/node_modules/@solana/web3.js/src/connection.ts:3964:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/var/www/html/purraria-nft/node_modules/@solana/web3.js/src/connection.ts:3921:20)
    at async sendAndConfirmRawTransaction (/var/www/html/purraria-nft/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/var/www/html/purraria-nft/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/var/www/html/purraria-nft/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async /var/www/html/purraria-nft/src/commands/upload.ts:375:19
    at async Promise.all (index 0)
    at async uploadV2 (/var/www/html/purraria-nft/src/commands/upload.ts:352:7)
    at async Command.<anonymous> (/var/www/html/purraria-nft/src/candy-machine-v2-cli.ts:187:7) {
  logs: [
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]',
    'Program log: Instruction: AddConfigLines',
    "Program log: panicked at 'range end index 3117 out of range for slice of length 1927', src/lib.rs:581:18",
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 78434 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete'
  ]
}
Done. Successful = false.
ended at: 2022-03-23T03:55:55.701Z. time taken: 00:01:34
```

### Operating system

ubuntu 20

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by izzyx6** [comment]
I have a similar issue. Need help!!

![image](https://user-images.githubusercontent.com/45260503/159885784-646dae28-5a3a-4f03-8851-e12422c988a7.png)
@stegaBOB

**Comment by izzyx6** [comment]
@stegaBOB I have similar issue when uploading 5k assets to mainnet

**Comment by stegaBOB** [comment]
Did you modify the size of your candy machine after uploading? It looks like this is what happened

**Comment by andiiskandarabdullah13** [comment]
> Did you modify the size of your candy machine after uploading? It looks like this is what happened

Of course, but it's still an error like that

**Comment by stegaBOB** [comment]
Then you didn't check the docs. You can't modify the size of your candy machine after creating it.

**Comment by myreceipt** [comment]
> Did you modify the size of your candy machine after uploading? It looks like this is what happened

What size did you mean? I really don't understand.
I'm also having the same issue here.
Please anyone here answers with a clear solution.

Thanks!

**Comment by stegaBOB** [comment]
After creating the candy machine you can't change the total number of assets.
