### ISSUE TITLE
[Bug]: ExperimentalWarning: buffer.Blob is an experimental feature.

### ISSUE THREAD

**Issue by yadardour** [metaplex-foundation/metaplex#2002]
### Which package is this bug report for?

candy machine cli

### Issue description

I have tried to upload on the devnet and I've got this error 

C:\Users\21267\Desktop\v3>ts-node C:\Users\21267\Desktop\v3\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -k seGqEzZdmmDY6kZSjig6YpTbHDKYkb7GXNdgYkoR1yj.json -cp config.json assets

wallet public key: seGqEzZdmmDY6kZSjig6YpTbHDKYkb7GXNdgYkoR1yj
(node:7316) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\21267\Desktop\v3\metaplex\js\packages\cli\src\helpers\various.ts:67
  const config = JSON.parse(configString);
                      ^
SyntaxError: Unexpected token : in JSON at position 321
    at JSON.parse (<anonymous>)
    at getCandyMachineV2Config (C:\Users\21267\Desktop\v3\metaplex\js\packages\cli\src\helpers\various.ts:67:23)
    at Command.<anonymous> (C:\Users\21267\Desktop\v3\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:157:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Command

```shell
C:\Users\21267\Desktop\v3>ts-node C:\Users\21267\Desktop\v3\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -k seGqEzZdmmDY6kZSjig6YpTbHDKYkb7GXNdgYkoR1yj.json -cp config.json assets
```

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Looks like there is probably an error in your config.json file. Please share that. Thanks.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/93608862/180459177-e532dc3d-0b62-4559-be26-d7b51c3faf62.png)

**Comment by SylvainSimon** [comment]
I'v the same warning here

**Comment by off1n3** [comment]
I'd a same warning, but my module is crashed and not work again without restart it.

(node:1593) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at new Blob (node:internal/blob:138:5)
    at _RequestManager.resolveRequest (~/node_modules/@discordjs/rest/dist/index.js:892:36)
    at async _RequestManager.queueRequest (~/node_modules/@discordjs/rest/dist/index.js:848:35)
    at async REST.request (~/node_modules/@discordjs/rest/dist/index.js:1000:22)
    at async ChatInputCommandInteraction.reply (~/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:110:5)
