### ISSUE TITLE
[Bug]: Error Uploading

### ISSUE THREAD

**Issue by nftogetyourich** [metaplex-foundation/metaplex#2008]
### Which package is this bug report for?

candy machine cli

### Issue description

i try to upload img+json to candy machine, but i have so many errors

### Command

```shell
Beginning the upload for 10000 (img+json) pairs
started at: 1648182104828
config for a candy machine with publickey: 3iidDi6fqyRWd1fLY28URSJ2piCBnB9qShZwZp5BrrjF has been already initialized
[10] out of [10000] items have been uploaded
Starting upload for [9990] items, format {"mediaExt":".png","index":"10"}
Progress: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 21/9990
Error uploading {"mediaExt":".png","index":"16"} asset (skipping) request to https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile failed, reason: connect ETIMEDOUT 216.239.36.54:443

Progress: [██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 25% | 2564/9990(node:284) UnhandledPromiseRejectionWarning: FetchError: request to https:....../ failed, reason: socket hang up
    at ClientRequest.<anonymous> (C:\Users\user\v2\metaplex\js\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at TLSSocket.socketOnEnd (_http_client.js:499:9)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:475:12)
```

### Operating system

windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Try using `arweave-sol` instead of the `arweave` option.
