### ISSUE TITLE
candy machine scan failed assets folder

### ISSUE THREAD

**Issue by ArmaBloody** [metaplex-foundation/metaplex#2010]
### Which package is this bug report for?

other

### Issue description

User@ArmaBloody MINGW64 ~/nft
$ ts-node \metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
>     -e devnet \
>     -k seller.json \
>     -cp config.json \
>     -c example \
>     \assets
Error: ENOENT: no such file or directory, scandir 'assets'
    at Object.readdirSync (node:fs:1392:3)
    at Argument.parseArg (C:\Users\User\nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:95:17)
    at myParseArg (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1095:34)
    at C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1127:19
    at Array.forEach (<anonymous>)
    at Command._processArguments (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1110:16)     
    at Command._parseCommand (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1230:12)
    at Command._dispatchSubcommand (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1057:25)   
    at Command._parseCommand (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1200:19)
    at Command.parse (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:889:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'assets'
}

### Command

```shell
ts-node \metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k seller.json \
    -cp config.json \
    -c example \
    \assets
```

### Relevant log output

```shell
User@ArmaBloody MINGW64 ~/nft
$ ts-node \metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
>     -e devnet \
>     -k seller.json \
>     -cp config.json \
>     -c example \
>     \assets
Error: ENOENT: no such file or directory, scandir 'assets'
    at Object.readdirSync (node:fs:1392:3)
    at Argument.parseArg (C:\Users\User\nft\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:95:17)
    at myParseArg (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1095:34)
    at C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1127:19
    at Array.forEach (<anonymous>)
    at Command._processArguments (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1110:16)     
    at Command._parseCommand (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1230:12)
    at Command._dispatchSubcommand (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1057:25)   
    at Command._parseCommand (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1200:19)
    at Command.parse (C:\Users\User\nft\metaplex\js\packages\cli\node_modules\commander\lib\command.js:889:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'assets'
}
```

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Please check our discord to get more help with this. Github issues arent the right format for this. https://discord.gg/metaplex. Thanks!

**Comment by ArmaBloody** [comment]
ok thanks:)
