### ISSUE TITLE
How to fix  ? Could not complete Bundlr tx upload successfully, exiting due to: Error: whilst uploading DataItem: 502 Bad Gateway 

### ISSUE THREAD

**Issue by NabiiBux** [metaplex-foundation/metaplex#2027]
### Which package is this bug report for?

candy machine cli

### Issue description

I had downloaded the latest metaplex and done all the steps now getting this error helps me to resolve   it, I had lost 3 sols stll collection is not uploaded can anyone also help me how to get a refund of those sol balance , that was lost?
.
Could not complete Bundlr tx upload successfully, exiting due to:  Error: whilst uploading DataItem: 502 Bad Gateway
    at NodeUploader.dataItemUploader (D:\metasol\metaplex\js\node_modules\@bundlr-network\client\build\common\upload.js:46:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at PromisePoolExecutor.handler (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:674:11)
upload was not successful, please re-run. Error: whilst uploading DataItem: 502 Bad Gateway
    at NodeUploader.dataItemUploader (D:\metasol\metaplex\js\node_modules\@bundlr-network\client\build\common\upload.js:46:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at PromisePoolExecutor.handler (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:674:11)

### Relevant log output

```shell
Could not complete Bundlr tx upload successfully, exiting due to:  Error: whilst uploading DataItem: 502 Bad Gateway
    at NodeUploader.dataItemUploader (D:\metasol\metaplex\js\node_modules\@bundlr-network\client\build\common\upload.js:46:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at PromisePoolExecutor.handler (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:674:11)
upload was not successful, please re-run. Error: whilst uploading DataItem: 502 Bad Gateway
    at NodeUploader.dataItemUploader (D:\metasol\metaplex\js\node_modules\@bundlr-network\client\build\common\upload.js:46:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:670:15
    at uploadTransaction (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:660:13)
    at PromisePoolExecutor.handler (D:\metasol\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:674:11)
```

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by NabiiBux** [comment]
I am receiving this issue please tell me exact process of uploading sir

**Comment by cesar4design** [comment]
Same for me with sugar

=> Upload error: Response failed with the following error: Unknown Error
=> Upload error: Response failed with the following error: Status: 502 Bad Gateway
