### ISSUE TITLE
[Bug]: Mint failed every time.

### ISSUE THREAD

**Issue by GottliebGlob** [metaplex-foundation/metaplex#2039]
### Which package is this bug report for?

candy machine cli

### Issue description

Hey! I've uploaded cm and now facing with a problem. Every time I try to mint I get "Mint Failed, please try again!"
If I look to the console I see 
![image](https://user-images.githubusercontent.com/53971863/162143645-1e9e5b00-89d4-479a-b5d1-3adbf25866df.png)
several times and finaly 
`Error: Timed out awaiting confirmation on transaction
    at connection.tsx:398:15
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.throw (runtime.js:119:21)
    at n (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:29:9)`

I know it's looking more like a solana problem. But may be someone knows what to do.

### Command

```shell
npx ts-node C:/Users/glebg/Data/Projects/candy-lab/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k Se4Gf2GsjgzZZyUfnhFVzVLcijsCXx5a9Erhsp5uoUF.json -cp config.json assets
```

### Relevant log output

```shell
REST null result for 5rB9pwFBUuez8F71iuLmQPP27JeZRYGDu88mfSr2VkRxLmyVk9AVDQAQbTFRxe1dHnnN9mh13bUbwbMRVSy8qkuB

Error: Timed out awaiting confirmation on transaction
    at connection.tsx:398:15
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.throw (runtime.js:119:21)
    at n (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:29:9)
```

### Operating system

win10

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by frasil1** [comment]
yea same

**Comment by mikecann** [comment]
same :(

**Comment by GottliebGlob** [comment]
> same :(
> yea same

I've fixed this by switching to https://solana-api.projectserum.com
