### ISSUE TITLE
[Bug]: (mainnet) Transaction was not confirmed in 60.01 seconds.

### ISSUE THREAD

**Issue by alexjs-dev** [metaplex-foundation/metaplex#2045]
### Which package is this bug report for?

candy machine cli

### Issue description

Having issues creating a candy machine on the mainnet. Have 399 NFTs to upload.

config:

```
{
  "price": 0.5,
  "number": 399,
  "gatekeeper": null,
  "solTreasuryAccount": "2qxCPKbCFVFmzEW7WReito3NAHxN13SqsFkCfEZLXNK9",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "08 April 2022 15:15:00 GMT+2",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "storage": "arweave",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "awsS3Bucket": null,
  "noRetainAuthority": false,
  "noMutable": false
}
```
➜  cli git:(master) ✗ solana --version
solana-cli 1.9.7 (src:08cc140d; feat:2191737503)

➜  cli git:(master) ✗ ts-node --version
v10.5.0

➜  cli git:(master) ✗ yarn --version
1.22.17

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e mainnet-beta \
    -k ~/.config/solana/main-test.json \
    -cp config.json \
    -c scrap1 \
    ./assets
```

### Relevant log output

```shell
Progress: [████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 10% | 4/39Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 37omi7.
    at Connection.confirmTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2782:13)
    at async sendAndConfirmRawTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async addConfigLines (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:550:22)
    at async PromisePoolExecutor.handler (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:588:7)
Error uploading {"mediaExt":".png","index":"275"} asset (skipping) Timed out awaiting confirmation on transaction
Failed writing indices 32-41: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 37omi7DU61wqTqWPrpyB7dmBoAwVrYuf8S1a5A2RoyJWQt814Tr94hSb5zF46PPp.
Progress: [██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 15% | 6/39Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 4memVV.
    at Connection.confirmTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2782:13)
    at async sendAndConfirmRawTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async addConfigLines (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:550:22)
    at async PromisePoolExecutor.handler (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:588:7)
Progress: [███████████████████████████████░░░░░░░░░] 77% | 311/399
Failed writing indices 52-61: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 4memVViA4GdnTgK4DCUL35Bs7vqUXXz97oE2D9wSQbafiaXreFAQirsqWKdzLvjj.
Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 54FnLP9CrYjgUSddDFuQPHciQUfs721ixRCAiJzaSgxWNVZuA2DmK4syXgKAmCK29nZdn.
    at Connection.confirmTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2782:13)
    at async sendAndConfirmRawTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async addConfigLines (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:550:22)
    at async PromisePoolExecutor.handler (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:588:7)

Failed writing indices 72-81: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 54FnLP9CrYjgUSddDFuQPHciQUfs721ixRCAiJzaSgxWNVZuA2DmK4syXgKAmCK2.
Progress: [███████████████████████████░░░░░░░░░░░░░] 66% | 26/39Translating error Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 35nW6.
    at Connection.confirmTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2782:13)
    at async sendAndConfirmRawTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async addConfigLines (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:550:22)
    at async PromisePoolExecutor.handler (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:588:7)

Failed writing indices 296-306: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 35nW6ZFFqpGZXXFfqPQGoryW54AK6ntkMtz4TfH2STX4w5dAXeYP7N6VeaadDm.
Progress: [██████████████████████████████░░░░░░░░░░] 74% | 29/39Translating error Error: failed to get recent blockhash: FetchError: request to https://api.metaplex.solana.com/ failed, reason: Clientd
    at Connection.getRecentBlockhash (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3130:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Provider.send (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:102:7)
    at async Object.rpc [as addConfigLines] (/Users/aleksei.d/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
    at async addConfigLines (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:550:22)
    at async PromisePoolExecutor.handler (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:588:7)
    at async PromisePoolExecutor.waitForTaskToFinish (/Users/aleksei.d/metaplex/js/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:208:9)
    at async PromisePoolExecutor.process (/Users/aleksei.d/metaplex/js/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:198:17)
    at async PromisePoolExecutor.start (/Users/aleksei.d/metaplex/js/node_modules/@supercharge/promise-pool/dist/promise-pool-executor.js:160:16)

Failed writing indices 388-397: failed to get recent blockhash: FetchError: request to https://api.metaplex.solana.com/ failed, reason: Client network socket disconnected before secure TLS connectiond
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ invoke [1]
    Program log: Instruction: AddConfigLines
    Program log: panicked at 'range end index 96717 out of range for slice of length 96585', src/lib.rs:581:18
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ consumed 20984 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/Users/aleksei.d/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3964:13)
    at runMicrotasks (<anonymous>)
Done. Successful = false.ections (internal/process/task_queues.js:95:5)
ended at: 2022-04-08T16:08:42.206Z. time taken: 00:15:54ei.d/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3921:20)
```

### Operating system

MacOS 11.6

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by alexjs-dev** [comment]
If I change config to use "arweave-sol" I still get timeouts...

Rejecting for timeout...
Timeout Error caught { timeout: true }
Error deploying config to Solana network. Error: Timed out awaiting confirmation on transaction
    at sendSignedTransaction (/Users/aleksei.d/metaplex/js/packages/cli/src/helpers/transactions.ts:121:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendTransactionWithRetryWithKeypair (/Users/aleksei.d/metaplex/js/packages/cli/src/helpers/transactions.ts:59:26)
    at async setCollection (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/set-collection.ts:192:5)
    at async uploadV2 (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:181:28)
    at async Command.<anonymous> (/Users/aleksei.d/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:269:7)
upload was not successful, please re-run. Error: Timed out awaiting confirmation on transaction
    at sendSignedTransaction (/Users/aleksei.d/metaplex/js/packages/cli/src/helpers/transactions.ts:121:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendTransactionWithRetryWithKeypair (/Users/aleksei.d/metaplex/js/packages/cli/src/helpers/transactions.ts:59:26)
    at async setCollection (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/set-collection.ts:192:5)
    at async uploadV2 (/Users/aleksei.d/metaplex/js/packages/cli/src/commands/upload.ts:181:28)
    at async Command.<anonymous> (/Users/aleksei.d/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:269:7)

**Comment by StonedTigers** [comment]
same here, can devs do something? :D 🙏

**Comment by DojoSoMope** [comment]
It's a blockchain issue. Nothing to do with the protocol, Solana has addressed this already.

**Comment by StonedTigers** [comment]
ok, Thank u! Sorry I've been a lil degen
<3

**Comment by alexjs-dev** [comment]
After 8 attempts I was able to do it:
ScrapRobots.world

**Comment by genius665** [comment]
@stegaBOB

**Comment by stegaBOB** [comment]
> It's a blockchain issue. Nothing to do with the protocol, Solana has addressed this already.

Yep. Nothing we can do on our end unfortunately. It should be fixed in the 1.9.15 validator update that's currently being rolled out.

**Comment by DoubleHelixX** [comment]
Any update on this?  1.9.16 validator update is live now. Not sure how to find 1.9.15 and how to include the fix for it for metaplex after downloading this new code.

[Mainnet-beta validator v1.9.16](https://github.com/solana-labs/solana/tree/v1.9.16)

**Comment by chmerev** [comment]
I have the same problem. Why is the program removing the SOL from my account in favor of my Metaplex account without creating a CMv2?

**Comment by GDdark** [comment]
same here. Any update?

**Comment by siribanjoy** [comment]
I'm getting: Failed writing indices

Any update

**Comment by aa21** [comment]
@stegaBOB still having this error in Jan 2023. Timeout coming from `sendTransactionWithRetryWithKeypair` in Buy method of the Auction House CLI.
