### ISSUE TITLE
[Bug]: TSError

### ISSUE THREAD

**Issue by Amayyur** [metaplex-foundation/metaplex#2049]
### Which package is this bug report for?

candy machine cli

### Issue description

C:\Users\Me\Desktop\Test\metaplex>ts-node C:\Users\Me\Desktop\Test\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts upload -e devnet -k C:\Users\Me\Desktop\Test\my-keypair.json -cp C:\Users\Me\Desktop\Test\metaplex\js\packages\cli\config.json -c temp C:\Users\Me\Desktop\Test\metaplex\js\packages\cli\assets
C:\Users\Me\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
js/packages/cli/src/candy-machine-v2-cli.ts:4:47 - error TS2307: Cannot find module 'commander' or its corresponding type declarations.

4 import { InvalidArgumentError, program } from 'commander';
                                                ~~~~~~~~~~~
js/packages/cli/src/candy-machine-v2-cli.ts:5:25 - error TS2307: Cannot find module '@project-serum/anchor' or its corresponding type declarations.

5 import * as anchor from '@project-serum/anchor';
                          ~~~~~~~~~~~~~~~~~~~~~~~
js/packages/cli/src/candy-machine-v2-cli.ts:14:45 - error TS2307: Cannot find module '@solana/web3.js' or its corresponding type declarations.

14 import { PublicKey, LAMPORTS_PER_SOL } from '@solana/web3.js';
                                               ~~~~~~~~~~~~~~~~~
js/packages/cli/src/candy-machine-v2-cli.ts:41:17 - error TS2307: Cannot find module 'loglevel' or its corresponding type declarations.

41 import log from 'loglevel';
                   ~~~~~~~~~~
js/packages/cli/src/candy-machine-v2-cli.ts:45:25 - error TS2307: Cannot find module 'mime' or its corresponding type declarations.

45 import { getType } from 'mime';
                           ~~~~~~

    at createTSError (C:\Users\Me\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820:12)
    at reportTSError (C:\Users\Me\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:824:19)
    at getOutput (C:\Users\Me\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1014:36)
    at Object.compile (C:\Users\Me\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1322:43)
    at Module.m._compile (C:\Users\Me\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Me\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticCodes: [ 2307, 2307, 2307, 2307, 2307 ]

### Command

_No response_

### Relevant log output

_No response_

### Operating system

Windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by woomike** [comment]
@Amayyur Were you able to run the yarn commands properly?  I had a very similar issue when I installed using `npm` instead of `yarn`. I also had to bump the yarn version in the package.json to my version instead of `1.19.0`

**Comment by clarencechanxy** [comment]
Hi I got this bug too. Could someone help? 

ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts --version
/usr/local/lib/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:4:47 - error TS2307: Cannot find module 'commander' or its corresponding type declarations.

4 import { InvalidArgumentError, program } from 'commander';
                                                ~~~~~~~~~~~
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:5:25 - error TS2307: Cannot find module '@project-serum/anchor' or its corresponding type declarations.

5 import * as anchor from '@project-serum/anchor';
                          ~~~~~~~~~~~~~~~~~~~~~~~
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:14:45 - error TS2307: Cannot find module '@solana/web3.js' or its corresponding type declarations.

14 import { PublicKey, LAMPORTS_PER_SOL } from '@solana/web3.js';
                                               ~~~~~~~~~~~~~~~~~
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:41:17 - error TS2307: Cannot find module 'loglevel' or its corresponding type declarations.

41 import log from 'loglevel';
                   ~~~~~~~~~~
metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:45:25 - error TS2307: Cannot find module 'mime' or its corresponding type declarations.

45 import { getType } from 'mime';
                           ~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1322:43)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticCodes: [ 2307, 2307, 2307, 2307, 2307 ]
}

**Comment by G-Deps** [comment]
Hi, I'm getting the exact same error, was anyone able to solve it?
