### ISSUE TITLE
mint nft process always times out [Bug]: 

### ISSUE THREAD

**Issue by Alukadddd** [metaplex-foundation/metaplex#2069]
### Which package is this bug report for?

candy machine cli

### Issue description

mint nft process always times out

### Command

```shell
ts-node ~/tool/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \                                                             
    -e devnet \
    -k ~/.config/solana/id.json \
    -cp config.json \
    -c example \
    ./assets
```

### Relevant log output

```shell
/Users/steven/tool/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2548
      throw new Error(
            ^
Error: failed to get info about account CggtNXgCye2qk7fLohonNftqaKT35GkuZJwHrRghEvSF: FetchError: request to https://api.devnet.solana.com/ failed, reason: connect ETIMEDOUT 69.63.176.59:443
    at Connection.getAccountInfo (/Users/steven/tool/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2548:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.fetchIdl (/Users/steven/tool/metaplex/js/node_modules/@project-serum/anchor/src/program/index.ts:311:25)
    at async loadCandyProgramV2 (/Users/steven/tool/metaplex/js/packages/cli/src/helpers/accounts.ts:572:15)
    at async Command.<anonymous> (/Users/steven/tool/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:133:27)
```

### Operating system

mac

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Alukadddd** [comment]
Because of the node problem, just change the node

**Comment by leon198167** [comment]
I have same problem,can you tell me how to solve it，thank you very much
