### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Kunal123ETH** [metaplex-foundation/metaplex#2106]
### Which package is this bug report for?

candy machine cli

### Issue description

EISDIR: illegal operation on a directory, read

### Command

```shell
C:\Users\kunal\Desktop\moon>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config solana/devnet.json \ -cp ~\metaplex\js\packages\cli\config.json -c ~\metaplex\js\assets
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at loadWalletKey (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\src\helpers\accounts.ts:526:34)
    at Command.<anonymous> (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:132:40)
    at Command.listener [as _actionHandler] (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:481:17)
    at C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1237:65
    at Command._chainOrCall (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1153:12)
    at Command._parseCommand (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1237:27)
    at Command._dispatchSubcommand (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\node_modules\commander\lib\command.js:1059:25) {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
```

### Operating system

Wdow

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by spreadcharm** [comment]
Please remove "\" in each line of command if you are using windows.

**Comment by Kunal123ETH** [comment]
please explain briefly am using windows. there is no "" in each line

**Comment by Kunal123ETH** [comment]
C:\Users\kunal\Desktop\moon>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config solana/devnet.json \ -cp ~\metaplex\js\packages\cli\config.json -c ~\metaplex\js\assets
Error: EISDIR: illegal operation on a directory, read

**Comment by Kunal123ETH** [comment]
C:\Users\kunal\Desktop\moon>ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k ~/.config/solana/devnet.json \ -cp ~\metaplex\js\packages\cli\config.json -c C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\assets
wallet public key: FKGmDNhBRTKJ9ku7je15tZXF99qDqj4F3fTgooz85bao
C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\src\helpers\various.ts:68
  const config = JSON.parse(configString);
                      ^
SyntaxError: Unexpected string in JSON at position 235
    at JSON.parse (<anonymous>)
    at getCandyMachineV2Config (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\src\helpers\various.ts:68:23)
    at Command.<anonymous> (C:\Users\kunal\Desktop\moon\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:158:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


now  get this error  verify my assets and ts verify but this comes after the upload commend

**Comment by msgadi** [comment]
I am also facing the same issue.
