### ISSUE TITLE
Transaction simulation failed: Blockhash not found [Bug]: 

### ISSUE THREAD

**Issue by realsbd** [metaplex-foundation/metaplex#2110]
### Which package is this bug report for?

candy machine cli

### Issue description

I am trying to upload 7777 NFT to ipfs, I have 13.4 SOL in my balance and am getting this error:

`Beginning the upload for 7777 (img+json) pairs
started at: 1651866132353
initializing candy machine
Transaction simulation failed: Blockhash not found

Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:19)
    at async Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: []
}
Error deploying config to Solana network. SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:19)
    at async Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: []
}
upload was not successful, please re-run. SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:19)
    at async Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: []
}`

I have tried everything but haven't got this solved.

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k ./mainnet-key.json -cp ~/dev/config.json -c mainnet --rpc-url https://solana--mainnet.datahub.figment.io/apikey/XXXXXXXXXXXXXXXXX/ ~/metaplex/js/packages/cli/assets-original
```

### Relevant log output

```shell
Beginning the upload for 7777 (img+json) pairs
started at: 1651866132353
initializing candy machine
Transaction simulation failed: Blockhash not found

Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:19)
    at async Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: []
}
Error deploying config to Solana network. SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:19)
    at async Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: []
}
upload was not successful, please re-run. SendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found
    at Connection.sendEncodedTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
    at async createCandyMachineV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\helpers\accounts.ts:150:11)
    at async uploadV2 (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\commands\upload.ts:130:19)
    at async Command.<anonymous> (C:\Users\Test\Desktop\crypto_job\7fp\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:184:7) {
  logs: []
}
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by mannomion** [comment]
the same issue. and dont know how to fix
