### ISSUE TITLE
[Bug]: candy machine v2 typescript errors

### ISSUE THREAD

**Issue by seiyria** [metaplex-foundation/metaplex#2115]
### Which package is this bug report for?

candy machine cli

### Issue description

```
$ git clone https://github.com/metaplex-foundation/metaplex.git
$ cd metaplex/js
$ yarn install && yarn bootstrap && yarn build
```

### Command

```shell
npx ts-node packages/cli/src/candy-machine-v2-cli.ts --version
```

### Relevant log output

```shell
C:\Users\seiyria\GitHub\metaplex\js\node_modules\ts-node\src\index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
packages/cli/src/candy-machine-v2-cli.ts(73,21): error TS7006: Parameter 'value' implicitly has an 'any' type.
packages/cli/src/candy-machine-v2-cli.ts(216,31): error TS2538: Type 'null' cannot be used as an index type.
packages/cli/src/candy-machine-v2-cli.ts(218,42): error TS2538: Type 'null' cannot be used as an index type.
packages/cli/src/candy-machine-v2-cli.ts(279,9): error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.
packages/cli/src/candy-machine-v2-cli.ts(290,9): error TS2322: Type 'PublicKey | null' is not assignable to type 'PublicKey'.
  Type 'null' is not assignable to type 'PublicKey'.
packages/cli/src/candy-machine-v2-cli.ts(390,64): error TS2571: Object is of type 'unknown'.
packages/cli/src/candy-machine-v2-cli.ts(477,75): error TS2571: Object is of type 'unknown'.
packages/cli/src/candy-machine-v2-cli.ts(563,29): error TS2531: Object is possibly 'null'.
packages/cli/src/candy-machine-v2-cli.ts(600,7): error TS2531: Object is possibly 'null'.
packages/cli/src/candy-machine-v2-cli.ts(876,51): error TS7006: Parameter 'creator' implicitly has an 'any' type.
packages/cli/src/candy-machine-v2-cli.ts(1006,29): error TS7006: Parameter 'index' implicitly has an 'any' type.
packages/cli/src/candy-machine-v2-cli.ts(1173,21): error TS2531: Object is possibly 'null'.
packages/cli/src/candy-machine-v2-cli.ts(1180,5): error TS2531: Object is possibly 'null'.
packages/cli/src/candy-machine-v2-cli.ts(1190,9): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.
packages/cli/src/candy-machine-v2-cli.ts(1237,22): error TS7006: Parameter 'value' implicitly has an 'any' type.
packages/cli/src/candy-machine-v2-cli.ts(1237,29): error TS7006: Parameter 'prev' implicitly has an 'any' type.

    at createTSError (C:\Users\seiyria\GitHub\metaplex\js\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (C:\Users\seiyria\GitHub\metaplex\js\node_modules\ts-node\src\index.ts:517:19)
    at getOutput (C:\Users\seiyria\GitHub\metaplex\js\node_modules\ts-node\src\index.ts:752:36)
    at Object.compile (C:\Users\seiyria\GitHub\metaplex\js\node_modules\ts-node\src\index.ts:968:32)
    at Module.m._compile (C:\Users\seiyria\GitHub\metaplex\js\node_modules\ts-node\src\index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\seiyria\GitHub\metaplex\js\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

### Operating system

windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment]
Try using our sugar CLI. https://docs.metaplex.com/sugar/introduction

**Comment by seiyria** [comment]
I have moved to sugar, and don't have any specific issues so far (it seems to work!), but I did find this issue while trying to set up CMv2.

**Comment by statikdev** [comment]
@stegaBOB // is this now deprecated?

**Comment by stegaBOB** [comment]
No, but I want it to be. The easiest way to debug problems with this TS CLI is to not use it lol.
