### ISSUE TITLE
[Bug]: ts 2554

### ISSUE THREAD

**Issue by b3ucx** [metaplex-foundation/metaplex#2122]
### Which package is this bug report for?

candy machine cli

### Issue description

ts-node candy-machine-v2-cli.ts upload -e devnet -k C:/Users/B3ucx/.config/solana/id.json -cp config.json -c temp ./assets
C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
helpers/accounts.ts:47:43 - error TS2554: Expected 0 arguments, but got 1.

47     accountInfo.delegatedAmount = new u64(0);
                                             ~

    at createTSError (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:820:12)
    at reportTSError (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:824:19)
    at getOutput (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1014:36)
    at Object.compile (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1322:43)
    at Module.m._compile (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\b3ucx\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2554 ]
}
PS C:\Users\b3ucx\Desktop\chichimzchine\metaplex\js\packages\cli\src> 

### Command

```shell
ts-node candy-machine-v2-cli.ts upload -e devnet -k C:/Users/B3ucx/.config/solana/id.json -cp config.json -c temp ./assets
```

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by b3ucx** [comment]
somebody can help me with this problem?
