### ISSUE TITLE
[Bug]: Arweave-sol upload

### ISSUE THREAD

**Issue by YoxGithub** [metaplex-foundation/metaplex#2124]

**Comment by YoxGithub** [comment]
Here is another log outputs :

wallet public key: HQYZfBS3xfJiDfEHJeE3f3jG32eKtQShD62Sc2SnetXw
USING CUSTOM URL (my custom rpc note: I edit this part)
(node:4416) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Beginning the upload for 1000 (img+json) pairs
started at: 1652573543099
config for a candy machine with publickey: DV3ty5oQKATBQpdc3w6H5ueXQm165sFmcWakR2WHq67q has been already initialized
[0] out of [1000] items have been uploaded
Starting upload for [1000] items, format {"mediaExt":".png","index":"0"}
0.297389218 SOL to upload 1399.296MB with buffer
Current balance 0.293960412. Sending fund txn...
upload was not successful, please re-run. Error: Tx undefined didn't finalize after 30 seconds
    at Utils.confirmationPoll (C:\Users\pc\Desktop\BLOCKCHAIN\metaplex\js\node_modules\@bundlr-network\client\build\common\utils.js:88:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Fund.fund (C:\Users\pc\Desktop\BLOCKCHAIN\metaplex\js\node_modules\@bundlr-network\client\build\common\fund.js:43:9)
    at async makeArweaveBundleUploadGenerator (C:\Users\pc\Desktop\BLOCKCHAIN\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:552:7)
    at async uploadV2 (C:\Users\pc\Desktop\BLOCKCHAIN\metaplex\js\packages\cli\src\commands\upload.ts:244:24)
    at async Command.<anonymous> (C:\Users\pc\Desktop\BLOCKCHAIN\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:269:7)

**Comment by YoxGithub** [comment]
Looks like nobody is coming for help :(, how can I withdraw the txn fund? anyone please
