### ISSUE TITLE
[Bug]: Uploading assets on aws s3 using CM v2

### ISSUE THREAD

**Issue by PnW1** [metaplex-foundation/metaplex#2129]
### Which package is this bug report for?

candy machine cli

### Issue description

1) select storage "aws" in config.json
2) add bucket name
3) Run command for creating candy machine

it says all assets uploaded, and give link in the cache but the files are not accessible using that link.

example: https://somthing.s3.amazonaws.com/assets\\1.json

### Command
AWS_ACCESS_KEY_ID=MY_KEY AWS_SECRET_ACCESS_KEY=MY_SECRET ts-node candy-machine-v2-cli.ts upload -e devnet  -k ../phantom1-keypair.json  -cp ../config.json -c example ./assets

### Relevant log output

```shell
{
    "program": {
        "uuid": "ED...g",
        "candyMachine": "EDqqwgY3x4t................AvuCTJEQHNF",
        "collection": "84ciaE2jbM.................fqQ9bCCkyGPe"
    },
    "items": {
        "0": {
            "link": "https://somthing.s3.amazonaws.com/assets\\0.json",
            "imageLink": "https://somthing.s3.amazonaws.com/assets/0.png?ext=png",
            "name": "Soul Van #0",
            "onChain": true,
            "verifyRun": false
        },
        "1": {
            "link": "https://somthing.s3.amazonaws.com/assets\\1.json",
            "imageLink": "https://somthing.s3.amazonaws.com/assets/1.png?ext=png",
            "name": "Soul Van #1",
            "onChain": true,
            "verifyRun": false
        }
    },
    "env": "devnet",
    "cacheName": "example"
}
```

### Operating system

ubuntu 20

### Priority this issue should have

High (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by ArchTaqi** [comment]
I'm also facing the same issues, below is my settings for storage;
```
{
    "storage": "aws",
    "awsS3Bucket": "metaplex-assets",
}
```
And using this command to upload assets,

```
AWS_ACCESS_KEY_ID=MY_KEY AWS_SECRET_ACCESS_KEY=MY_SECRET \
ts-node metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/devnet.json \
    -l debug \
    -cp metaplex/config.json \
    -c WeFrens \
    ~/metaplex-foundation/assets
```

```
Location: https://metaplex-assets.s3.amazonaws.com//Users/muhammadtaqi/metaplex-foundation/assets/98.json
Updating cache for  98
ed using the specified endpoint. Please send all future requests to this endpoint.direct: The bucket you are attempting to access must be address
protocols/Aws_restXml.js:8037:24)bjectCommandError (/Users/muhammadtaqi/metaplex-foundation/metaplex/js/node_modules/@aws-sdk/client-s3/dist-cjs/
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/muhammadtaqi/metaplex-foundation/metaplex/js/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /Users/muhammadtaqi/metaplex-foundation/metaplex/js/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
ndardRetryStrategy.js:51:46)rategy.retry (/Users/muhammadtaqi/metaplex-foundation/metaplex/js/node_modules/@aws-sdk/middleware-retry/dist-cjs/Sta
ddleware.js:56:20rs/muhammadtaqi/metaplex-foundation/metaplex/js/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMi
    at async /Users/muhammadtaqi/metaplex-foundation/metaplex/js/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async uploadFile (/Users/muhammadtaqi/metaplex-foundation/metaplex/js/packages/cli/src/helpers/upload/aws.ts:26:5)
    at async awsUpload (/Users/muhammadtaqi/metaplex-foundation/metaplex/js/packages/cli/src/helpers/upload/aws.ts:81:23) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 301,
    requestId: undefined,
    extendedRequestId: 'nVIKs/addafsfsadfwer223/9bvTd6FvnZAKhWy/vhBabxi8U+7F4TjmdVdGTf4E2t+LvLLqi+Y=',
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  Code: 'PermanentRedirect',
  Endpoint: 'metaplex-assets.s3.eu-west-2.amazonaws.com',
  Bucket: 'metaplex-assets',
  RequestId: 'M07BG2TVVWRK2Y5Z',
  HostId: 'nVIKs/0FgetBhSHeNerfOLu/9bvTd6F6nZgKhW3/vh6bxi3U+7F6TjmdgdGTfdE2f+LvgLqi+Y=',
  '$response': HttpResponse {
    statusCode: 301,
    headers: {
      'x-amz-bucket-region': 'eu-west-2',
      'x-amz-request-id': 'M07BG2454VWRK2Y5Z',
      'x-amz-id-2': 'nVIKs/0FgetBhSHeNerfOLu/9bvdd36FvnZAKhWy/vhBabxi8U+745gfdTjmdVdGTf4E2t+LvLLqi+Y=',
      'content-type': 'application/xml',
      'transfer-encoding': 'chunked',
      date: 'Wed, 18 May 2022 21:10:01 GMT',
      server: 'AmazonS3',
      connection: 'close'
    },
    body: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 301,
      statusMessage: 'Moved Permanently',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [ClientRequest],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 16,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    }
  }
}
```
