### ISSUE TITLE
[Bug]: I Cannot withdraw my Rent from Candy Machine | return data.map(item => ({               ^ TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Thagg3rs** [metaplex-foundation/metaplex#2164]
### Which package is this bug report for?

candy machine cli

### Issue description

When i try to withdraw my rent it will not let me. Even when i used 2 different commands( withdraw_all and withdraw HT1MBvRbJU2NSo8hE6q1Zq6jLAo7NBEiQaRDxxxxxxxx ). I get the same response for both commands. If it helps ive had this rent for about a month, April 27TH

### Command

```shell
ts-node js/packages/cli/src/candy-machine-v2-cli.ts  withdraw_all -e mainnet-beta -k ~/.config/solana/mainnet-beta.json 

and 

ts-node js/packages/cli/src/candy-machine-v2-cli.ts  withdraw HT1MBvRbJU2NSo8hE6q1Zq6jLAo7NBEiQaRDxxxxxxxx -e mainnet-beta -k ~/.config/solana/mainnet-beta.json
```

### Relevant log output

```shell
(node:21680) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
C:\.Real\~\metaplex\js\packages\cli\src\helpers\accounts.ts:741
  return data.map(item => ({
              ^
TypeError: Cannot read properties of undefined (reading 'map')
    at unsafeResAccounts (C:\.Real\~\metaplex\js\packages\cli\src\helpers\accounts.ts:741:15)
    at getProgramAccounts (C:\.Real\~\metaplex\js\packages\cli\src\helpers\accounts.ts:721:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (C:\.Real\~\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:341:42)
```

### Operating system

Windows 10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by TestThisX** [comment]
Hi All, 

Facing the same issue atm... What was the solution for this ?
ts-node /Applications/XAMPP/xamppfiles/htdocs/OTHERS/deprecated-clis-main/src/candy-machine-v1-cli.ts withdraw -e mainnet-beta -k /Applications/XAMPP/xamppfiles/htdocs/OTHERS/deprecated-clis-main/key.json --dry

CMv1
Using cluster mainnet-beta

(node:73300) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Applications/XAMPP/xamppfiles/htdocs/OTHERS/deprecated-clis-main/src/helpers/accounts.ts:743
  return data.map(item => ({
              ^
TypeError: Cannot read properties of undefined (reading 'map')
    at unsafeResAccounts (/Applications/XAMPP/xamppfiles/htdocs/OTHERS/deprecated-clis-main/src/helpers/accounts.ts:743:15)
    at getProgramAccounts (/Applications/XAMPP/xamppfiles/htdocs/OTHERS/deprecated-clis-main/src/helpers/accounts.ts:723:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/OTHERS/deprecated-clis-main/src/candy-machine-v1-cli.ts:260:41)
