### ISSUE TITLE
Error: The "path" argument must be type of string. Received undefined.

### ISSUE THREAD

**Issue by Furdew** [metaplex-foundation/metaplex#2190]
### Which package is this bug report for?

candy machine cli

### Issue description

Hi! So i'm trying to upload my assets but i keep running into an issue. It keeps saying "upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined" Now i know why (im pretty sure) its returning that. as you'll see in the log output below, its saying its skipping unsupported file "/server3/" which is where all of my files are located. so that would make sense why the path is returning undefined. unless im totally wrong there. how do i go about making it not skip that file? 

### Command

```shell
ts-node c:/server3/NFT/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload \ -e devnet \ -k C:\server3\NFT\keypair.json \ -cp config.json \ -c example \ ./assets
```

### Relevant log output

```shell
WARNING: Skipping unsupported file type \server3
WARNING: Skipping unsupported file type \Setups
WARNING: Skipping unsupported file type \solana-install-tmp
WARNING: Skipping unsupported file type \steamcmd
WARNING: Skipping unsupported file type \swapfile.sys
WARNING: Skipping unsupported file type \System Volume Information
WARNING: Skipping unsupported file type \temp
WARNING: Skipping unsupported file type \UpcomingCollections
WARNING: Skipping unsupported file type \user
WARNING: Skipping unsupported file type \Users
WARNING: Skipping unsupported file type \Valorant
WARNING: Skipping unsupported file type \Windows
WARNING: Skipping unsupported file type \XboxGames
Beginning the upload for 10 (img+json) pairs
started at: 1654847330565
upload was not successful, please re-run. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:654:5)
    at uploadV2 (c:\server3\NFT\metaplex\js\packages\cli\src\commands\upload.ts:119:24)
    at Command.<anonymous> (c:\server3\NFT\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:271:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Operating system

windows

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Furdew** [comment]
Found out it was because windows has issues with multi line commands. Once i changed my command to this it worked: ts-node c:/server3/NFT/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet -k C:\server3\NFT\keypair.json -cp config.json -c example c:/server3/NFT/assets
