### ISSUE TITLE
[Error]: Cannot read properties of null (reading '_bn')

### ISSUE THREAD

**Issue by JRB-y** [metaplex-foundation/metaplex#2218]
### Which package is this bug report for?

candy machine cli

### Issue description

I verify_assets with success!
When try to deploy, from`metaplex/js` folder i run
```bash
ts-node packages/cli/src/candy-machine-v2-cli.ts upload \
    -e devnet \
    -k ~/.config/solana/id.json \
    -cp packages/cli/config.json \
    -c example \
    ./art
```

I got this error 
```bash
wallet public key: 8Ge8euDYLK5Puar6LXMmHnPHgPAQWHSzj7563dshQScN
Using cluster devnet
/Users/jrb/web3/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:35
  return (value as PublicKeyData)._bn !== undefined;
                                  ^
TypeError: Cannot read properties of null (reading '_bn')
    at isPublicKeyData (/Users/jrb/web3/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:35:35)
    at new PublicKey (/Users/jrb/web3/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:51:9)
    at getCandyMachineV2Config (/Users/jrb/web3/metaplex/js/packages/cli/src/helpers/various.ts:198:36)
    at Command.<anonymous> (/Users/jrb/web3/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:166:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Operating system

macos

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by JRB-y** [comment]
I think we can close this issue: 
It was the `-cp packages/cli/config.json \` it needs to be `-cp ./packages/cli/config.json \`
