### ISSUE TITLE
failed to get info about account CggtNXgCye2qk7fLohonNftqaKT35GkuZJwHrRghEvSF

### ISSUE THREAD

**Issue by ttwo22** [metaplex-foundation/metaplex#2236]
Using cluster devnet
D:\Project\Solana\deprecated-clis\node_modules\@project-serum\anchor\node_modules\@solana\web3.js\src\connection.ts:2548      throw new Error(
            ^
Error: failed to get info about account CggtNXgCye2qk7fLohonNftqaKT35GkuZJwHrRghEvSF: FetchError: request to https://api.devnet.solana.com/ failed, reason: read ECONNRESET
    at Connection.getAccountInfo (D:\Project\Solana\deprecated-clis\node_modules\@project-serum\anchor\node_modules\@solana\web3.js\src\connection.ts:2548:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.fetchIdl (D:\Project\Solana\deprecated-clis\node_modules\@project-serum\anchor\src\program\index.ts:311:25)
    at async loadCandyProgramV2 (D:\Project\Solana\deprecated-clis\src\helpers\accounts.ts:574:15)
    at async Command.<anonymous> (D:\Project\Solana\deprecated-clis\src\candy-machine-v2-cli.ts:141:27)

昨天正常使用，我换了个钱包，更换元数据重新上传就报错了。不知道这个CggtNXgCye2qk7fLohonNftqaKT35GkuZJwHrRghEvSF在哪

**Comment by wenhaogege66** [comment]
I met the same question too! I need help

**Comment by wenhaogege66** [comment]
我和我的好兄弟已经解决了这个问题，系统找不到信息的这个账户是Token Account，Token Account 是 Mint Account 和用户的绑定关系，NFT 由哪个钱包持有是由这个账户决定的。
Token Account的地址是由mint账户和NFT 持有者的账户计算出的，例如：
import { getAssociatedTokenAddress } from "@solana/spl-token";

const tokenAddress = await getAssociatedTokenAddress(
  mintAccount,    // NFT 的 Mint Address
  userAccount     // 该 NFT 的持有者
);
但是计算出了地址，该Token Account还未创建成功，所以我们需要自己提前创建Token Account：
    await createAssociatedTokenAccount(
      this.connection,
      Keypair.fromSecretKey(bs58.decode(ProgramConfig.NFT_ACCOUNT.SECRET_KEY)),
      try_mint.publicKey, 
      new PublicKey(ProgramConfig.NFT_ACCOUNT.PUBLIC_KEY)
      );

TRANSLATORS：
    My good brother and I have solved this problem. The Account in which the system cannot find information is the Token Account. The Token Account is the binding relationship between the Mint Account and the user, and the NFT is determined by which wallet it is held. Token Account address is calculated from accounts of mint and accounts of NFT holders, such as: 
import { getAssociatedTokenAddress } from "@solana/spl-token";

const tokenAddress = await getAssociatedTokenAddress(
  mintAccount,    // NFT 的 Mint Address
  userAccount     // 该 NFT 的持有者
);

However, after the address is calculated, the Token Account has not been created successfully, so we need to create a Token Account in advance:  
    await createAssociatedTokenAccount(
      this.connection,
      Keypair.fromSecretKey(bs58.decode(ProgramConfig.NFT_ACCOUNT.SECRET_KEY)),
      try_mint.publicKey, 
      new PublicKey(ProgramConfig.NFT_ACCOUNT.PUBLIC_KEY)
      );
