### ISSUE TITLE
TypeError when updating metaplex-foundation/js created NFT, cannot read 'ToBuffer'

### ISSUE THREAD

**Issue by Doughp** [metaplex-foundation/metaplex#2242]
**### Program:**
Metaplex-foundation/js(0.11.7)and Solana-Wallet-Adapter(0.9.16)
in Create-React-App 5

**### Preface:**
I created a function to create a NFT 

`const createNFT = async() => {
        const { nft } = await metaplex.nfts().create({
          uri: "https://arweave.net/5bd58f4V4UEuTl1MGFX1dn1tu3dQTKWo7fCeZyEqQzc",
          
        })
        console.log(nft)
      }`

Which worked fine creating my NFT, now I am trying to update the Metadata with this function
`     
 const _address = new PublicKey(address)

 const updateMetadata = async() => {

        const frozenNFT = await metaplex.nfts().update({
            nftOrSft: _address,
            uri: "https://www.arweave.net/MuV4ddqdaqPzVGNOt89EW1v8bf4wh94ENCmxoZCYbN0?ext=json"
          })
    
      }`

But I am getting this error in return:

findMetadataPda.ts:10 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toBuffer')
    at findMetadataPda (findMetadataPda.ts:10:1)
    at Object.handle (updateNft.ts:67:1)
    at Task.callback (OperationClient.ts:66:1)
    at Task.ts:82:1
    at Disposable.run (Disposable.ts:34:1)
    at Task.forceRun (Task.ts:74:1)
    at Task.run (Task.ts:51:1)
    at OperationClient.execute (OperationClient.ts:76:1)
    at NftClient.update (NftClient.ts:80:1)
    at updateMetadata (App.js:117:1)

**Comment by Doughp** [comment]
Just realized I put this in wrong one
