### ISSUE TITLE
Error while creating candyMachines - Failed to send transaction: Transaction simulation failed

### ISSUE THREAD

**Issue by mastercodercat** [metaplex-foundation/metaplex#2268]
I encountered an error while creating a candy machine using metaplex JS sdk.

> MetaplexError: SystemProgram > Unknown Program Error
>> Source: Program > SystemProgram [11111111111111111111111111111111]
>> Problem: The program [SystemProgram] at address [11111111111111111111111111111111] raised an error that is not recognized by the programs registered by the SDK.
>> Solution: Unfortunately, you will need to check the unparsed error below to investigate what went wrong. To get more helpful error messages, ensure the program that failed is registered by the SDK and provides an "errorResolver" method.

> Caused By: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
> 
> [ Logs: Program 11111111111111111111111111111111 invoke [1] |$> Transfer: insufficient lamports 10911747, need 173164800 |$> Program 11111111111111111111111111111111 failed: custom program error: 0x1 ]
> 
>     at RpcClient.parseProgramError (RpcClient.mjs:256:1)
>     at RpcClient.sendTransaction (RpcClient.mjs:77:1)
>     at async RpcClient.sendAndConfirmTransaction (RpcClient.mjs:108:1)
>     at async TransactionBuilder.sendAndConfirm (TransactionBuilder.mjs:151:1)
>     at async Object.handle (createCandyMachineV2.mjs:50:1)
>     at async Disposable.run (Disposable.mjs:24:1)
>     at async onContract (useDropDetail.ts:256:1)

```
const { nft: deployedNFT, tokenAddress } = await metaplex.nfts().create({
  uri,
  name: nft.name,
  symbol: collection.symbol,
  sellerFeeBasisPoints: (collection.royalty_percentage || 0) * 100,
  creators: publicKey ? [{ address: publicKey, share: 100 }] : [],
  collection: addressPubKey,
});
```

**Comment by Shinwari536** [comment]
hey everyone, anybody has a solution to this issue?
