### ISSUE TITLE
non-base58 character

### ISSUE THREAD

**Issue by Luukkk1** [metaplex-foundation/metaplex#2294]
I'm trying to create a token but when I'm running the program it gives me the following error:

Error: Non-base58 character
    at Object.decode (C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@solana\web3.js\node_modules\base-x\src\index.js:111:11)
    at new PublicKey (C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@solana\web3.js\lib\index.cjs.js:180:50)
    at C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@solana\web3.js\lib\index.cjs.js:1405:17
    at Array.forEach (<anonymous>)
    at Transaction.compileMessage (C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@solana\web3.js\lib\index.cjs.js:1403:16)
    at Transaction._compile (C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@solana\web3.js\lib\index.cjs.js:1528:26)
    at Transaction.partialSign (C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@solana\web3.js\lib\index.cjs.js:1649:26)
    at RpcClient.signTransaction (C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@metaplex-foundation\js\dist\cjs\plugins\rpcModule\RpcClient.cjs:47:19)
    at RpcClient.sendTransaction (C:\Users\luukh\OneDrive\Bureaublad\Solana-Token\node_modules\@metaplex-foundation\js\dist\cjs\plugins\rpcModule\RpcClient.cjs:65:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

**Comment by Abhishek7Tech** [comment]
@Luukkk1 Did you managed to solve this. I am getting a similar error?
