### ISSUE TITLE
Error when trying to run candy machine cli code 

### ISSUE THREAD

**Issue by aelqaraoui** [metaplex-foundation/metaplex#288]
I was trying to run the cli candy machine code when running create_candy_machine command

here is the error i encountered :
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18855 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (/home/amine/Projects/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/amine/Projects/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/amine/Projects/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/amine/Projects/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (/home/amine/Projects/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18855 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
/home/amine/Projects/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:30
      return new ProgramError(errorCode, errorMsg);
             ^
ProgramError
    at Function.parse (/home/amine/Projects/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (/home/amine/Projects/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 313,
  msg: 'Number of config lines must match items available'
}

**Comment by aneopsy** [comment]
Hello,
Can you send the command with your parameters ?

**Comment by DunnCreativeSS** [comment]
Different error, also with candymachine:

c:\Users\jd\Documents\metaplex\js\packages\cli\src>yarn ts-node cli upload "./" -k c:\Users\jd\solana.json
yarn run v1.22.11
$ c:\Users\jd\Documents\metaplex\js\node_modules\.bin\ts-node cli upload ./ -k c:\Users\jd\solana.json
Done
Done in 10.52s.

c:\Users\jd\Documents\metaplex\js\packages\cli\src>yarn ts-node cli create_candy_machine -k "c:\Users\jd\solana.json" -p 1
yarn run v1.22.11
$ c:\Users\jd\Documents\metaplex\js\node_modules\.bin\ts-node cli create_candy_machine -k c:\Users\jd\solana.json -p 1
(node:18348) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_bn' of undefined
    at isPublicKeyData (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\publickey.ts:29:35)
    at new PublicKey (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\publickey.ts:45:9)    at c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:586:20
    at step (c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:64:23)
    at Object.next (c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:45:53)
    at fulfilled (c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 10.51s.

c:\Users\jd\Documents\metaplex\js\packages\cli\src>

**Comment by DunnCreativeSS** [comment]
I don't think I'm actually that far yet, turns out if may have not seen my pngs/jsons?

c:\Users\jd\Documents\metaplex\js\packages\cli\src>yarn ts-node cli upload "./cm" -k c:\Users\jd\solana.json
yarn run v1.22.11
$ c:\Users\jd\Documents\metaplex\js\node_modules\.bin\ts-node cli upload ./cm -k c:\Users\jd\solana.json
Processing file: 0
Error deploying config to Solana network. Error: Non-base58 character
    at Object.decode (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\base-x\src\index.js:115:11)
    at new PublicKey (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\publickey.ts:50:30)
    at c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:356:28
    at Array.map (<anonymous>)
    at c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:354:54
    at step (c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:64:23)
    at Object.next (c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:45:53)
    at fulfilled (c:\Users\jd\Documents\metaplex\js\packages\cli\cli.ts:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Started awaiting confirmation for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
REST null result for 4KEnN3G6pcBTq5oPk83CMsjB65UXvYasVsHj53L7zwMagYYNKz6E6mUENN9v6wAezKjV9aRRwPeF5oeMem8bmFKR null
Rejecting for timeout...
Timeout Error caught { timeout: true }
(node:24472) UnhandledPromiseRejectionWarning: Error: Timed out awaiting confirmation on transaction
    at c:\Users\jd\Documents\metaplex\js\packages\cli\helper.ts:131:13
    at step (c:\Users\jd\Documents\metaplex\js\packages\cli\helper.ts:41:23)
    at Object.throw (c:\Users\jd\Documents\metaplex\js\packages\cli\helper.ts:22:53)
    at rejected (c:\Users\jd\Documents\metaplex\js\packages\cli\helper.ts:14:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DunnCreativeSS** [comment]
It's the same error, in publickey.

It doesn't like the publickey created?

--help says it wants a wallet, this is a wallet,

**Comment by DunnCreativeSS** [comment]
Alright, I hardcoded public key, painstakingly converted cli upload to do it mainnet-beta, now I have the exact same error as OP

yarn run v1.22.11ents\metaplex\js\packages\cli\src>yarn ts-node cli create_candy_machine -k  c:\Users\jd\solana.json -p 1
$ c:\Users\jd\Documents\metaplex\js\node_modules\.bin\ts-node cli create_candy_machine -k c:\Users\jd\solana.json -p 1
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20355 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3577:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Connection.sendRawTransaction (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3537:20)
    at Object.sendAndConfirmRawTransaction (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at Provider.send (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at Object.rpc [as initializeCandyMachine] (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 20355 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
(node:36620) UnhandledPromiseRejectionWarning: Error:
    at Function.parse (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36620) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36620) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DunnCreativeSS** [comment]
I believe the problem is the programids.

**Comment by DunnCreativeSS** [comment]
Getting there, what's the programId

const TOKEN_PROGRAM_ID = new PublicKey(
  "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
);
const SPL_ASSOCIATED_TOKEN_ACCOUNT_PROGRAM_ID = new PublicKey(
  "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
);
const TOKEN_METADATA_PROGRAM_ID = new PublicKey(
  "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
);
const programId =(SystemProgram.programId)

or

const programId = new PublicKey(
 (SystemProgram.programId)
);

fail with

c:\Users\jd\Documents\metaplex\js\packages\cli\src>yarn ts-node cli create_candy_machine -k  c:\\Users\\jd\\solana.json -p 1
yarn run v1.22.11
$ c:\Users\jd\Documents\metaplex\js\node_modules\.bin\ts-node cli create_candy_machine -k c:\\Users\\jd\\solana.json -p 1
(node:40320) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of null
    at Function.fetchIdl (c:\Users\jd\Documents\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\index.ts:311:51)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 10.79s.

**Comment by joaoh82** [comment]
Also getting same error
```
> ./metaplex upload --env devnet  --keypair ../../../../crypto/solana/SolanaWallet/my-keypair.json ./assets
(node:70995) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of null
    at Function.fetchIdl (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/index.js:118:61)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex-test --trace-warnings ...` to show where the warning was created)
```

**Comment by Millali-Ilyas** [comment]
Same, just messing around in devnet , anyone was successful on fixing issues that look like that ?

```
metaplex upload "./imgs"  --keypair "C:\Users\Admin\Desktop\solanaWallet\my-keypair.json" 


Beginning the upload for 3 (png+json) pairs
started at: 1631683878900
wallet public key: 7LXr2a9....uARYbD
Processing file: 0
initializing config
Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x66
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 3455 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x66
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66
    at Connection.sendEncodedTransaction (D:\NFT\metaplex\js\packages\cli\node_modules\@solana\web3.js\lib\index.cjs.js:4896:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (D:\NFT\metaplex\js\packages\cli\node_modules\@solana\web3.js\lib\index.cjs.js:4855:20)
    at async Object.sendAndConfirmRawTransaction (D:\NFT\metaplex\js\packages\cli\node_modules\@solana\web3.js\lib\index.cjs.js:6745:21)
    at async Provider.send (D:\NFT\metaplex\js\packages\cli\node_modules\@project-serum\anchor\dist\cjs\provider.js:84:22)
    at async Object.rpc [as initializeConfig] (D:\NFT\metaplex\js\packages\cli\node_modules\@project-serum\anchor\dist\cjs\program\namespace\rpc.js:11:31) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x66',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 3455 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x66'
  ]
}
Error deploying config to Solana network. ProgramError
    at Function.parse (D:\NFT\metaplex\js\packages\cli\node_modules\@project-serum\anchor\dist\cjs\error.js:36:20)
    at Object.rpc [as initializeConfig] (D:\NFT\metaplex\js\packages\cli\node_modules\@project-serum\anchor\dist\cjs\program\namespace\rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 102,
  msg: 'The program could not deserialize the given instruction'
}
(node:12112) UnhandledPromiseRejectionWarning: Error
    at Function.parse (D:\NFT\metaplex\js\packages\cli\node_modules\@project-serum\anchor\dist\cjs\error.js:36:20)
    at Object.rpc [as initializeConfig] (D:\NFT\metaplex\js\packages\cli\node_modules\@project-serum\anchor\dist\cjs\program\namespace\rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)        
(node:12112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by gkiri** [comment]
Anyone able to fix these errors?

**Comment by adigupta13** [comment]
Still getting same error

**Comment by arnaubennassar** [comment]
I'm getting same error as @Millali-Ilyas

**Comment by arnaubennassar** [comment]
@Millali-Ilyas I fixed the error by adding `symbol` on the JSON... make sure you're JSONs are correct, it may solve the issue

**Comment by jordansexton** [comment]
Thanks @Happyprince65. Can you say more about the steps you're taking to reproduce this issue?

**Comment by ReDey3** [comment]
anyone has the solution for this thing?

**Comment by samuelvanderwaal** [comment]
Custom program error 0x139 is:

```bash
0x139: 
	NFT Candy Machine         |	ConfigLineMismatch: Number of config lines must be at least number of items available
```

Common sources of error:

* Issue with the JSON file
* Issue with the number of assets uploaded versus number specified via command line option `-n`
* Issue with asset numbering leading to number mismatches

Things to try:

* Validate JSON files, run verify, fix any errors that are identified and run upload again
* If you've created your candy machine config account with the wrong number of items you may have to try again with a fresh cache and run upload again
