### ISSUE TITLE
candy machine set_start_date not working based on doc

### ISSUE THREAD

**Issue by f4xxf4xx** [metaplex-foundation/metaplex#306]
Trying to use the set_start_date, looking at the command docs, it says
```
% metaplex help set_start_date                                                         
Usage: cli set_start_date [options]
Options:
  -k, --keypair <path>     Solana wallet
  -c, --cache-name <path>  Cache file name
  -d, --date <string>      timestamp - eg "04 Dec 1995 00:12:00 GMT"
  -h, --help               display help for command
```
I would expect to be able to do something like 
` metaplex set_start_date -d "05 Sep 2021 18:00:00 GMT" -k ~/.config/solana/devnet.json`
But I am getting a very hard to interpret error message:

```
Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0xa1
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 2590 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0xa1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0xa1
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as updateCandyMachine] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0xa1',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 2590 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0xa1'
  ]
}
(node:10321) UnhandledPromiseRejectionWarning: Error
    at Function.parse (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/error.js:36:20)
    at Object.rpc [as updateCandyMachine] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:10321) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10321) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by f4xxf4xx** [comment]
It seems like using `create_candy_machine` makes set_start_time work, although i'm not sure what `create_candy_machine` actually does.

**Comment by jordansexton** [comment]
Looks like this was an issue of `set_start_date` vs `set_start_time` but please comment if the issue isn't fixed.
