### ISSUE TITLE
metaplex upload cli

### ISSUE THREAD

**Issue by mihaiserban** [metaplex-foundation/metaplex#351]
After uploading 6666 assets, fails to write indices.

command:
`metaplex upload ./assets -k /Users/mitzuuuu/.config/solana/mainnet.json -n 6666 -e 'mainnet-beta' -c "mainnet"`

result:
`
saving config line 5990-5999 failed Error: Invalid arguments: config not provided.
    at /snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/common.js:41:23
    at Array.forEach (<anonymous>)
    at Object.validateAccounts (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/common.js:33:16)
    at ix (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/instruction.js:14:22)
    at txFn (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/transaction.js:13:20)
    at Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:8:24)
    at /snapshot/js/packages/cli/build/cli.js:302:76
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.throw (/snapshot/js/packages/cli/build/cli.js:45:53)
    at rejected (/snapshot/js/packages/cli/build/cli.js:37:65)
`

**Comment by mihaiserban** [comment]
initializing config failes, no program set in .cache folder. Maybe upload should not proceed if no program is initialized?

`Processing file: 0
initializing config
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1 
    Program 11111111111111111111111111111111 invoke [1]
    Transfer: insufficient lamports 4936988821, need 11143356720
    Program 11111111111111111111111111111111 failed: custom program error: 0x1
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as initializeConfig] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 4936988821, need 11143356720',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
}
Error deploying config to Solana network. SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as initializeConfig] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Transfer: insufficient lamports 4936988821, need 11143356720',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x1'
  ]
}
Started awaiting confirmation for 2qTG7aYSZMSjPZd25FTv9jbrmvAzcJD9Kn6U8JWMgPEYwoR9eharQcC64MT3zXexz8sWg1dwEq8TwByD4tYdgM6b
REST null result for 2qTG7aYSZMSjPZd25FTv9jbrmvAzcJD9Kn6U8JWMgPEYwoR9eharQcC64MT3zXexz8sWg1dwEq8TwByD4tYdgM6b null
REST null result for 2qTG7aYSZMSjPZd25FTv9jbrmvAzcJD9Kn6U8JWMgPEYwoR9eharQcC64MT3zXexz8sWg1dwEq8TwByD4tYdgM6b null
REST no confirmations for 2qTG7aYSZMSjPZd25FTv9jbrmvAzcJD9Kn6U8JWMgPEYwoR9eharQcC64MT3zXexz8sWg1dwEq8TwByD4tYdgM6b {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: null,
  slot: 95766624,
  status: { Ok: null }
}
`

**Comment by Br4ndonP0nce** [comment]
How did you initialize configs then?
