### ISSUE TITLE
Error deploying config to Solana network. Error: Non-base58 character

### ISSUE THREAD

**Issue by ohaddahan** [metaplex-foundation/metaplex#355]
I followed this [guide](https://hackmd.io/@levicook/HJcDneEWF) and used the [sample json](https://docs.metaplex.com/nft-standard#json-structure) just to see how it works quick and dirty.
Got the error below, it was fixed then I changed the `creators address` to my `solana address`.

This issue is an FYI for others and a better error message might be needed here also, I'll try and create PR later.

```
Error deploying config to Solana network. Error: Non-base58 character
    at Object.decode (/snapshot/js/node_modules/base-x/src/index.js:115:11)
    at new PublicKey (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:135:50)
    at /snapshot/js/packages/cli/build/cli.js:210:42
    at Array.map (<anonymous>)
    at /snapshot/js/packages/cli/build/cli.js:208:64
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.next (/snapshot/js/packages/cli/build/cli.js:45:53)
    at fulfilled (/snapshot/js/packages/cli/build/cli.js:36:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Writing indices 0-0
saving config line 0-0 failed Error: Invalid arguments: config not provided.
    at /snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/common.js:41:23
    at Array.forEach (<anonymous>)
    at Object.validateAccounts (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/common.js:33:16)
    at ix (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/instruction.js:14:22)
    at txFn (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/transaction.js:13:20)
    at Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:8:24)
    at /snapshot/js/packages/cli/build/cli.js:302:76
    at step (/snapshot/js/packages/cli/build/cli.js:64:23)
    at Object.next (/snapshot/js/packages/cli/build/cli.js:45:53)
    at /snapshot/js/packages/cli/build/cli.js:39:71
Done. Successful = false. If 'false' - rerun
```

**Comment by ParmuSingh** [comment]
if you're using devnet, remove .cache folder where you ran metaplex upload before to fix this.

**Comment by jordansexton** [comment]
Thanks for noting what worked for you. Closing this as it doesn't seem actionable now, but hopefully it will help anyone who comes along. A PR to improve the error or docs would be awesome though.
