### ISSUE TITLE
Index greater than length when running metaplex upload on devnet

### ISSUE THREAD

**Issue by kevinfaveri** [metaplex-foundation/metaplex#359]
after running megaplex upload (`metaplex upload ./nfts --env devnet --keypair ~/.config/solana/devnet.json`) I get an error like that (it is only 1 nft, basically a 1.png and 1.json file inside this folder):

```bash
File uploaded: arweurl
setting cache for  1
Writing indices 1-1
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x12f 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x12f
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 6519 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x12f
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x12f
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x12f',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 6519 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x12f'
  ]
}
saving config line 1-1 failed ProgramError
    at Function.parse (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/error.js:31:20)
    at Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 303,
  msg: 'Index greater than length!'
}
Done. Successful = false. If 'false' - rerun
```

It seems like the file is correctly uploaded but this transaction simulation fails.

**Comment by kevinfaveri** [comment]
I was starting with 1.png. It needs to start with 0.png. Closed.

**Comment by zarifaziz** [comment]
how did you make the code start from 0?
