### ISSUE TITLE
 findDOMNode is deprecated in StrictMode. | Webapp, cant select NFT to sell

### ISSUE THREAD

**Issue by uaktags** [metaplex-foundation/metaplex#393]
When attempting to go to https://<url>/#/auction/create/1 and clicking "Add an NFT" you're presented with a blank selection modal and the console says the following error:
```
react-dom.development.js?a814:67 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at DomWrapper (webpack-internal:///../../node_modules/rc-motion/es/DomWrapper.js:20:87)
    at eval (webpack-internal:///../../node_modules/rc-motion/es/CSSMotion.js:53:32)
    at Mask (webpack-internal:///../../node_modules/rc-dialog/es/Dialog/Mask.js:18:25)
    at div
    at Dialog (webpack-internal:///../../node_modules/rc-dialog/es/Dialog/index.js:31:32)
    at eval (webpack-internal:///../../node_modules/rc-util/es/Portal.js:11:25)
    at PortalWrapper (webpack-internal:///../../node_modules/rc-util/es/PortalWrapper.js:79:87)
    at DialogWrap (webpack-internal:///../../node_modules/rc-dialog/es/DialogWrap.js:23:23)
    at Modal (webpack-internal:///../../node_modules/antd/es/modal/Modal.js:73:62)
    at ArtSelector (webpack-internal:///./src/views/auctionCreate/artSelector.tsx:31:5)
    at div
    at eval (webpack-internal:///../../node_modules/antd/es/grid/col.js:49:62)
    at div
    at eval (webpack-internal:///../../node_modules/antd/es/grid/row.js:45:34)
    at CopiesStep (webpack-internal:///./src/views/auctionCreate/index.tsx:716:13)
    at div
    at eval (webpack-internal:///../../node_modules/antd/es/grid/col.js:49:62)
    at div
    at eval (webpack-internal:///../../node_modules/antd/es/grid/row.js:45:34)
    at AuctionCreateView (webpack-internal:///./src/views/auctionCreate/index.tsx:97:83)
    at component
    at Route (webpack-internal:///../../node_modules/react-router/esm/react-router.js:466:29)
    at Switch (webpack-internal:///../../node_modules/react-router/esm/react-router.js:672:29)
    at main
    at Basic (webpack-internal:///../../node_modules/antd/es/layout/layout.js:72:25)
    at Adapter (webpack-internal:///../../node_modules/antd/es/layout/layout.js:55:66)
    at section
    at BasicLayout (webpack-internal:///../../node_modules/antd/es/layout/layout.js:87:63)
    at Adapter (webpack-internal:///../../node_modules/antd/es/layout/layout.js:55:66)
    at eval (webpack-internal:///./src/components/Layout/index.tsx:40:61)
    at ConfettiProvider (webpack-internal:///./src/components/Confetti/index.tsx:25:3)
    at MetaProvider (webpack-internal:///./src/contexts/meta/meta.tsx:67:3)
    at StoreProvider (webpack-internal:///../common/dist/lib/contexts/store.js:27:26)
    at CoingeckoProvider (webpack-internal:///./src/contexts/coingecko.tsx:35:3)
    at AccountsProvider (webpack-internal:///../common/dist/lib/contexts/accounts.js:313:29)
    at Or (webpack-internal:///../../node_modules/use-wallet/dist/index-d3bd4678.js:39:87863)
    at eval (webpack-internal:///../../node_modules/use-wallet/dist/index-d3bd4678.js:39:11985)
    at Pr
    at WalletModalProvider (webpack-internal:///../common/dist/lib/contexts/wallet.js:85:32)
    at WalletProvider (webpack-internal:///../../node_modules/@solana/wallet-adapter-react/lib/WalletProvider.js:25:27)
    at WalletProvider (webpack-internal:///../common/dist/lib/contexts/wallet.js:118:27)
    at ConnectionProvider (webpack-internal:///../common/dist/lib/contexts/connection.js:66:31)
    at Providers (webpack-internal:///./src/providers.tsx:25:3)
    at Router (webpack-internal:///../../node_modules/react-router/esm/react-router.js:95:30)
    at HashRouter (webpack-internal:///../../node_modules/react-router-dom/esm/react-router-dom.js:107:35)
    at Routes
    at App
    at LoadableComponent (webpack-internal:///../../node_modules/next/dist/next-server/lib/loadable.js:122:36)
    at App
    at div
    at App (webpack-internal:///./src/pages/_app.tsx:25:3)
    at ErrorBoundary (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:26:47)
    at ReactDevOverlay (webpack-internal:///../../node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:86:23)
    at Container (webpack-internal:///../../node_modules/next/dist/client/index.js:125:1)
    at AppContainer (webpack-internal:///../../node_modules/next/dist/client/index.js:484:3)
    at Root (webpack-internal:///../../node_modules/next/dist/client/index.js:611:3)
    ```

**Comment by lz2470** [comment]
Face same issue here. I already add creator of candy machine and creator in the metadata to the store
