### ISSUE TITLE
Metaplex upload REST null result (mainnet-beta)

### ISSUE THREAD

**Issue by adrzadrz** [metaplex-foundation/metaplex#401]
I started the upload yesterday evening to upload 5000 images:
`metaplex upload ./temp --env mainnet-beta --keypair ~/.config/solana/wallet1.json`
It seems to have worked for the first 3000s images, but it failed with this error
```
Processing file: 3703
Started awaiting confirmation for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
REST null result for Ro8RnL5CHSzBgjUTYc12nFpgve3mKbQHSLuY6jXZvbYepvnAfiuWzRgAoPiGTiBKZAemJXmBFwFQbjmr6giHiAC null
Rejecting for timeout...
Timeout Error caught { timeout: true }
(node:12704) UnhandledPromiseRejectionWarning: Error: Timed out awaiting confirmation on transaction
    at C:\snapshot\js\packages\cli\build\helpers\transactions.js:162:31
    at step (C:\snapshot\js\packages\cli\build\helpers\transactions.js:33:23)
    at Object.throw (C:\snapshot\js\packages\cli\build\helpers\transactions.js:14:53)
    at rejected (C:\snapshot\js\packages\cli\build\helpers\transactions.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:12704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

And now when I'm running
`metaplex verify --env mainnet-beta --keypair ~/.config/solana/wallet1.json`
 I'm getting errors for every single entries. 

```
...
Looking at key  3002
Name  or uri  didnt match cache values of [redacted]#3700 and https://arweave.net/[redacted]  marking to rerun for image 3699
Looking at key  3003
Name  or uri  didnt match cache values of [redacted]#3701 and https://arweave.net/[redacted] marking to rerun for image 3700
...
```

Thanks for your help

**Comment by richardj97** [comment]
Have you managed to sort it?

**Comment by adrzadrz** [comment]
No. I'm currently retrying to upload everything on devnet, to see if it still blocks at file #3703. If it does, I'll know there might be a problem with the file or json. If it doesn't, hopefullly someone knows what's happening :/

**Comment by adrzadrz** [comment]
@richardj97  might have found something: https://twitter.com/solanastatus/status/1437757547235131396?s=21&fbclid=IwAR3dgHelVRSJEa8SgmdjlG8C4dtYgFyrT25jekozfCgvDDa2JIc4BjKMjFA

**Comment by richardj97** [comment]
> @richardj97 might have found something: https://twitter.com/solanastatus/status/1437757547235131396?s=21&fbclid=IwAR3dgHelVRSJEa8SgmdjlG8C4dtYgFyrT25jekozfCgvDDa2JIc4BjKMjFA

That has to be the issue... everything works with devnet etc

**Comment by adrzadrz** [comment]
Yup same here. It works with devnet. Hopefully they fix this soon. At least now it's out of our hands

**Comment by fieldpalmer** [comment]
Was that the issue or have you got it sorted? I'm still getting the same error on testnet and devnet

**Comment by brightlkms** [comment]
same error right now
