### ISSUE TITLE
Error: Invalid arguments: config not provided.

### ISSUE THREAD

**Issue by achiko** [metaplex-foundation/metaplex#421]
```
Error: Invalid arguments: config not provided.
    at ./metaplex/js/node_modules/@project-serum/anchor/dist/cjs/program/common.js:41:23
    at Array.forEach (<anonymous>)
    at Object.validateAccounts (./metaplex/js/node_modules/@project-serum/anchor/dist/cjs/program/common.js:33:16)
    at ix (./metaplex/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/instruction.js:14:22)
    at txFn (./metaplex/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/transaction.js:13:20)
    at Object.rpc [as addConfigLines] (./metaplex/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:8:24)
    at ./metaplex/js/packages/cli/build/cli.js:465:76
    at step (./metaplex/js/packages/cli/build/cli.js:64:23)
    at Object.next (./metaplex/js/packages/cli/build/cli.js:45:53)
    at ./metaplex/js/packages/cli/build/cli.js:39:71
```

**Comment by BurgercubeNFT** [comment]
All metaplex commands should run from directory where ".cache" folder is stored. In other world from the same directory where you were run metaplex_upload command.

**Comment by spaceseedtoken** [comment]
> All metaplex commands should run from directory where ".cache" folder is stored. In other world from the same directory where you were run metaplex_upload command.

what is supposed to be in the cache files, mine is empty and it seems it's causing issues
