### ISSUE TITLE
Error uploading files using CLI

### ISSUE THREAD

**Issue by arnaubennassar** [metaplex-foundation/metaplex#486]
I've been trying to use the candy machine CLI without success. After having issues related to installing and building, I've decided to use Docker to have a clean and easy to reproduce setup. So here is what I did:

1. Build the container: `docker build . -t candy-machine`. Dockerfile is:
```dockerfile
FROM node:14

RUN git clone https://github.com/metaplex-foundation/metaplex.git
RUN cd metaplex/js/packages/cli && yarn
RUN cd metaplex/js/packages/cli && yarn build
RUN cd metaplex/js/packages/cli && yarn run package:linuxb
RUN cd metaplex/js/packages/cli && cp bin/linux/metaplex /bin

ENTRYPOINT [ "/bin/bash" ]
```
2. Go inside the container with private key and metadata attached: `docker run -it -v $(pwd)/metadata:/metadata -v ~/.config/solana/id.json:/id.json candy-machine`
3. (Inside the container) Upload images `metaplex upload /metadata --keypair /id.json -e devnet`

And then I'm stuck with this error, which is actually the same error I was having outside of Docker:

```
root@9c0e61d733e8:/# metaplex upload /metadata --keypair /id.json -e devnet
Beginning the upload for 6 (png+json) pairs
started at: 1632478573183
wallet public key: *******************************************************
Processing file: 0
initializing config
Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x66
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 4290 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x66
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0x66
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as initializeConfig] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x66',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 4290 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x66'
  ]
}
Error deploying config to Solana network. ProgramError
    at Function.parse (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/error.js:36:20)
    at Object.rpc [as initializeConfig] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 102,
  msg: 'The program could not deserialize the given instruction'
}
(node:7) UnhandledPromiseRejectionWarning: Error
    at Function.parse (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/error.js:36:20)
    at Object.rpc [as initializeConfig] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea on how to overcome this error?

**Comment by arnaubennassar** [comment]
Found the error, I was missing the `symbol` on the JSONs

**Comment by cdric** [comment]
I ran into the same issue. Glad to know that the "symbol" was the cause of the problem.
Out of curiosity, does the symbol value really matter if you create a new NFT collection and don't plan on using it? 
If so, how can you make sure that you use a symbol that is unique to your collection?

**Comment by jordansexton** [comment]
Just noting, it looks like https://github.com/metaplex-foundation/metaplex/issues/690 is related.

Can this be closed? It sounds like the issue was resolved.
