### ISSUE TITLE
CLI error loop

### ISSUE THREAD

**Issue by EON-II** [metaplex-foundation/metaplex#494]
Done. Successful = false.
upload was not successful, rerunning
wallet public key: 3xDnddoHG2XyRaBN6wS2DTmBuahPYcYhhfRwrvNRtMDE
Processing file: 0
Processing file: 50
Processing file: 100
Processing file: 150
Writing indices 191-200
Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [
    1
]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 48491 out of range for slice of length 48280', nft-candy-machine/src/lib.rs: 318: 18
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js: 4863: 13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js: 95: 5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js: 4822: 20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js: 6649: 21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js: 84: 22)
    at async Object.rpc [as addConfigLines
] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js: 11: 31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [
            1
        ]',
    'Program log: libstd rust_begin_panic',
        "Program log: panicked at 'range end index 48491 out of range for slice of length 48280', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
    ]
}
saving config line 191-200 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js: 4863: 13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js: 95: 5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js: 4822: 20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js: 6649: 21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js: 84: 22)
    at async Object.rpc [as addConfigLines
] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js: 11: 31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [
            1
        ]',
    'Program log: libstd rust_begin_panic',
        "Program log: panicked at 'range end index 48491 out of range for slice of length 48280', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
    ]
}

I've seen a few others with this same issue, wondering if there was a solution!

**Comment by EON-II** [comment]
Also, this error only happens with indices 191-200, all other ones prior process/write just fine

**Comment by FoxelFox** [comment]
i get the same error

**Comment by EON-II** [comment]
for anyone else wondering, BE SURE you're starting with a 0.png and 0.json file, that completely fixed it for me
