### ISSUE TITLE
Verify error: Error: not all NFTs checked out.

### ISSUE THREAD

**Issue by Dressi123** [metaplex-foundation/metaplex#514]
hello, I'm trying to verify my upload but I get this error every time.
this is my JSON file for one of my nfts. 
```
{
  "name": "Solflare X NFT",
  "symbol": "sft",
  "description": "Celebratory Solflare NFT for the Solflare X launch",
  "seller_fee_basis_points": 0,
  "image": "image.png",
  "animation_url": "",
  "external_url": "",
  "attributes": [
    {
      "trait_type": "web",
      "value": "yes"
    },
    {
      "trait_type": "mobile",
      "value": "yes"
   },
   {
      "trait_type": "extension",
      "value": "yes"
    }
  ],
  "collection": {
     "name": "Solflare X NFT",
     "family": "Solflare" 
  },
  "properties": {
    "files": [
      {
        "uri": "image.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "EmhPP1HLx9UT7Mx6hv2VNXayqArPvvkJThE2pZ9DXd4m",
        "share": 100
      }
    ]
  }
}
```
im using this command to upload with: `metaplex upload ./assets --env devnet --keypair /Users/andreas/Desktop/Crypto/nft/solanaWallet/test-wallet-keypair-01.json`
it prints this response:
```
Beginning the upload for 1 (png+json) pairs
started at: 1632681780461
wallet public key: EmhPP1HLx9UT7Mx6hv2VNXayqArPvvkJThE2pZ9DXd4m
Processing file: 0
Writing indices 0-0
Done. Successful = true.
ended at: 2021-09-26T18:43:15.306Z. time taken: 00:00:14
```
but when I try to run the verify command: `metaplex verify -k /Users/andreas/Desktop/Crypto/nft/solanaWallet/test-wallet-keypair-01.json`
it prints this response

```
wallet public key: EmhPP1HLx9UT7Mx6hv2VNXayqArPvvkJThE2pZ9DXd4m
(node:34983) UnhandledPromiseRejectionWarning: Error: not all NFTs checked out. check out logs above for details
    at /snapshot/js/packages/cli/build/candy-machine-cli.js:267:27
    at step (/snapshot/js/packages/cli/build/candy-machine-cli.js:53:23)
    at Object.next (/snapshot/js/packages/cli/build/candy-machine-cli.js:34:53)
    at fulfilled (/snapshot/js/packages/cli/build/candy-machine-cli.js:25:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:34983) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:34983) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
hope somebody can help me :)

**Comment by thecookingsenpai** [comment]
Same to me. Has the upload command executed successfully? Mine is stuck at `ended at: 2021-09-27T08:53:22.809Z. time taken: 04:16:53` . I left the process open in a screen and tried to verify, same error. Actually, on htop i can see the process writing something, also strace shows it is working on something. I guess I will wait a little but makes no sense to me

**Comment by alexander-io** [comment]
I'm also having this issue

**Comment by mustafatalha** [comment]
I'am also having too. I think this is about arweave shows metadata but not image. Image links on arweave return "Not Found".

Because of that, verify method aborts.
