### ISSUE TITLE
panicked at 'range end index 971 out of range for slice of length 736'

### ISSUE THREAD

**Issue by SethCalkins** [metaplex-foundation/metaplex#527]
### Running command
`metaplex upload ./assets --env devnet --keypair ~/.config/solana/devnet.json`
### Attempting to run metaplex upload and receiving the following error:
```Beginning the upload for 1 (png+json) pairs
started at: 1632778292633
wallet public key: EC84npQQBQza9QsAXNWEnKFwKQDH8kpvtttaDhkNGFvb
Processing file: 0
Writing indices 0-2
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 971 out of range for slice of length 736', nft-candy-machine/src/lib.rs:318:18
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/cli/node_modules/@solana/web3.js/lib/index.cjs.js:4964:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/cli/node_modules/@solana/web3.js/lib/index.cjs.js:4923:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/cli/node_modules/@solana/web3.js/lib/index.cjs.js:6907:21)
    at async Provider.send (/snapshot/cli/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/cli/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 971 out of range for slice of length 736', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
saving config line 0-2 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/cli/node_modules/@solana/web3.js/lib/index.cjs.js:4964:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/cli/node_modules/@solana/web3.js/lib/index.cjs.js:4923:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/cli/node_modules/@solana/web3.js/lib/index.cjs.js:6907:21)
    at async Provider.send (/snapshot/cli/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/cli/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 971 out of range for slice of length 736', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
Done. Successful = false.
upload was not successful, rerunning
```

### Using the following JSON Code as test
```json
{
  "name": "Solflare X NFT",
  "symbol": "TEST",
  "description": "Celebratory Solflare NFT for the Solflare X launch",
  "seller_fee_basis_points": 0,
  "image": "image.png",
  "animation_url": "",
  "external_url": "",
  "attributes": [
    {
      "trait_type": "web",
      "value": "yes"
    },
    {
      "trait_type": "mobile",
      "value": "yes"
   },
   {
      "trait_type": "extension",
      "value": "yes"
    }
  ],
  "collection": {
     "name": "Solflare X NFT",
     "family": "Solflare" 
  },
  "properties": {
    "files": [
      {
        "uri": "image.png",
        "type": "image/png"
      }
    ],
    "category": "image",
    "creators": [
      {
        "address": "EC84npQQBQza9QsAXNWEnKFwKQDH8kpvtttaDhkNGFvb",
        "share": 100
      }
    ]
  }
}
```

`metaplex --version`
0.0.2
`node --version`
v14.17.6

**Comment by saraspaudel** [comment]
Same as https://github.com/metaplex-foundation/metaplex/issues/518

**Comment by SethCalkins** [comment]
> Same as #518

for anyone else wondering, BE SURE you're starting with a 0.png and 0.json file, that completely fixed it for me

_Originally posted by @EON-II in https://github.com/metaplex-foundation/metaplex/issues/494#issuecomment-927235861_

Issue could be different, my JSON / Images start with 0.png 
Have you tried this?

**Comment by saraspaudel** [comment]
+1 @SethCalkins

**Comment by saraspaudel** [comment]
Tried with `-c temp2` and it works

**Comment by uaktags** [comment]
@saraspaudel ``-c temp2`` would just be using a new temp file, completely starting from the beginning. By default, you shouldn't NEED to change your cache filename. If you're going to do that, might as well just delete your original cache file  ``.cache/devnet-temp``.

@SethCalkins the 0.png vs image.png doesn't matter either. the upload.ts will search the metadata's json for "image.png" and will do a string replace for it to be <index>.png.
So 0.json can list "image.png" all day long. The actual png file though needs to be 0.png.
To visualize what is valid:

```
$ ls assets/
0.png 0.json
$ cat 0.json | grep image.
"image": "image.png",
"uri": "image.png",
$
```
as well as
```
$ ls assets/
0.png 0.json
$ cat 0.json | grep image.
"image": "0.png",
"uri": "0.png",
$
```

Both are valid, so your original JSON, atleast to that comments point, is completely valid.



Doesn't really help you with the error, but figured FYI.
For curiosity, can you try the following:
Remove all but 0.png/0.json from assets.
Delete your .cache/devnet-temp file
rerun the upload.
If successful, move 1.png/1.json to the assets folder (keep 0.png/0.json), and rerun the upload.
If failed, what's the failing file's filesize and can you provide what ```file``` output. Similar to this:
```$ file 2.png
2.png: PNG image data, 720 x 720, 8-bit/color RGB, non-interlaced
```

**Comment by patchmix** [comment]
also able to experience this issue,  no luck in removing files
