### ISSUE TITLE
'A raw constraint was violated' when running create_candy_machine on mainnet

### ISSUE THREAD

**Issue by grimAgent** [metaplex-foundation/metaplex#535]
I'm running this command: `ts-node ~/metaplex/js/packages/cli/src/candy-machine-cli.ts create_candy_machine --price 0.1 --sol-treasury-account redacted_treasury_wallet --env mainnet-beta`

And getting back this error:

```
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8f 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x8f
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 19712 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8f
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8f
    at Connection.sendEncodedTransaction (/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3648:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Connection.sendRawTransaction (/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3608:20)
    at async Object.sendAndConfirmRawTransaction (/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x8f',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 19712 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8f'
  ]
}
/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/error.ts:36
      return new ProgramError(errorCode, errorMsg);
             ^
ProgramError: 
    at Function.parse (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as initializeCandyMachine] (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 143,
  msg: 'A raw constraint was violated'
}
```

This is my metadata:
```json
{
    "name": "Name",
    "symbol": "Symbol",
    "description": "Description",
    "seller_fee_basis_points": 500,
    "image": "0.png",
    "external_url": "https://site.com",
    "attributes": [
        {
            "trait_type": "ID",
            "value": 0
        }
    ],
    "collection": {
        "name": "Name",
        "family": "Name"
    },
    "properties": {
        "files": [
            {
                "uri": "0.png",
                "type": "image/png"
            }
        ],
        "creators": [
            {
                "address": "redacted_minting_authority_wallet (the one running the commands)",
                "share": 1
            },
            {
                "address": "redacted_treasury_wallet",
                "share": 66
            },
            {
                "address": "redacted_another_creator_wallet",
                "share": 33
            }
        ]
    }
}
```

Any ideas what might be wrong???

**Comment by richard-fisher** [comment]
The wallet address that receives the mint funds has to have a balance > 0. It’s a constraint in candy machine that I assume is to ensure it’s a real address

**Comment by Ru5ty0ne** [comment]
> 
> 
> Thanks for answering @richard-fisher. @grimAgent, did this resolve the issue for you?

I had same issue and it was resolved by funding treasury account
