### ISSUE TITLE
Error uploading candy machine: encoding overruns Buffer

### ISSUE THREAD

**Issue by the-wuh** [metaplex-foundation/metaplex#541]
When I to upload assets less than 10 (indices 0-9) it fails but it successfully uploads when it is more than but if it is less than 10, it uploads successfully.
Say I was to upload 15:
0-9 will fail
10-14 will upload successfully to chain
and so I get this error in a loop
```
Processing file: 0
Writing indices 0-9
saving config line 0-9 failed RangeError: encoding overruns Buffer
    at Blob.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:2334:13)
    at Structure.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1272:26)
    at WrappedLayout.encode (/snapshot/js/node_modules/@project-serum/borsh/dist/lib/index.js:65:28)
    at WrappedLayout.encode (/snapshot/js/node_modules/@project-serum/borsh/dist/lib/index.js:65:28)
    at Structure.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1272:26)
    at /snapshot/js/node_modules/buffer-layout/lib/Layout.js:1117:25
    at Array.reduce (<anonymous>)
    at Sequence.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1116:22)
    at Structure.encode (/snapshot/js/node_modules/buffer-layout/lib/Layout.js:1272:26)
    at WrappedLayout.encode (/snapshot/js/node_modules/@project-serum/borsh/dist/lib/index.js:65:28)
Done. Successful = false.
upload was not successful, rerunning

```

**Comment by ciumexan** [comment]
weird...
I cannot get over the data =. null error. 
Can you share your NFT json (obfuscate wallet and sensitive strings)?

**Comment by the-wuh** [comment]
I got it to work. I had to reduce the number of characters in the string for the ```"name"``` value in my json. It has not thrown the error since then. Is there a limit to the number of characters the string can contain for the ```"name"``` value?

**Comment by lisncruhs** [comment]
@the-wuh Everything has been uploaded to arweave, but I'm getting this same error. Do you think shortening the name string in the mainnet-beta-temp file would fix this? Any idea whether it would break anything?
