### ISSUE TITLE
Error updating Candy Machine: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dex2code** [metaplex-foundation/metaplex#546]
$alias metaplex='ts-node ~/.jsapps/metaplex-cli/js/packages/cli/src/candy-machine-cli.ts'
$ metaplex update_candy_machine --env devnet --keypair ~/.config/solana/minter.json --price 0.01 --date "29 Sep 2021 15:20:00 GMT"
wallet public key: BYss9ph23s1GJiJHtj52VrJaxRMPeYtLwuA9Q2ovJ3zQ
(node:9301) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_bn' of undefined
    at isPublicKeyData (/home/mint/.jsapps/metaplex-cli/js/node_modules/@solana/web3.js/src/publickey.ts:29:35)
    at new PublicKey (/home/mint/.jsapps/metaplex-cli/js/node_modules/@solana/web3.js/src/publickey.ts:45:9)
    at /home/mint/.jsapps/metaplex-cli/js/packages/cli/src/candy-machine-cli.ts:560:26
    at step (/home/mint/.jsapps/metaplex-cli/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/home/mint/.jsapps/metaplex-cli/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/home/mint/.jsapps/metaplex-cli/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9301) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kevinfaveri** [comment]
what was the problem here? @dex2code

**Comment by ciumexan** [comment]
Hello I have the same issue. Can you help solving this. ?
