### ISSUE TITLE
Cannot upload at all with Metaplex. Can you advise on what to do?

### ISSUE THREAD

**Issue by ciumexan** [metaplex-foundation/metaplex#555]
**Node version**: 
`v14.17.0`
**Metaplex**: 
`0.0.1`
**ts-node version**:
`v10.2.1`

executing upload with: 
`metaplex upload ./assets --env devnet -k /fullpath/wallet_test_net.json`

I get this error: 
```
Beginning the upload for 10 (png+json) pairs
started at: 1632983381751
(node:13182) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token } in JSON at position 185
    at JSON.parse (<anonymous>)
    at Object.loadCache (/snapshot/js/packages/cli/build/helpers/cache.js:19:16)
    at Object.<anonymous> (/snapshot/js/packages/cli/build/commands/upload.js:94:44)
    at step (/snapshot/js/packages/cli/build/commands/upload.js:63:23)
    at Object.next (/snapshot/js/packages/cli/build/commands/upload.js:44:53)
    at /snapshot/js/packages/cli/build/commands/upload.js:38:71
    at new Promise (<anonymous>)
    at /snapshot/js/packages/cli/build/commands/upload.js:34:12
    at Object.upload (/snapshot/js/packages/cli/build/commands/upload.js:87:12)
    at /snapshot/js/packages/cli/build/cli.js:133:51
```
```
(Use "metaplex --trace-warnings ..." to show where the warning was created)
(node:13182) `UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`
(node:13182) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**This is my NFT JSON (started with 0.json and 0.png)**

```
{
	"name": "ART #0000",
	"symbol": "",
	"description": "Here is test 1",
	"seller_fee_basis_points": 1000,
	"image": "image.png",
	"external_url": "https://solflare.com",
	"animation_url": "",
	"collection": {
		"name": "X NFT",
		"family": "X NFT"
	},
	"properties": {
		"files": [
			{
				"uri": "image.png",
				"type": "image/png"
			}
		],
		"category": "image",
		"creators": [
			{
				"address": "GhCBk21LbJgxE9JatYLk65E4hULkYn28pZQ4GY3VXwrF",
				"share": 250
			}
		]
	},
	"attributes": [
		{
			"trait_type": "Background Color",
			"value": "palegreen"
		},
		{
			"trait_type": "Head Color",
			"value": "lightblue"
		},
		{
			"trait_type": "Neck Color",
			"value": "lightslategray"
		}
	]
}
```

**Comment by ciumexan** [comment]
with ts-node got this 
```
wallet public key: 5CQu...u4hLKgC
(node:14109) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of null
    at Function.fetchIdl (/Volumes/work/metaplex/js/node_modules/@project-serum/anchor/src/program/index.ts:311:51)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14109) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14109) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by jscrui** [comment]
You should pass a symbol.

**Comment by aheckmann** [comment]
Is this still reproducible? Let me know. If not, please close.
