### ISSUE TITLE
Error while running yarn run package:macos?

### ISSUE THREAD

**Issue by qualityrender** [metaplex-foundation/metaplex#560]
Hi, I am trying to put up a candy-machine for myself and have a problem with metaplex:

1. I go to cd Metaplex / js / packages / cli
2.  run yarn install
3. run yarn build
4. then yarn run package:macos I get this 

`➜  cli git:(master) ✗ yarn run package:macos
yarn run v1.22.11
$ pkg . --targets node14-macos-x64 --output bin/macos/metaplex
> pkg@5.3.1
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/fetch.js
prebuild-install WARN install No prebuilt binaries found (target=v14.17.2 runtime=node arch=x64 libc= platform=darwin)
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Body.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Fetch.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Headers.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Request.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Response.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/StreamArrayBufferResponse.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/StreamBlobResponse.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/utils.js
✨  Done in 18.26s.`

I have tried to use npx pkg . -d --targets node14-macos-x64 --output bin/macos/metaplex but still getting this erros

node version  v14.17.6
Git version 2.30.1 (Apple Git-130)
Yarn version 1.22.11

Any one have the same issue?

**Comment by uaktags** [comment]
These aren't errors, they're warnings. Check the bin/macos folder. It should have created just fine.

**Comment by qualityrender** [comment]
Ah alright that true thank you

**Comment by Brueni92** [comment]
When I try to then run `metaplex --version`, I get the following error:

```
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: dlopen(/var/folders/4d/c2dp505d6p9dhvqlpc4nxtbw0000gn/T/02eb951b494ee013e1c4a3f6028e87677a6db44e87325bd383df7c44ef81af45/canvas.node, 1): Library not loaded: @loader_path/librsvg-2.2.dylib
  Referenced from: /var/folders/4d/c2dp505d6p9dhvqlpc4nxtbw0000gn/T/02eb951b494ee013e1c4a3f6028e87677a6db44e87325bd383df7c44ef81af45/canvas.node
  Reason: image not found
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)
    at tryImporting (pkg/prelude/bootstrap.js:2080:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1154:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/snapshot/js/node_modules/canvas/lib/bindings.js:3:18) {
  code: 'ERR_DLOPEN_FAILED'
}
```

anyone seen that before?

**Comment by nikilunikos** [comment]
yes i have the same problem
two days ago everything was working but not today, will love to have clue

**Comment by mustafatalha** [comment]
Binary version has a problem, you can use directly from code. Check getting started on https://hackmd.io/@levicook/HJcDneEWF

ts-node .\candy-machine-cli.ts --version

**Comment by dobpp** [comment]
@mustafatalha Do you mean we can replicate all metaplex commands with candy-machine-cli command?

**Comment by catpower** [comment]
Is it fixed? Still having the same problem with latest code
