### ISSUE TITLE
I get this when I try to upload my assets why? ./assets --env devnet --keypair ~/.config/solana/devnet.json Error

### ISSUE THREAD

**Issue by qualityrender** [metaplex-foundation/metaplex#563]
➜  cli git:(master) ✗ metaplex upload ./assets --env devnet --keypair  ~/.config/solana/devnet.json   
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: dlopen(/var/folders/9r/v46rx_1x7mdgpx1pjfm4dpvm0000gn/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node, 1): Library not loaded: @loader_path/libpixman-1.0.40.0.dylib
  Referenced from: /var/folders/9r/v46rx_1x7mdgpx1pjfm4dpvm0000gn/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node
  Reason: image not found
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)
    at tryImporting (pkg/prelude/bootstrap.js:2080:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/js/node_modules/canvas/lib/bindings.js:3:18)

Yeah not sure what to do...

**Comment by ajobi-uhc** [comment]
try re-forking and rebuilding and installing all the packages. It seems to be a node/modules problem

**Comment by wandrzejczak** [comment]
I've the same problem. I've reinstalled all node_modules.

**Comment by nikilunikos** [comment]
to reinstall al node_modules you just have to delete then run yarn install ? Thanks

**Comment by nikilunikos** [comment]
I tried many times but nothing change, if you have other clue :)

**Comment by NailchikSam** [comment]
same problem. Pls can u tell me what command did u use

**Comment by mustafatalha** [comment]
Binary version has a problem, you can use directly from code. Check getting started on https://hackmd.io/@levicook/HJcDneEWF

ts-node .\candy-machine-cli.ts upload bla bla
