### ISSUE TITLE
Cannot read properties of undefined (reading '_bn') when use update_candy_machine 

### ISSUE THREAD

**Issue by AcoustiCoder** [metaplex-foundation/metaplex#564]
I upload my files succesfully. But when try update candy  machine i got this error.

`wallet public key: E9WnMXUvr1fWLCyVT6pVCSzDEXJQzuBdFHrsZXZkTo3e
/mnt/c/metap/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:29
  return (value as PublicKeyData)._bn !== undefined;
                                  ^
TypeError: Cannot read properties of undefined (reading '_bn')
    at isPublicKeyData (/mnt/c/metap/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:29:35)
    at new PublicKey (/mnt/c/metap/metaplex/js/node_modules/@solana/web3.js/src/publickey.ts:45:9)
    at /mnt/c/metap/metaplex/js/packages/cli/src/candy-machine-cli.ts:564:26
    at step (/mnt/c/metap/metaplex/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/mnt/c/metap/metaplex/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/mnt/c/metap/metaplex/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by qualityrender** [comment]
yeah I get the same problem, gone try to do a new fork and try the whole process again

**Comment by AcoustiCoder** [comment]
> yeah I get the same problem, gone try to do a new fork and try the whole process again

any progress? i tryed everything and still same..

**Comment by Nikola43** [comment]
you need set start date before update

**Comment by AcoustiCoder** [comment]
> you need set start date before update

i will try this thank you so much

**Comment by Hiyorimi** [comment]
doesn't work with any date `--date "03 Oct 2021 21:54:00 GMT"`  or `"now"`

Cloned master.

**Comment by AcoustiCoder** [comment]
> doesn't work with any date `--date "03 Oct 2021 21:54:00 GMT"` or `"now"`
> 
> Cloned master.

so we dont use date anymore?

**Comment by Hiyorimi** [comment]
> > doesn't work with any date `--date "03 Oct 2021 21:54:00 GMT"` or `"now"`
> > Cloned master.
> 
> so we dont use date anymore?

I changed `const candyMachine = new PublicKey(cacheContent.candyMachineAddress);`  to `const candyMachine = new PublicKey(cacheContent.program.config);` but got stuck with 0xa2 error.

**Comment by samuelrondot** [comment]
I have the same issue, how did you guys fixed this ?

**Comment by Znomon** [comment]
Dealing with the same issue. Anyone fix it? It appears to be having an issue reading cache

**Comment by nicojochnick** [comment]
I actually run into the issue when I call `create_candy_machine`, wondering if anyone has experienced the same?

**Comment by Moikapy** [comment]
Has this been resolved?

**Comment by add1ct3dd** [comment]
I am also getting this issue, and if I try create_candy_machine first I get 

```Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d```

**Comment by piscespieces** [comment]
Getting

```
Error deploying config to Solana network. TypeError: Cannot read properties of undefined (reading '_bn') at isPublicKeyData
```

When running the command that is in the docs
```ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts help upload```

**Comment by zkhalapyan** [comment]
@Znomon create_candy_machine actually needs to read in the .cache file; you will get the following error if you don't first upload your assets.

```
➜  burble git:(main) ✗ ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env devnet --keypair  ~/.config/solana/id.json
wallet public key: 6zsuBDfuvtxK5FD9tf8u8LfrYBVnxDWRhj43snmC6Qx6
/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:777
    const config = new PublicKey(cacheContent.program.config);
                                              ^
TypeError: Cannot read properties of undefined (reading 'program')
    at Command.<anonymous> (/Users/zkhalapyan/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts:777:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by lukedupin** [comment]
I was getting this error because one of my 0.json files's creators address field was invalid. After fixing the address field, everything began working.

**Comment by jignesh6990** [comment]
Tried to find the solution for this issue since last 3 nights but nothing works.
TypeError: Cannot read properties of undefined (reading '_bn')
    at isPublicKeyData (D:\Work\JP\lottery\metaplex\js\node_modules\@solana\web3.js\src\publickey.ts:35:35)
    at new PublicKey (D:\Work\JP\lottery\metaplex\js\node_modules\@solana\web3.js\src\publickey.ts:51:9)
    at getCandyMachineV2Config (D:\Work\JP\lottery\metaplex\js\packages\cli\src\helpers\various.ts:195:36)
    at Command.<anonymous> (D:\Work\JP\lottery\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:157:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

![Screenshot 2022-04-01 115856](https://user-images.githubusercontent.com/4235471/161208125-1ddba713-054c-4be0-876d-434cf8339723.jpg)

**Comment by Nigh7Sh4de** [comment]
I was running into this issue because I had misconfigured my `gatekeeper` in the *config.json*. To find the root cause, I edited *...\metaplex\js\node_modules\@solana\web3.js\lib\index.cjs.js* and added the following line to `function isPublicKeyData`:
```
if (!value) return false;
```

In my case this changed the error message to:
```
    gatekeeper.gatekeeperNetwork = new web3.PublicKey(
                                ^
TypeError: Cannot create property 'gatekeeperNetwork' on string 'ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6'
    at getCandyMachineV2Config (C:\Users\Dennis\github\metaplex\js\packages\cli\src\helpers\various.ts:195:33)
    at Command.<anonymous> (C:\Users\Dennis\github\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:157:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
````

Turns out I needed to set `gatekeeperNetwork` and `expireOnUse` on the root of my config.json instead of as properties of the `gatekeeper` on root (I really should get better at reading documentation):
```
"gatekeeper": {
  "gatekeeperNetwork": "ignREusXmGrscGNUesoU9mxfds9AiYTezUKex2PsZV6",
  "expireOnUse": true
},
```

**Comment by naftalimurgor** [comment]
Anyone ever resolved this issue? I'm running into a similar issue with Nextjs:
```sh
Server Error

TypeError: Cannot read properties of undefined (reading '_bn')
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source

pages/MintNFTs.js (15:30) @ MintNFTs

  13 | const [disableMint, setDisableMint] = useState(true);
  14 | 
> 15 | const candyMachineAddress = new PublicKey(
     |                            ^
  16 |   process.env.NEXT_PUBLIC_CANDY_MACHINE_ID
  17 | );
  18 | let candyMachine;
```

Any pointers on how to resolve this are highly appreciated :pray: 
Thanks!

**Comment by itachi47** [comment]
for me updating @solana/web3.js worked, `pnpm update @solana/web3.js`
