### ISSUE TITLE
Binary running error after package:linux in CLI (Ubuntu)

### ISSUE THREAD

**Issue by agmitron** [metaplex-foundation/metaplex#581]
I'm trying to build a binary package on Ubuntu linux and create a candy machine. 

```bash
alek@nortimg:~/Code/metaplex/js/packages/cli$ yarn build
yarn run v1.22.11
$ tsc -p ./src
Done in 9.28s.


alek@nortimg:~/Code/metaplex/js/packages/cli$ yarn run package:linux
yarn run v1.22.11
$ pkg . --no-bytecode --targets node14-linux-x64 --output bin/linux/metaplex
> pkg@5.3.1
> Error! --no-bytecode and no source breaks final executable
  /home/alek/Code/metaplex/js/node_modules/rpc-websockets/dist/index.js
  Please run with "-d" and without "--no-bytecode" first, and make
  sure that debug log does not contain "was included as bytecode".
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
alek@nortimg:~/Code/metaplex/js/packages/cli$ yarn run package:linuxb
yarn run v1.22.11
$ pkg . --targets node14-linux-x64 --output bin/linux/metaplex
> pkg@5.3.1
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/fetch.js
prebuild-install WARN install No prebuilt binaries found (target=v14.17.2 runtime=node arch=x64 libc= platform=linux)
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Body.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Fetch.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Headers.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Request.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/Response.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/StreamArrayBufferResponse.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/StreamBlobResponse.js
> Warning Failed to make bytecode node14-x64 for file /snapshot/js/node_modules/react-native-fetch-api/src/utils.js
Done in 11.46s.


alek@nortimg:~/Code/metaplex/js/packages/cli$ ./bin/linux/metaplex 
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: INTERNAL ERROR this file doesn't exist in the virtual file system :/snapshot/js/node_modules/canvas/build/Release/libjpeg.so.62
    at tryImporting (pkg/prelude/bootstrap.js:2046:19)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/js/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
alek@nortimg:~/Code/metaplex/js/packages/cli$ ./bin/linux/metaplex create_candy_machine -k ~/.config/solana/id.json -e devnet -p 0.5
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: INTERNAL ERROR this file doesn't exist in the virtual file system :/snapshot/js/node_modules/canvas/build/Release/libjpeg.so.62
    at tryImporting (pkg/prelude/bootstrap.js:2046:19)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/js/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)


alek@nortimg:~/Code/metaplex/js/packages/cli$ ./bin/linux/metaplex create_candy_machine -k ~/.config/solana/id.json -e devnet -p 0.5
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: INTERNAL ERROR this file doesn't exist in the virtual file system :/snapshot/js/node_modules/canvas/build/Release/libjpeg.so.62
    at tryImporting (pkg/prelude/bootstrap.js:2046:19)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/js/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
```

But when I'm calling the built binary, it throws error and doesn't work. It seems there is a problem with `pkg` script.

**package.json**
```json
{
  "name": "@metaplex/cli",
  "version": "0.0.2",
  "main": "./build/cli.js",
  "license": "MIT",
  "bin": {
    "metaplex": "./build/candy-machine-cli.js"
  },
  "scripts": {
    "build": "tsc -p ./src",
    "watch": "tsc -w -p ./src",
    "package:linux": "pkg . --no-bytecode --targets node14-linux-x64 --output bin/linux/metaplex",
    "package:linuxb": "pkg . --targets node14-linux-x64 --output bin/linux/metaplex",
    "package:win": "pkg . --targets node14-win-x64 --output bin/win/metaplex",
    "package:macos": "pkg . --targets node14-macos-x64 --output bin/macos/metaplex",
    "format": "prettier --loglevel warn --write \"**/*.{ts,js,json,yaml}\"",
    "format:check": "prettier --loglevel warn --check \"**/*.{ts,js,json,yaml}\"",
    "lint": "eslint \"src/**/*.ts\" --fix",
    "lint:check": "eslint \"src/**/*.ts\"",
    "test": "jest"
  },
  "pkg": {
    "scripts": "./build/**/*.{js|json}"
  },
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current"
          }
        }
      ],
      "@babel/preset-typescript"
    ]
  },
  "jest": {
    "testPathIgnorePatterns": [
      "<rootDir>/build/",
      "<rootDir>/node_modules/"
    ]
  },
  "dependencies": {
    "@project-serum/anchor": "^0.14.0",
    "@solana/spl-token": "^0.1.8",
    "arweave": "^1.10.16",
    "bn.js": "^5.2.0",
    "borsh": "^0.4.0",
    "commander": "^8.1.0",
    "form-data": "^4.0.0",
    "ipfs-http-client": "^52.0.3",
    "jsonschema": "^1.4.0",
    "loglevel": "^1.7.1",
    "node-fetch": "^2.6.1",
    "weighted": "^0.3.0",
    "canvas": "^2.8.0",
    "image-data-uri": "^2.0.1",
    "imagemin": "^7.0.1",
    "imagemin-pngquant": "^9.0.2",
    "lodash": "^4.17.21",
    "merge-images": "^2.0.0"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.15.6",
    "@babel/preset-typescript": "^7.15.0",
    "@types/jest": "^27.0.1",
    "jest": "^27.2.0",
    "pkg": "^5.3.1",
    "typescript": "^4.3.5"
  }
}
```

**Comment by mustafatalha** [comment]
We all have same problem. I think, a commit in last week broke the cli. 

Similar issues:

https://github.com/metaplex-foundation/metaplex/issues/563

https://github.com/metaplex-foundation/metaplex/issues/560 Check comments, same problem exist.

**Comment by mustafatalha** [comment]
Binary version has a problem, you can use directly from code. Check getting started on https://hackmd.io/@levicook/HJcDneEWF

ts-node .\candy-machine-cli.ts help

**Comment by nukec** [comment]
using ts-node also due to bug

**Comment by emzeesquared** [comment]
I'm a noob and don't understand what you guys mean by you're using ts-node.  I installed ts node but using your command "ts-node .\candy-machine-cli.ts help" gives me an error "-bash: .candy-machine-cli.ts: command not found

**Comment by mustafatalha** [comment]
You should install ts-node with npm. 

npm install ts-node --global

**Comment by emzeesquared** [comment]
> You should install ts-node with npm.
> 
> npm install ts-node --global

I should be more specific.  I have installed ts-node with no issue however when using any ts-node command it tells me it's not a recognized command.  I'm running macOS.

**Comment by agmitron** [comment]
> > You should install ts-node with npm.
> > npm install ts-node --global
> 
> I should be more specific. I have installed ts-node with no issue however when using any ts-node command it tells me it's not a recognized command. I'm running macOS.

Instead of `metaplex help` use 

```bash
ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts help
```

(replace this path to your cloned repo's path)

It means you should call a TS script directly, without building it.

**Comment by dobpp** [comment]
> copy so files from here /metaplex/js/node_modules/canvas/build/Release to /usr/local/lib

I tried but still not working
