### ISSUE TITLE
Issue uploading via CLI

### ISSUE THREAD

**Issue by inksolum** [metaplex-foundation/metaplex#585]
Hi guys,

I'm trying tu upload assets using the CLI, but I'm getting an error running the following command on Windows 10:
.\/bin/win/metaplex upload .\example-assets\ --env devnet --keypair C:\wallet-test\devnet.json

pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: The specified module could not be found.
C:\Users\ANDRES~1\AppData\Local\Temp\b544b96dfa4cb284cbc1d94eac17dc8dc964f5b84a011214227bae0ff6f25dd2\canvas.node
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)
    at tryImporting (pkg/prelude/bootstrap.js:2080:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\snapshot\js\node_modules\canvas\lib\bindings.js:3:18)

Am I missing anything? 

Yarn version: 1.22.11
  '@metaplex/cli': '0.0.2',
  npm: '6.14.15',
  ares: '1.17.2',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.6',
  openssl: '1.1.1l',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.76',
  zlib: '1.2.11'
solana-cli: 1.7.12

**Comment by mustafatalha** [comment]
Binary version has a problem, you can use directly from code. Check getting started on https://hackmd.io/@levicook/HJcDneEWF

ts-node .\candy-machine-cli.ts upload .\example-assets\ --env devnet --keypair C:\wallet-test\devnet.json
