### ISSUE TITLE
Metaplex verify fails due to unexpected error

### ISSUE THREAD

**Issue by JIVIN0902** [metaplex-foundation/metaplex#590]
(node:11359) UnhandledPromiseRejectionWarning: Error: not all NFTs checked out. check out logs above for details
    at /Users/jivinvaidya/metaplex/js/packages/cli/src/candy-machine-cli.ts:282:11
    at step (/Users/jivinvaidya/metaplex/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/Users/jivinvaidya/metaplex/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/Users/jivinvaidya/metaplex/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

I have not modified any code in the cli files. When I run metaplex upload it works fine and it creates a devnet-temp file but on running metaplex verify it breaks and gives this error

**Comment by ajpierce** [comment]
I was getting this same error, and so I _did_ go and modify my code to get more data about why it was failing.  Outlined my changes here:

https://github.com/metaplex-foundation/metaplex/issues/608#issuecomment-934500783

Looks like there's information missing from the cache data, even though it's in the cache items array.  Running upload multiple times has not fixed this for me yet.

Did you ever get past this error?

**Comment by JIVIN0902** [comment]
@ajpierce I am still stuck on this. I read your comment. But my situation is that I have only 1png and 1.json file only for testing right now in the assets folder and it still fails
