### ISSUE TITLE
Metaplex: command not found

### ISSUE THREAD

**Issue by taimurworks98** [metaplex-foundation/metaplex#601]
My command: 
metaplex upload ./assets --env devnet --keypair ~/.config/solana/devnet.json

Error:
metaplex: command not found

My package:
"@metaplex/js": "^1.0.0",
"@solana/spl-token": "^0.1.8",

Is there anything missing?

Need Help!

**Comment by hmzakhalid** [comment]
the metaplex bin is broken for some reason
install `npm install -g ts-node`
then from the `cli` folder run this command
'ts-node ./src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet.json'

**Comment by taimurworks98** [comment]
> the metaplex bin is broken for some reason install `npm install -g ts-node` then from the `cli` folder run this command `ts-node ./src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet.json`
> 
> if you get errors while uploading and it doesn't work. Dont worry cuz everyone else is facing the same issue. They'll probably fix it soon

Beginning the upload for 2 (png+json) pairs
started at: 1633338231125
(node:12797) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/root/.config/solana/devnet.json'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at loadWalletKey (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/accounts.ts:263:34)
    at /home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/commands/upload.ts:62:38
    at step (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/commands/upload.ts:44:23)
    at Object.next (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/commands/upload.ts:25:53)
    at /home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/commands/upload.ts:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/commands/upload.ts:15:12)
    at upload (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/commands/upload.ts:67:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by taimurworks98** [comment]
> the metaplex bin is broken for some reason install `npm install -g ts-node` then from the `cli` folder run this command `ts-node ./src/candy-machine-cli.ts upload ./assets --env devnet --keypair ~/.config/solana/devnet.json`
> 
> if you get errors while uploading and it doesn't work. Dont worry cuz everyone else is facing the same issue. They'll probably fix it soon



THANKS THAT DID HELP ME!!!

BUT I RAN INTO ANOTHER ISSUE, CAN YOU PLEASE CHECK THIS ONE




Beginning the upload for 2 (png+json) pairs
started at: 1633341106605
wallet public key: DNc8riHgdf9PP4TsUAA3QDK9TU48h64oUZSji4zTH37B
Processing file: 0
REST no confirmations for 2Bs3cRUbXWgfPgqgJxbAF3Fx1anXcuVboeDPGnyRBucPKXmaAfz9EsKj3qUJKrNHEQYtkDjVvAMsa8jMqHzXLeQg {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: null,
  slot: 85099481,
  status: { Ok: null }
}
Error uploading file 0 Error: No transaction ID for upload: 0
    at /home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:71:11
    at step (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:52:23)
    at Object.next (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:33:53)
    at fulfilled (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error uploading file 1 Error: No transaction ID for upload: 1
    at /home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:71:11
    at step (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:52:23)
    at Object.next (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:33:53)
    at fulfilled (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/src/helpers/upload/arweave.ts:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Done. Successful = false.
upload was not successful, rerunning
