### ISSUE TITLE
Error on CREATE_CANDY_MACHINE ==>> Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0

### ISSUE THREAD

**Issue by taimurworks98** [metaplex-foundation/metaplex#604]
Command:
ts-node ./src/candy-machine-cli.ts create_candy_machine -k /root/.config/solana/devnet.json -e devnet -p 0.5

Error:
wallet public key: DNc8riHgdf9PP4TsUAA3QDK9TU48h64oUZSji4zTH37B
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Create Account: account Address { address: FfDF72cBkRQF59BY1BcwsnqsTXMMkzC3swaENcPaKSYW, base: None } already in use
    Program 11111111111111111111111111111111 failed: custom program error: 0x0
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x0
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3668:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3628:20)
    at async Object.sendAndConfirmRawTransaction (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Create Account: account Address { address: FfDF72cBkRQF59BY1BcwsnqsTXMMkzC3swaENcPaKSYW, base: None } already in use',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x0',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x0'
  ]
}
(node:7460) UnhandledPromiseRejectionWarning: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3668:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/connection.ts:3628:20)
    at async Object.sendAndConfirmRawTransaction (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (/home/taimoor/Workspace/Softtik/Solana/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lamar-frankie** [comment]
I got a similar error. Double check your command and the arguments. That's what my issue was. I had a typo in one of the arguments.

**Comment by slimjnft** [comment]
I am having the same issue here. I checked the commands and arguments multiple times but nothing worked. Any other suggestions for a solution?

**Comment by boudlal** [comment]
Just remove the `.cache `folder, and try again
