### ISSUE TITLE
Error When trying to create a new fair launch: 

### ISSUE THREAD

**Issue by lamar-frankie** [metaplex-foundation/metaplex#615]
Hello, 

when I try to create a new fair fair launch by entering the following:
```bash
node build/fair-launch-cli.js new_fair_launch -e devnet -k ~/.config/solana/devnet.json -u test01 -f 0.1 -s 0.1 -pe 2 -pos "2021 Oct 04 13:30:00 EST" -poe "2021 Oct 04 13:30:00 EST" -pte "2021 Oct 03 13:40:00 EST" -ts 0.1 -n 2 -arbp 5000 -atc 1 -sd "05 Oct 2021 09:00:00 GMT"
```

I receive the following error: 

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x131 
    Program faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]
    Program log: Instruction: InitializeMint
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2280 of 175325 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program log: Custom program error: 0x131
    Program faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j consumed 35032 of 200000 compute units
    Program faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j failed: custom program error: 0x131
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x131
    at Connection.sendEncodedTransaction (~/Documents/code_base/metaplex/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (~/Documents/code_base/metaplex/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (~/Documents/code_base/metaplex/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (~/Documents/code_base/metaplex/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as initializeFairLaunch] (/~/Documents/code_base/metaplex/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]',
    'Program log: Instruction: InitializeMint',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2280 of 175325 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success',
    'Program log: Custom program error: 0x131',
    'Program faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j consumed 35032 of 200000 compute units',
    'Program faircnAB9k59Y4TXmLabBULeuTLgV7TkGMGNkjnA15j failed: custom program error: 0x131'
  ]
}
(node:89613) UnhandledPromiseRejectionWarning: Error
    at Function.parse (~/Documents/code_base/metaplex/js/node_modules/@project-serum/anchor/dist/cjs/error.js:31:20)
    at Object.rpc [as initializeFairLaunch] (~/Documents/code_base/metaplex/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:89613) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:89613) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lamar-frankie** [comment]
Node version = v14.18.0
Solana version = 1.7.14 
Yarn Version = 1.22.15
OS = Ubuntu 20.04.3 LTS

**Comment by lamar-frankie** [comment]
Typo in the fair launch cmd. Endate was before the start date.
