### ISSUE TITLE
'Index greater than length!'

### ISSUE THREAD

**Issue by richardj97** [metaplex-foundation/metaplex#621]
Hello, I can't seem to get past uploading 2000/10,000 NFTs. I'm stuck with the error message:

`Transaction simulation failed: Error processing Instruction 0: custom program error: 0x12f
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x12f
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 8974 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x12f
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x12f
    at Connection.sendEncodedTransaction (C:\Users\RichJacobs\metaplex2\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3668:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\Users\RichJacobs\metaplex2\js\packages\cli\node_modules\@solana\web3.js\src\connection.ts:3628:20)
    at async Object.sendAndConfirmRawTransaction (C:\Users\RichJacobs\metaplex2\js\packages\cli\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\RichJacobs\metaplex2\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (C:\Users\RichJacobs\metaplex2\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x12f',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 8974 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x12f'
  ]
}
saving config line 2000-2002 failed ProgramError:
    at Function.parse (C:\Users\RichJacobs\metaplex2\js\packages\cli\node_modules\@project-serum\anchor\src\error.ts:30:14)
    at Object.rpc [as addConfigLines] (C:\Users\RichJacobs\metaplex2\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 303,
  msg: 'Index greater than length!'
}`

Does anyone have an idea? Thanks

**Comment by Harish88s** [comment]
Does it have any rate limiting ?  Taking a pause and trying again gives you same result?

**Comment by richardj97** [comment]
No luck. If I go back to 1999 it works fine! As soon as I put nft 2000 in the upload folder it shows Error 303: Index greater than length!
