### ISSUE TITLE
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139

### ISSUE THREAD

**Issue by Zaft** [metaplex-foundation/metaplex#625]
When running the create_candy_machine command I'm receiving the following error: 

I have tested the same set of assets and commands on devnet without having any issues. 

Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 21820 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (/Users/dev/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/Users/dev/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/Users/dev/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/Users/dev/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (/Users/dev/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 21820 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}

ProgramError
    at Function.parse (/Users/dev/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (/Users/kurt/dev/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 313,
  msg: 'Number of config lines must match items available'
}

**Comment by Zaft** [comment]
I think this is related to issue [](https://github.com/metaplex-foundation/metaplex/issues/464). However, I'm not clear as to step he used to resolve the issue.

**Comment by Harish88s** [comment]
Over ride the cache folder might help  .cache/ 
copy it from local file

**Comment by richardj97** [comment]
I'm having the same issue. There is nothing wrong with mine, as soon as it hits NFT 2000 it causes the 'Index greater than length!' error

**Comment by Zaft** [comment]
Ok this might help somone. If you run the verify command with the -l trace, it sets the log level to trace out which item check out. I have seen so for that a few don't print with the checked out line. Once it's done I'm going to set those items to onChain: false and re-rerun the upload.

**Comment by Happyprince65** [comment]
After above check please change all onchain value to false, and run upload command again. let us know what was your result
