### ISSUE TITLE
Getting error on creating timestamp. TypeError: Cannot read property 'candyMachineAddress' of undefined

### ISSUE THREAD

**Issue by hammadsayyed** [metaplex-foundation/metaplex#655]
On devnet everything worked fine but on mainnet-beta this error occured.
Uploaded the assets successfully.
Created candy machine successfully.
Causing error while creating timestamp by below command.
```
ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --keypair /home/user1/mp-assets/mainnet-beta.json --date '6 Oct 2021 20:00:00 UTC'
```
```
(node:3165) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'candyMachineAddress' of undefined
    at /home/user1/metaplex/js/packages/cli/src/candy-machine-cli.ts:565:53
    at step (/home/user1/metaplex/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/home/user1/metaplex/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/home/user1/metaplex/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3165) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3165) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
## Additional details
node --version v14.18.0
ts-node --version v10.2.1
npm --version 6.14.15

## Solutions tried
Run the verified command.
Re run the upload command.
Tried to run on windows and ubuntu

What went wrong please help.

**Comment by Mad-houdini8** [comment]
I'm having the same exact issue

**Comment by MetaMutants** [comment]
Hi, I found the solution. When on mainnet you have to set the environment to mainnet because the default is devnet so add -e mainnet-beta to the command.

**Comment by jordansexton** [comment]
@MetaMutants @itxshakil thanks for sharing your solutions!
