### ISSUE TITLE
Can't build macos-x64 cli package

### ISSUE THREAD

**Issue by manticarodrigo** [metaplex-foundation/metaplex#664]
Getting the following error while running `yarn run package:macos-x64` using node `v14.17.0` as specified in `.nvmrc` file:

```[
  {
    "nodeRange": "node14",
    "platform": "macos",
    "arch": "x64",
    "output": "/Users/manticarodrigo/@manticarodrigo/metaplex/js/packages/cli/bin/macos/metaplex",
    "forceBuild": false,
    "fabricator": {
      "nodeRange": "node14",
      "platform": "macos",
      "arch": "x64",
      "binaryPath": "/Users/manticarodrigo/.pkg-cache/v3.2/fetched-v14.17.2-macos-x64-signed"
    },
    "binaryPath": "/Users/manticarodrigo/.pkg-cache/v3.2/fetched-v14.17.2-macos-x64"
  }
]
/snapshot/js/node_modules/react-native-fetch-api/fetch.js:1
(function (exports, require, module, __filename, __dirname) { import Headers from "./src/Headers";
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:103:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
/snapshot/js/node_modules/react-native-fetch-api/fetch.js:1
(function (exports, require, module, __filename, __dirname) { import Headers from "./src/Headers";
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:103:7)
    at Socket.<anonymous> ([eval]:18:19)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)```

**Comment by sensiblefolk** [comment]
Hello @manticarodrigo are you still experiencing this error, if yes then the approach that worked using an M1 macbook.

Following this helpful article by jurnal [link here](https://www.jurnalanas.com/node-js-mac-m1/), once you are done installing node v14.17.0 repeat `yarn run package:macos-x64`.
