### ISSUE TITLE
Cannot verify upload and create candy machine

### ISSUE THREAD

**Issue by dex2code** [metaplex-foundation/metaplex#672]
Successfully uploaded assets:

% alias metaplex='ts-node /Users/me/.japps/metaplex/js/packages/cli/src/candy-machine-cli.ts' 
% metaplex -V
0.0.2

% metaplex upload ./assets --env mainnet-beta --keypair ~/.config/solana/sr.json   
Beginning the upload for 50 (png+json) pairs
started at: 1633708255536
wallet public key: <my_wallet>
Processing file: 0
Writing indices SR0049-SR0542
Writing indices SR0606-SR1512
Writing indices SR1612-SR2333
Writing indices SR2441-SR2882
Writing indices SR2961-SR3873
Done. Successful = true.
ended at: 2021-10-08T15:52:25.810Z. time taken: 00:01:30

After this tried to verify uploading:

% metaplex verify --env mainnet-beta --keypair ~/.config/solana/sr.json
wallet public key: <my_wallet>
(node:18941) UnhandledPromiseRejectionWarning: Error: not all NFTs checked out. check out logs above for details
    at /Users/me/.japps/metaplex/js/packages/cli/src/candy-machine-cli.ts:273:11
    at step (/Users/me/.japps/metaplex/js/packages/cli/src/candy-machine-cli.ts:53:23)
    at Object.next (/Users/me/.japps/metaplex/js/packages/cli/src/candy-machine-cli.ts:34:53)
    at fulfilled (/Users/me/.japps/metaplex/js/packages/cli/src/candy-machine-cli.ts:25:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

% metaplex create_candy_machine -k ~/.config/solana/sr.json -e mainnet-beta -p 1        
wallet public key: <my_wallet>
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18820 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (/Users/me/.japps/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/Users/me/.japps/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/Users/me/.japps/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/Users/me/.japps/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as initializeCandyMachine] (/Users/me/.japps/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18820 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
(node:19294) UnhandledPromiseRejectionWarning: Error: 
    at Function.parse (/Users/me/.japps/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:30:14)
    at Object.rpc [as initializeCandyMachine] (/Users/me/.japps/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Whats wrong?

**Comment by dex2code** [comment]
Moreover, the problem is in config.data variable - it contains only 10 items instead of 50 in cache.

Is this problem on arweave side?
