### ISSUE TITLE
M1 Mac Apple -> canvas.node, 1): no suitable image found

### ISSUE THREAD

**Issue by Qambar** [metaplex-foundation/metaplex#691]
It seems to be creating a file canvas.node in /var/folders/f_/ll33dc315ldc738pbth9339m0000gp/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node

And throwing following error on M1 Mac Apple

```
$ metaplex -v
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: dlopen(/var/folders/f_/ll33dc315ldc738pbth9339m0000gp/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node, 1): no suitable image found.  Did find:
        /var/folders/f_/ll33dc315ldc738pbth9339m0000gp/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node: mach-o, but wrong architecture
        /private/var/folders/f_/ll33dc315ldc738pbth9339m0000gp/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node: mach-o, but wrong architecture
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)
    at tryImporting (pkg/prelude/bootstrap.js:2080:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/js/node_modules/canvas/lib/bindings.js:3:18)
(base) 
```

**Comment by bmeeder22** [comment]
Try running`brew install` on the following packages: 
`pixman, cairo and pango`

**Comment by Qambar** [comment]
The actual error is `canvas.node: mach-o, but wrong architecture` installing those packages didn't help. still getting the same error:

```$ ~/bin/metaplex verify --keypair ~/.config/solana/id.json
pkg/prelude/bootstrap.js:1697
      throw error;
      ^

Error: dlopen(/var/folders/f_/ll33dc315ldc738pbth9339m0000gp/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node, 1): no suitable image found.  Did find:
        /var/folders/f_/ll33dc315ldc738pbth9339m0000gp/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node: mach-o, but wrong architecture
        /private/var/folders/f_/ll33dc315ldc738pbth9339m0000gp/T/8eb7bd0516654c7bf3e2d99959b4166cc3c7cfc31e647d23d51a23475f407d8a/canvas.node: mach-o, but wrong architecture
    at tryImporting (pkg/prelude/bootstrap.js:2028:37)
    at tryImporting (pkg/prelude/bootstrap.js:2080:16)
    at process.dlopen (pkg/prelude/bootstrap.js:2103:7)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1676:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/snapshot/js/node_modules/canvas/lib/bindings.js:3:18)
(base) ```

**Comment by sensiblefolk** [comment]
Just use a linux distro if you could, save yourself from the m1 hell

**Comment by andrewgypsee** [comment]
@Qambar Did you figure it out, I'm having trouble getting CLI working on M1.

**Comment by jscrui** [comment]
To make it work try using `$ ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts` instead of `metaplex`. 


There is a problem on the executable building its also happens on Ubuntu 20.04.

**Comment by yurenji** [comment]
+1 
had the same issue with macos-x64 build

**Comment by felipeinfantino** [comment]
Hi, im having the same problem and the ts-node solution didnt work

```
ts-node src/candy-machine-cli.ts
Error: dlopen(/Users/pepegis/Documents/Pepe/Solana/metaplex/js/node_modules/canvas/build/Release/canvas.node, 1): no suitable image found.  Did find:
	/Users/pepegis/Documents/Pepe/Solana/metaplex/js/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
	/Users/pepegis/Documents/Pepe/Solana/metaplex/js/node_modules/canvas/build/Release/canvas.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1127:18)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/pepegis/Documents/Pepe/Solana/metaplex/js/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
```

node -v
v14.17.0

ts-node -v
v10.4.0

Any suggestions ?

**Comment by Nasafato** [comment]
@felipeinfantino This is because the `canvas` library only comes with binaries built for x86-64 (Intel), but none for the M1 Mac. You'll need to build the `canvas` library from source:
```
// With yarn:
npm_config_build_from_source=true yarn add -W canvas
// With node
npm install --build-from-source canvas
```

**Comment by ringockmg** [comment]
@Nasafato 

Followed every step, still have the same issue.

**Comment by amandafanny** [comment]
![image](https://user-images.githubusercontent.com/54808661/150277451-8a1762a0-cfb6-4ec5-8caf-a434358efda3.png)

**Comment by kcc0** [comment]
Has anyone found a fix for this yet? I'm facing this issue on my M1 Pro.

**Comment by johnhatvani** [comment]
I am also facing the same issue on the m1, 
Have followed the suggestions in this thread ie.

my issue is with the `v2-cli` especially this command ` ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts --version`

**Comment by kcc0** [comment]
> 

This is the only way it worked for me -> https://github.com/Automattic/node-canvas/issues/1733#issuecomment-1019991052

**Comment by stegaBOB** [comment]
For M1 you need to follow this and it should work: https://docs.metaplex.com/candy-machine-v2/getting-started#apple-m1-chip

**Comment by yokinist** [comment]
> For M1 you need to follow this and it should work: https://docs.metaplex.com/candy-machine-v2/getting-started#apple-m1-chip

it works for me. thanks!
```
$ brew install pkg-config cairo pango libpng jpeg giflib librsvg
```
