### ISSUE TITLE
Timeout Error caught { timeout: true }

### ISSUE THREAD

**Issue by samuelrondot** [metaplex-foundation/metaplex#696]
Hello,
I'm facing an issue while uploading on the mainnet-beta. I'm getting the following error : 
```

ejecting for timeout...
Timeout Error caught { timeout: true }
Error uploading file 1272 Error: Timed out awaiting confirmation on transaction
    at /Users/samuel/Desktop/TheBoringSociety/metaplex/js/packages/cli/src/helpers/transactions.ts:121:13
    at step (/Users/samuel/Desktop/TheBoringSociety/metaplex/js/packages/cli/src/helpers/transactions.ts:33:23)
    at Object.throw (/Users/samuel/Desktop/TheBoringSociety/metaplex/js/packages/cli/src/helpers/transactions.ts:14:53)
    at rejected (/Users/samuel/Desktop/TheBoringSociety/metaplex/js/packages/cli/src/helpers/transactions.ts:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The first files went through but after a certain amount files I started getting issues like if my ip was blocked for too many attempt.
I can't find any similar info. Does any body face the same issue ?

**Comment by samuelrondot** [comment]
If someone has this issue too, it's because I didn't have enough SOL in my wallet. The price asked by Metaplex when you first run the -upload command is not the final one ( by far )
