### ISSUE TITLE
create_candy_machine with custom treasury address problem

### ISSUE THREAD

**Issue by Mitolius** [metaplex-foundation/metaplex#745]
Hello world,

I pull latest (2021-10-16), I try to set a different treasury address using the -s argument of the create_candy_machine command but it throw and error:

Command look like this (bash script) if I remove the -s argument it works:

ts-node $metaplex_cli create_candy_machine -k $keypair -p $price --env $env -s MY_TREASURY_PUBLIC_KEY

wallet public key: GZxyaoAU4hrhuSjVPvNgeUs3b5YrcM1nX7vgb6A9T3BF
============== treasury wallet:GnM1dB9T3zX1kGfpvKccEEbsfb2UCdjNtdmq8A3SENY5
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8f
Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program log: Custom program error: 0x8f
Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18258 of 200000 compute units
Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8f
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8f
at Connection.sendEncodedTransaction (/home/user/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Connection.sendRawTransaction (/home/user/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
at async Object.sendAndConfirmRawTransaction (/home/user/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
at async Provider.send (/home/user/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
at async Object.rpc [as initializeCandyMachine] (/home/user/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
logs: [
'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
'Program 11111111111111111111111111111111 invoke [2]',
'Program 11111111111111111111111111111111 success',
'Program log: Custom program error: 0x8f',
'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18258 of 200000 compute units',
'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8f'
]
}
(node:5420) UnhandledPromiseRejectionWarning: Error:
at Function.parse (/home/user/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
at Object.rpc [as initializeCandyMachine] (/home/user/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use node --trace-warnings ... to show where the warning was created)
(node:5420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Mitolius** [comment]
Ok I found the solution for thos having the same issue:
custom program error: 0x8f'

The treasury wallet must have SOL balance. I request airdrop of 1 SOL in it and it works
