### ISSUE TITLE
create_candy_machine command seems not working

### ISSUE THREAD

**Issue by selimerunkut** [metaplex-foundation/metaplex#748]
Hi,

created wallet and funded  it on devnet

pulled this metaplex repo and  executed the following commands:

` yarn metaplex upload ./packages/cli/example-assets --env devnet --keypair ~/.config/solana/devnet.json`

upload seemed successful, although I do not see the images only he metadata:

`https://c4tnifyiqohcuvyxngfoyisz2fageik6z4cmizlnjxm5y5eqsyca.arweave.net/FybUFwiDjipXF2mK7CJZ0UBiIV7PBMRlbU3Z3HSQlgQ/`

`yarn metaplex verify --env devnet --keypair ~/.config/solana/devnet.json`

result: `Name 1 with https://arweave.net/SAvhSWFxqLsruGr1iioRJIl1k542nBsrHBtgrKc3VE4 returned non-200 from uploader 404`

After the command yarn metaplex create_candy_machine --env devnet --keypair ~/.config/solana/devnet.json

I get the following error:

`Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Allocate: account Address { address: 7xwf7banQtiDnkFMmZLBifm9mQKULzsMGCLvgsq6vnyw, base: None } already in use
    Program 11111111111111111111111111111111 failed: custom program error: 0x0
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x0
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Connection.sendRawTransaction (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at Object.sendAndConfirmRawTransaction (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at Provider.send (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at Object.rpc [as initializeCandyMachine] (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Allocate: account Address { address: 7xwf7banQtiDnkFMmZLBifm9mQKULzsMGCLvgsq6vnyw, base: None } already in use',
    'Program 11111111111111111111111111111111 failed: custom program error: 0x0',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x0'
  ]
}
(node:9019) UnhandledPromiseRejectionWarning: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Connection.sendRawTransaction (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at Object.sendAndConfirmRawTransaction (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at Provider.send (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at Object.rpc [as initializeCandyMachine] (/Users/selimerunkut/metaplex-foundation/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by lettuce0x** [comment]
Indeed, I had similar issue testing to upload the png files of the example-assets folder. For some reason, it is returning 404 on Arweave. I tested replacing one of those png files, and it worked.

**Comment by zyrusdiaz** [comment]
Hi, any updates on this? 

Found an article that says I need SOL tokens in the current account address for this to be fixed. Already tried that, but this error is still occurring.

**Comment by smemz12** [comment]
Did you figure this out?

**Comment by selimerunkut** [comment]
> Did you figure this out?

yes, see here:
https://github.com/metaplex-foundation/metaplex/issues/748#issuecomment-950303247
