### ISSUE TITLE
Translating error on upload, Candy Machine doesn´t initialze

### ISSUE THREAD

**Issue by 0xsol1d** [metaplex-foundation/metaplex#784]
Hi,
I´m running into a very frustrating error when try to upload the files on devnet. A few days ago it worked but now I´m getting this:

Beginning the upload for 2 (png+json) pairs
started at: 1634975178415
wallet public key: **************************************************
Processing file: 0
initializing config

Translating error Error: Transaction was not confirmed in 60.02 seconds. It is unknown if it succeeded or failed. Check signature ExXMKE2JHoCKYqXXAab71UAuh9oeYJZNWCypXEhpKJdWUFxpr7ui8dZyd2LsnzGYFN7wuvfeLvQfe3ukzdypsbx using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async Object.sendAndConfirmRawTransaction (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as initializeConfig] (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
Error deploying config to Solana network. Error: Transaction was not confirmed in 60.02 seconds. It is unknown if it succeeded or failed. Check signature ExXMKE2JHoCKYqXXAab71UAuh9oeYJZNWCypXEhpKJdWUFxpr7ui8dZyd2LsnzGYFN7wuvfeLvQfe3ukzdypsbx using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async Object.sendAndConfirmRawTransaction (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as initializeConfig] (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
(node:13728) UnhandledPromiseRejectionWarning: Error: Transaction was not confirmed in 60.02 seconds. It is unknown if it succeeded or failed. Check signature ExXMKE2JHoCKYqXXAab71UAuh9oeYJZNWCypXEhpKJdWUFxpr7ui8dZyd2LsnzGYFN7wuvfeLvQfe3ukzdypsbx using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async Object.sendAndConfirmRawTransaction (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as initializeConfig] (C:\_SOLJUNKS\Candy_Machine_Test2\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled 
with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)    
(node:13728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I dont know why this "timeout" error occurs. Tried several fresh setups, sometimes it works, sometimes not, but never out of the box. I´m using WIndows and VisualCode, SOlanaCLI 1.7.15, no VPN and stabile internet connection.

JSON files are legit and are follwing the metaplex standard, several people comfirmed that to me.

Also got this comment to this error:
"The solution was to increase the image file size to at least 20kb each. 
Apparently arweave has an issue where png files <5kb are not processed correctly during upload."
but this even doesn´t change the timeout error on initialzing.

If you need more info, please tell. 
I hope someone can help me with this.

**Comment by emersonthis** [comment]
I'm still getting this same error 3 months later. I think this issue should still be open.

**Comment by Jjfern96** [comment]
Same issue. Any incites here?

**Comment by yashtech4721** [comment]
Same issue. Is there problem in solana blockchain or endpoint?
