### ISSUE TITLE
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d

### ISSUE THREAD

**Issue by sexymeow** [metaplex-foundation/metaplex#811]
Hi,

After running `$ts-node js/packages/cli/src/candy-machine-cli.ts upload /home/loa/Desktop/metaplex/assets --env devnet --keypair /home/loa/config/solana/devnet.json `

im getting the following:
```
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16535 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16535 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 60-69 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 70-79
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16564 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16564 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 70-79 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 80-89
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16408 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16408 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 80-89 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 90-99
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16627 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16627 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 90-99 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 100-109
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16492 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16492 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 100-109 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 110-119
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16490 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16490 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 110-119 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 120-129
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16409 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16409 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 120-129 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 130-139
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16485 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16485 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 130-139 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 140-149
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16563 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16563 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 140-149 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 150-159
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16142 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async Object.sendAndConfirmRawTransaction (/home/loa/Desktop/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 16142 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 150-159 failed ProgramError
    at Function.parse (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/error.ts:36:14)
    at Object.rpc [as addConfigLines] (/home/loa/Desktop/metaplex/js/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}
Writing indices 160-169

```

**Comment by Nikodeam** [comment]
> i think i found it, wasws a hidden folder, thank you!



> @sexymeow I got this resolved by removing the `.cache` folder

Could you guys please help me out and tell where it was? I took a search with windows file explorer there are 4.

**Comment by santiq** [comment]
Cache folders are located in 

> metaplex/.cache

and

> metaplex/js/.cache

**Comment by Jalapina** [comment]
I have this issue still. I tried deleting my .cache folder from the main directory and inside js. 
I'm on devnet and have 3 sol in my account

**Comment by ManuBernard** [comment]
Same here, still having this issue, on mainnet. Deleted the .cache folder, doesn't help. 
Any body has an idea ?
