### ISSUE TITLE
Trying to yarn install and getting a canvas error

### ISSUE THREAD

**Issue by cheeyoon** [metaplex-foundation/metaplex#824]
```
➜  ~ cd src/metaplex/js 
➜  js git:(master) yarn install && yarn bootstrap && yarn build
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/helper-compilation-targets@7.15.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
warning " > ts-jest@24.3.0" has incorrect peer dependency "jest@>=24 <25".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-typescript@7.15.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @oyster/common > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > candy-machine-mint > @solana/wallet-adapter-material-ui@0.8.3" has incorrect peer dependency "@solana/wallet-adapter-react@^0.8.3".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > candy-machine-mint > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > candy-machine-mint > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > less-loader@10.2.0" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > @typechain/ethers-v4@1.0.1" has unmet peer dependency "typechain@^2.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > @typechain/ethers-v4@1.0.1" has unmet peer dependency "ethers@^4.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @aws-sdk/client-s3 > @aws-sdk/middleware-sdk-s3@3.38.0" has unmet peer dependency "@aws-sdk/signature-v4-crt@^3.31.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.15.4" has unmet peer dependency "@babel/core@^7.13.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-class-properties@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-class-static-block@7.15.4" has unmet peer dependency "@babel/core@^7.12.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-dynamic-import@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-export-namespace-from@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-json-strings@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-logical-assignment-operators@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-numeric-separator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.15.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-optional-chaining@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-private-methods@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-private-property-in-object@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-class-static-block@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-export-namespace-from@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-syntax-private-property-in-object@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-arrow-functions@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-async-to-generator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-block-scoping@7.15.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-classes@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-computed-properties@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-destructuring@7.14.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-dotall-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-duplicate-keys@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-for-of@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-function-name@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-member-expression-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-amd@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-commonjs@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-systemjs@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-modules-umd@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.14.9" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-new-target@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-object-super@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-parameters@7.15.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-property-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-regenerator@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-reserved-words@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-spread@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-template-literals@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-typeof-symbol@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-unicode-escapes@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-transform-unicode-regex@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/preset-modules@0.1.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-corejs2@0.2.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-corejs3@0.2.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-regenerator@0.2.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-typescript > @babel/plugin-transform-typescript@7.15.8" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > @solana/spl-name-service > crypto-ts@1.0.2" has unmet peer dependency "@angular/common@>= 5.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > @solana/spl-name-service > crypto-ts@1.0.2" has unmet peer dependency "@angular/core@>= 5.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > @solana/spl-name-service > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > magic-sdk > @magic-sdk/commons@1.2.1" has incorrect peer dependency "@magic-sdk/provider@^4.3.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > magic-sdk > @magic-sdk/commons@1.2.1" has incorrect peer dependency "@magic-sdk/types@^3.1.1".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > web > webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.15.4" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex > @babel/helper-create-regexp-features-plugin@7.14.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-env > babel-plugin-polyfill-corejs2 > @babel/helper-define-polyfill-provider@0.2.3" has unmet peer dependency "@babel/core@^7.4.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @metaplex/cli > @babel/preset-typescript > @babel/plugin-transform-typescript > @babel/plugin-syntax-typescript@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin-ed25519@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin-ed25519@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/http-helpers@1.4.0" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-jrpc@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > @oyster/common > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-utils@0.9.5" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-jrpc@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
warning "workspace-aggregator-cb047d04-6a23-4e6f-8541-334b585b31cf > candy-machine-mint > @solana/wallet-adapter-wallets > @solana/wallet-adapter-torus > @toruslabs/openlogin > @toruslabs/openlogin-utils@0.10.2" has unmet peer dependency "@babel/runtime@7.x".
[5/5] 🔨  Building fresh packages...
[13/20] ⢀ less-watch-compiler
[14/20] ⢀ core-js
[10/20] ⢀ secp256k1
[7/20] ⢀ canvas
**error** /Users/cheeyoon/src/metaplex/js/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/cheeyoon/src/metaplex/js/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.6
node-pre-gyp info using node@17.0.1 | darwin | x64
node-pre-gyp info check checked for "/Users/cheeyoon/src/metaplex/js/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@17.0.1 (node-v102 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@17.0.1 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@17.0.1 | darwin | x64
gyp info find Python using Python version 2.7.15 found at "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
(node:10980) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/cheeyoon/src/metaplex/js/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cheeyoon/src/metaplex/js/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cheeyoon/src/metaplex/js/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/cheeyoon/Library/Caches/node-gyp/17.0.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/cheeyoon/Library/Caches/node-gyp/17.0.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/cheeyoon/src/metaplex/js/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/cheeyoon/Library/Caches/node-gyp/17.0.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/cheeyoon/src/metaplex/js/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/cheeyoon/src/metaplex/js/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/usr/local/bin/node" "/Users/cheeyoon/src/metaplex/js/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/cheeyoon/src/metaplex/js/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/cheeyoon/src/metaplex/js/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v102"
gyp ERR! cwd /Users/cheeyoon/src/metaplex/js/node_modules/canvas
gyp ERR! node -v v17.0.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/cheeyoon/src/metaplex/js/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/cheeyoon/src/metaplex/js/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/cheeyoon/src/metaplex/js/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v102' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/cheeyoon/src/metaplex/js/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1062:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 20.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/cheeyoon/src/metaplex/js/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/cheeyoon/src/metaplex/js/node_modules/canvas
node-pre-gyp ERR! node -v v17.0.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.6
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /Users/cheeyoon/src/metaplex/js/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/cheeyoon/src/metaplex/js/node_modules/canvas/
```

**Comment by cheeyoon** [comment]
> your yarn.lock is corrupted. use the yarn.lock in this projects as base one and the run yarn isntall

Tried `git checkout` to a previous yarn.lock and ran `yarn install` again and still getting the same canvas error.
Seems like [https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v102-darwin-unknown-x64.tar.gz](url) `Not Found` is causing this

**Comment by nathanielremy** [comment]
npm install 14.17.0
nvm use 14.17.0

Use this version of node (14.17.0) it will fix your canvas issue. Then after maybe you will run into the yarn build issue and have to checkout the previous commit

**Comment by cheeyoon** [comment]
Thanks, that solved it

**Comment by lherna1371** [comment]
had issues with canvas while running 'yarn install' ​on the mac, apple chip. had to install from source: 

https://github.com/Automattic/node-canvas/wiki/Installation%3A-Mac-OS-X


ran: brew install pkg-config cairo pango libpng jpeg giflib librsvg

**Comment by nicojochnick** [comment]
I was looking for hours for this - thank you so much!

**Comment by hanscnelson** [comment]
> 

Thank you!
