### ISSUE TITLE
Candy Machine upload fails when new file is added to folder

### ISSUE THREAD

**Issue by wandrzejczak** [metaplex-foundation/metaplex#825]
**Describe the bug**

Upload command fails, when we initially upload for example 2 files, and we add 2.png and 2.json files.
Then we end up with an error like below:

```
Processing file: 0
Writing indices 0-4
Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 1211 out of range for slice of length 976', nft-candy-machine/src/lib.rs:318:18
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (C:\Users\wojtek\projects\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3689:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\Users\wojtek\projects\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3649:20)
    at async Object.sendAndConfirmRawTransaction (C:\Users\wojtek\projects\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\wojtek\projects\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (C:\Users\wojtek\projects\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 1211 out of range for slice of length 976', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
saving config line 0-4 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (C:\Users\wojtek\projects\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3689:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (C:\Users\wojtek\projects\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3649:20)
    at async Object.sendAndConfirmRawTransaction (C:\Users\wojtek\projects\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (C:\Users\wojtek\projects\metaplex\js\node_modules\@project-serum\anchor\src\provider.ts:112:18)
    at async Object.rpc [as addConfigLines] (C:\Users\wojtek\projects\metaplex\js\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 1211 out of range for slice of length 976', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}

```
**To Reproduce**
1. Upload files
2. add new png & JSON file with number +1
3. run upload command

**Expected behavior**
I'd expect the program to add the new files without an error.

**Comment by wandrzejczak** [comment]
I've my assets started with 0 index.
Problem is that when I upload and I want to add new file with 1 index upload fails.

**Comment by DesignerPaco** [comment]
Hello  I am getting issues uploading the assets, its .mp4 does candymachine supports video?? Sorry i am new Dev the error is below:
 return fs.readdirSync(`${val}`).map(file => path.join(val, file));
                      ^
Error: number of png files (0) is different than the number of json files (11)

**Comment by edemirler** [comment]
Same issue here, cannot upload new files.
