### ISSUE TITLE
Adding more asset to candy machine after initial upload is failing

### ISSUE THREAD

**Issue by cdric** [metaplex-foundation/metaplex#884]
**Describe the bug**
I've uploaded and successfully verified the first set of assets to my candy machine.
I've successfully created and updated the candy machine.
I've minted all the tokens on the candy machine through the UI
When I'm trying to upload more assets I ran into an error when processing the indices

**To Reproduce**
```
ts-node js/packages/cli/src/candy-machine-cli.ts upload ../Assets/001 --env devnet --keypair ../SolanaWallet/wallet.json --log-level trace
ts-node js/packages/cli/src/candy-machine-cli.ts verify --env devnet --keypair ../SolanaWallet/wallet.json  --log-level trace
ts-node js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env devnet --keypair ../SolanaWallet/wallet.json  --price 0.01 --log-level trace
ts-node js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env devnet --keypair ../SolanaWallet/wallet.json --log-level trace --date "3 Nov 2021 08:00:00 UTC" --price 0.01
```
Then I mint all the tokens via the UI and the command is failing 
I delete the ../Assets/001 folder with the previous asset and I replace with additional ones

`ts-node js/packages/cli/src/candy-machine-cli.ts upload ../Assets/001 --env devnet --keypair ../SolanaWallet/wallet.json --log-level trace`

Log

```
ts-node js/packages/cli/src/candy-machine-cli.ts upload ../Assets/001 --env devnet --keypair ../SolanaWallet/wallet.json --log-level trace
setting the log value to: trace
Beginning the upload for 2 (png+json) pairs
started at: 1635926577716
wallet public key: [redacted]
program id from anchor cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ
Processing file: 0
Estimated manifest size: 248
Arweave cost estimates: {
  arweave: 0.000405954255,
  solana: 0.00014401336323612905,
  arweavePrice: 82.48,
  solanaPrice: 232.5,
  exchangeRate: 0.35475268817204303,
  byteCost: 353003700,
  totalBytes: 837275,
  fee: 52950555
}
lamport cost to store ../Assets/001/2.png: 144013.36323612905
Started awaiting confirmation for 5J69pwuKosWZzwb6YSCbPRRbf12K4Uhp4JGZWKvFTyYtGuZNKkPaRHuJd7PwwTt7jjbphuLjKvJC5sp8T9yPx6V7
REST confirmation for 5J69pwuKosWZzwb6YSCbPRRbf12K4Uhp4JGZWKvFTyYtGuZNKkPaRHuJd7PwwTt7jjbphuLjKvJC5sp8T9yPx6V7 {
  confirmationStatus: 'confirmed',
  confirmations: 1,
  err: null,
  slot: 91705171,
  status: { Ok: null }
}
Returning status {
  confirmationStatus: 'confirmed',
  confirmations: 1,
  err: null,
  slot: 91705171,
  status: { Ok: null }
}
Latency (ms) 5J69pwuKosWZzwb6YSCbPRRbf12K4Uhp4JGZWKvFTyYtGuZNKkPaRHuJd7PwwTt7jjbphuLjKvJC5sp8T9yPx6V7 1.4709999561309814
solana transaction (devnet) for arweave payment: {
  txid: '5J69pwuKosWZzwb6YSCbPRRbf12K4Uhp4JGZWKvFTyYtGuZNKkPaRHuJd7PwwTt7jjbphuLjKvJC5sp8T9yPx6V7',
  slot: 91705171
}
trying to upload 2.png: NFT #0003
File uploaded: https://arweave.net/aEGDFXx-q2CUmTvweFpz3vc1m6QRjChEGXpdD9wu7Rg
setting cache for  2
Processing file: 1
Estimated manifest size: 248
Arweave cost estimates: {
  arweave: 0.000738531633,
  solana: 0.0002619960821068387,
  arweavePrice: 82.48,
  solanaPrice: 232.5,
  exchangeRate: 0.35475268817204303,
  byteCost: 642201420,
  totalBytes: 1525841,
  fee: 96330213
}
lamport cost to store ../Assets/001/3.png: 261996.0821068387
Started awaiting confirmation for 2brHHXk5FNsTVeUSq9amDaqvcnmzA4JMX9Zb5KmxNwDUz5Zh1zcCQYM3EU2wcUSvRTCzQYcNPjVtttNi3qokaKq5
REST confirmation for 2brHHXk5FNsTVeUSq9amDaqvcnmzA4JMX9Zb5KmxNwDUz5Zh1zcCQYM3EU2wcUSvRTCzQYcNPjVtttNi3qokaKq5 {
  confirmationStatus: 'confirmed',
  confirmations: 2,
  err: null,
  slot: 91705220,
  status: { Ok: null }
}
Returning status {
  confirmationStatus: 'confirmed',
  confirmations: 2,
  err: null,
  slot: 91705220,
  status: { Ok: null }
}
Latency (ms) 2brHHXk5FNsTVeUSq9amDaqvcnmzA4JMX9Zb5KmxNwDUz5Zh1zcCQYM3EU2wcUSvRTCzQYcNPjVtttNi3qokaKq5 1.6519999504089355
solana transaction (devnet) for arweave payment: {
  txid: '2brHHXk5FNsTVeUSq9amDaqvcnmzA4JMX9Zb5KmxNwDUz5Zh1zcCQYM3EU2wcUSvRTCzQYcNPjVtttNi3qokaKq5',
  slot: 91705220
}
trying to upload 3.png: NFT #0004
File uploaded: https://arweave.net/rf-q8rhNNbwduPqTEItROwnQ6QNMcTP7AAriQ2QTtA8
setting cache for  3
Processing file: 2
Processing file: 3
Writing indices 0-3
Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 1211 out of range for slice of length 736', nft-candy-machine/src/lib.rs:320:18
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 1211 out of range for slice of length 736', nft-candy-machine/src/lib.rs:320:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
saving config line 0-3 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 1211 out of range for slice of length 736', nft-candy-machine/src/lib.rs:320:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}
Done. Successful = false.
upload was not successful, rerunning
```

**Expected behavior**
Either the candy machine doesn't support adding more asset and a clear error message should be displayed.
Or the upload of additional assets successfully complete

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS BigSur 11.6
 - Browser: Not relevant
 - Version: Not relevant

**Additional context**

Content on the asset folder on first asset upload
0.json
0.png
1.json
1.png

Content of the asset folder on second asset upload
2.json
2.png
3.json
3.png

**Comment by cdric** [comment]
After discussing this on the Metaplace Discord I've been told that this is a technical limitation. 

The explanation I was given was the following: "The config containing the URLs is stored in an Account. You need to specify the account size at creation of it. (in our case when upload starts) Since rent cost is based on the file size the candy machine chooses the smallest possible account size for your config to save you money."
