### ISSUE TITLE
Help error upload files to testnet and mainnet but not devnet

### ISSUE THREAD

**Issue by PabloHirsh** [metaplex-foundation/metaplex#916]
to the testnet or mainnet, in the devnet it works ok

my wallets are created in the corresponding networks

% metaplex upload ~ / candy_machine / TestProd --env testnet --keypair ~ / test_wallets / main2.json
Beginning the upload for 2 (png + json) pairs
started at: 1636264002872
wallet public key: ApK1pk32WX7X58hJVEYRuz2WAaAo9pfKtTk8xV3FGQeM
(node: 17917) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'state' of null
    at Function.parseIxLayout (/home/pablo/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:91:30)
    at new InstructionCoder (/home/pablo/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/instruction.ts:40:38)
    at new Coder (/home/pablo/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/coder/index.ts:46:24)
    at new Program (/home/pablo/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/index.ts:252:19)
    at Object. <anonymous> (/home/pablo/metaplex/js/packages/cli/src/helpers/accounts.ts:463:19)
    at step (/home/pablo/metaplex/js/packages/cli/src/helpers/accounts.ts:63:23)
    at Object.next (/home/pablo/metaplex/js/packages/cli/src/helpers/accounts.ts:44:53)
    at fulfilled (/home/pablo/metaplex/js/packages/cli/src/helpers/accounts.ts:35:58)
    at processTicksAndRejections (internal / process / task_queues.js: 95: 5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node: 17917) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch (). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections = strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node: 17917) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by truonggau** [comment]
same issue, did u resolve it?

**Comment by ladicz** [comment]
Same issue, but on testnet only. Imho problem is while loading candy machine program in (/home/pablo/metaplex/js/packages/cli/src/helpers/accounts.ts:463:19). 
For some reason I can see NFT Candy Machine program as not executable on testnet https://explorer.solana.com/address/cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ?cluster=testnet
while on devnet (and mainnet) it is executable https://explorer.solana.com/address/cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ?cluster=devnet

**Comment by HaoCherHong** [comment]
Hey it happens if updated (re-deployed) the rust programs. This project uses Anchor framework and it needs idl files for the cli.
So after you deploy the new rust program, you should also update the idl file on chain.

For example if you updated the candy machine program, you need to deploy the idl file also:
```shell
anchor idl init -f target/idl/nft_candy_machine_v2.json "your new program id" --provider.wallet ~/.config/solana/devnet.json
Idl account created: D7XC2SRCPt5zMGoZMR427MfRCF6FakJXtioxeoT9gYD2
```

Then you should be good to go.
