### ISSUE TITLE
Invalid ELF during upload

### ISSUE THREAD

**Issue by solanatreehouseclub** [metaplex-foundation/metaplex#938]
**Describe the bug**
When trying to upload using candy-machine-cli.ts an error `Error: /metaplex/js/node_modules/canvas/build/Release/canvas.node: invalid ELF header` is created

**To Reproduce**
1. Create a folder  /media/toupload with 10 .png and matching .json files
2. move the devnet.json file to /media/
2. run `ts-node candy-machine-cli.ts upload /media/toupload --env devnet --keypair /media/devnet.json -n 10`
3. See error

**Expected behavior**
The files should be uploaded without issue.

**Error**
```
sthc@DESKTOP-DCNAFLK:/mnt/c/Users/sthc/Documents/NFT Git Project/metaplex/js/packages/cli/src$ ts-node candy-machine-cli.ts upload /media/toupload --env devnet --keypair /media/devnet.json -n 10
Error: /mnt/c/Users/sthc/Documents/NFT Git Project/metaplex/js/node_modules/canvas/build/Release/canvas.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/mnt/c/Users/stlc/Documents/NFT Git Project/metaplex/js/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

**Desktop (please complete the following information):**
Ubuntu on WSL
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

**Comment by solanatreehouseclub** [comment]
As expected, was calling a windows release from linux....
