### ISSUE TITLE
A has_one constraint was violated on uploading

### ISSUE THREAD

**Issue by louisreberga** [metaplex-foundation/metaplex#945]
I have this error when I try to upload images...

Beginning the upload for 100 (png+json) pairs
started at: 1636640570795
wallet public key: 7aiDSFxkwr6MdjwzC85ydbvHRdaj6gYo4Nw5ctRvZU32
Processing file: 0
Processing file: 50
Processing file: 100
Processing file: 150
Processing file: 200
Writing indices 0-9
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: Custom program error: 0x8d
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 14934 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x8d
    at Connection.sendEncodedTransaction (/home/rebergalou/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/home/rebergalou/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/home/rebergalou/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/home/rebergalou/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as addConfigLines] (/home/rebergalou/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: Custom program error: 0x8d',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 14934 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x8d'
  ]
}
saving config line 0-9 failed ProgramError: 141: A has_one constraint was violated
    at Function.parse (/home/rebergalou/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/error.ts:41:14)
    at Object.rpc [as addConfigLines] (/home/rebergalou/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 141,
  msg: 'A has_one constraint was violated'
}

**Comment by kek4ok** [comment]
@louisreberga are u found how to fix it?
