### ISSUE TITLE
Yarn Build Issue

### ISSUE THREAD

**Issue by fivelions8** [metaplex-foundation/metaplex#957]
Was trying to follow a tutorial but run into this error, downgraded my node version and all but still couldn't do anything

$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 4 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in 'candy-machine-mint'
lerna ERR! yarn run build stdout:
$ react-scripts build
Creating an optimized production build...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\react-scripts\scripts\build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\ahmed\Desktop\Solana\metaplex-master\js\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'candy-machine-mint'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\ahmed\Desktop\Solana\metaplex-master\js> git checkout bf1bc27 -- js/yarn.lock
fatal: not a git repository (or any of the parent directories): .git

**Comment by spencercoder** [comment]
gettin same issue
