### ISSUE TITLE
create_candy_machine throws error

### ISSUE THREAD

**Issue by iLyadKD** [metaplex-foundation/metaplex#960]
**Describe the bug**
after running the create_candy_machine command, the following error is outputted:

```
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139 
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Custom program error: 0x139
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18798 of 200000 compute units
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x139
    at Connection.sendEncodedTransaction (/Users/farbod/Sites/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3553:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/Users/farbod/Sites/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:3513:20)
    at async sendAndConfirmRawTransaction (/Users/farbod/Sites/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-confirm-raw-transaction.ts:27:21)
    at async Provider.send (/Users/farbod/Sites/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/provider.ts:114:18)
    at async Object.rpc [as initializeCandyMachine] (/Users/farbod/Sites/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:19:23) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program 11111111111111111111111111111111 invoke [2]',
    'Program 11111111111111111111111111111111 success',
    'Program log: Custom program error: 0x139',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 18798 of 200000 compute units',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x139'
  ]
}
(node:18861) UnhandledPromiseRejectionWarning: Error: 313: Number of config lines must be at least number of items available
    at Function.parse (/Users/farbod/Sites/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/error.ts:35:14)
    at Object.rpc [as initializeCandyMachine] (/Users/farbod/Sites/metaplex/js/packages/cli/node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:23:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. run upload command (had some failed uploads, so we ran it again)
2. run the create_candy_machine command
3. See error

**Screenshots**

<img width="1054" alt="Screen Shot 2021-11-14 at 6 19 54 PM" src="https://user-images.githubusercontent.com/19579861/141686191-2b111df8-887a-497e-a177-e6da7ea196c2.png">

**Desktop:**
 - OS: MacOS Big Sur

**Comment by spencercoder** [comment]
how did you fix it?

**Comment by SeanOverton** [comment]
same issue?
