### ISSUE TITLE
Metaplex Candy Machine CLI | Custom program error: 0x135

### ISSUE THREAD

**Issue by 1Note-io** [metaplex-foundation/metaplex#983]
**Describe the bug**
I have set up a Linux server with metaplex candy machine CLI.
The first tests on the devnet work fine, only when I try to create my token on the mainnet it fails.

To be clear, I've re-executed these steps several times. My address with which I want to run the mint has 0.9 SOL (enough for a mint of a small image, at least as far as I know). On the devnet the CLI works perfectly and I receive my minted NFTs neatly.

**Commands that I use**
_//  Command 1.  Works fine_
ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts upload /var/www/html/images/images/ --env mainnet-beta --keypair /root/serverwallet/keypair.json --cache-name randomname123 --rpc-url https://api.mainnet-beta.solana.com

_//  Command 2. Works fine_
ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env mainnet-beta --keypair /root/serverwallet/keypair.json --cache-name randomname123 --rpc-url https://api.mainnet-beta.solana.com

_//  Command 3. Works fine_
ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts update_candy_machine --env mainnet-beta --date "now" --price 0 --keypair /root/serverwallet/keypair.json --cache-name randomname123 --rpc-url https://api.mainnet-beta.solana.com

_// Command 4. Doesn't work (get error back)_
ts-node ~/metaplex-foundation/metaplex/js/packages/cli/src/candy-machine-cli.ts mint_one_token --env mainnet-beta --keypair /root/serverwallet/keypair.json --cache-name randomname123 --rpc-url https://api.mainnet-beta.solana.com

**To Reproduce**
1. Download and Set Up Candy Machine CLI.
2. Run the commands above.
3. See error

**Expected behavior**
Expected outcome would not be an error. **All commands work flawlessly on the devnet**.

**Error log after command 4**
`wallet public key: E3hbETBkma9L8JLoh4erdns3ibfwpt9g5oTh9rVwi9HA
USING CUSTOM URL https://api.mainnet-beta.solana.com
REST error for 7NtEgsArJNTv4QkoBvHVp8sjAbfFc7UfcwnwGVRDPea3j45wkfDotfdb6B93Ac1KERgr46j7Q3j8YbjUYbyftT1 {
  confirmationStatus: 'processed',
  confirmations: 0,
  err: { InstructionError: [ 4, [Object] ] },
  slot: 107221941,
  status: { Err: { InstructionError: [Array] } }
}
Timeout Error caught { InstructionError: [ 4, { Custom: 309 } ] }
Rejected via websocket { InstructionError: [ 4, { Custom: 309 } ] }
(node:1471) UnhandledPromiseRejectionWarning: Error: Transaction failed: Custom program error: 0x135
    at /root/metaplex-foundation/metaplex/js/packages/cli/src/helpers/transactions.ts:136:19
    at step (/root/metaplex-foundation/metaplex/js/packages/cli/src/helpers/transactions.ts:33:23)
    at Object.next (/root/metaplex-foundation/metaplex/js/packages/cli/src/helpers/transactions.ts:14:53)
    at fulfilled (/root/metaplex-foundation/metaplex/js/packages/cli/src/helpers/transactions.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)`

Transaction on the mainnet:
https://solscan.io/tx/7NtEgsArJNTv4QkoBvHVp8sjAbfFc7UfcwnwGVRDPea3j45wkfDotfdb6B93Ac1KERgr46j7Q3j8YbjUYbyftT1

**System info:**
 - (Linux server) Ubuntu version: 20.04
 - candy-machine-cli version: 0.0.2

**Comment by 1Note-io** [comment]
Problem solved. For anyone with this problem, your mainnet wallet must have at least 1 SOL to guarantee the transaction.
